"""The expected answers of the ORACLE cases, computed by DuckDB.

    gen_expected.py <output directory> <data directory>

A `python_oracle` script (tools/build/python/README.md, Oracles). The data
directory holds the cases, `<shard>/<case>.sql`, staged from `oracle/`. Each
file is one SELECT, after a header of `--` lines:

    -- order: total | none | keys=<c1>,<c2>     (required)
    -- float: ulps=<n> | rel=<x>                 (optional; ulps=0)
    -- not null: <c1>, <c2>                      (optional; every other
                                                  column is nullable)

`order` and `float` are the comparison policy the expected file carries.
`not null` declares the columns the plan declares non-nullable (query
semantics §8, preamble: declared nullability is hand-derived, never read
from DuckDB, whose result types carry none); render.py refuses the
declaration if the column holds a NULL.

The tables a query names are the datasets of datasets.py (`types`, `nulls`,
`join_left`, `join_right`) and the HAND twins' inputs of twin_inputs.py
(`bool_pairs`, `ints_nullable`, `groups`, `sort_rows`), each built in Python
from its seed or its rows and handed to DuckDB as a pyarrow table: no file
is read back, and nothing komira wrote is an input.

DuckDB runs with `threads = 1`, `TimeZone = 'UTC'` and its defaults
otherwise (query semantics, preamble). Each query is first held to
sql_discipline.py (every ORDER BY key states ASC/DESC and NULLS FIRST/LAST,
every literal is CAST, no function on its list of those reading more than
their arguments (a clock, a random draw, the session, SQL text, the running
DuckDB), and FROM names only the tables registered here, with no AT
clause, its own CTEs and the allowed table functions), on the exact text that is then run. The result is rendered by render.py to

    <output directory>/expect/<shard>/<case>.tsv

with, after the policy lines, the line
`# GENERATED by gen_expected.py (duckdb <version>, pyarrow <version>) from oracle/<shard>/<case>.sql`.
"""

import os
import sys

import duckdb
import pyarrow as pa

import datasets
import oracle_case
import render
import sql_discipline
import twin_inputs


# Every table connect() registers: the only tables a case's FROM may name.
TABLES = list(datasets.NAMES) + list(twin_inputs.NAMES)


def connect():
    con = duckdb.connect(config={"threads": 1})
    con.execute("SET threads = 1")
    con.execute("SET TimeZone = 'UTC'")
    for name in datasets.NAMES:
        con.register(name, datasets.build(name).table)
    for name in twin_inputs.NAMES:
        if name in datasets.NAMES:
            raise oracle_case.CaseError("table %s is both a dataset and a twin input" % name)
        con.register(name, twin_inputs.build(name))
    return con


def run_query(con, sql):
    """Check `sql` and run that same text; the result as a pyarrow Table."""
    sql_discipline.check(con, sql, TABLES)
    res = con.execute(sql)
    if hasattr(res, "to_arrow_table"):
        table = res.to_arrow_table()
    else:
        table = res.fetch_arrow_table()
    if isinstance(table, pa.RecordBatchReader):
        table = table.read_all()
    return table


def generated_line(rel):
    return "GENERATED by gen_expected.py (duckdb %s, pyarrow %s) from oracle/%s" % (duckdb.__version__, pa.__version__, rel)


def cases(data):
    found = []
    for shard in sorted(os.listdir(data)):
        for f in sorted(os.listdir(os.path.join(data, shard))):
            if not f.endswith(".sql"):
                raise oracle_case.CaseError("%s/%s is not a .sql case" % (shard, f))
            found.append(shard + "/" + f)
    return found


def main(out, data):
    con = connect()
    for rel in cases(data):
        with open(os.path.join(data, rel), encoding="utf-8") as f:
            sql = f.read()
        try:
            policy, not_null = oracle_case.read_header(sql)
            table = run_query(con, sql)
            text = render.render_table(table, policy, [generated_line(rel)], not_null)
        except Exception as e:
            raise oracle_case.CaseError("oracle/%s: %s" % (rel, e)) from e
        dest = os.path.join(out, "expect", rel[: -len(".sql")] + ".tsv")
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)


main(sys.argv[1], sys.argv[2])
