"""The expected answers of the ORACLE cases, computed by DuckDB.

    gen_expected.py <output directory> <data directory>

A `python_oracle` script (tools/build/python/README.md, Oracles). The data
directory holds the cases, `<shard>/<case>.sql`, staged from `oracle/`. Each
file is one SELECT, after a header of `--` lines:

    -- order: total | none | keys=<c1>,<c2>     (required)
    -- float: ulps=<n> | rel=<x>                 (optional; ulps=0)
    -- not null: <c1>, <c2>                      (optional; every other
                                                  column is nullable)

`order` and `float` are the comparison policy the expected file carries.
`not null` declares the columns the plan declares non-nullable (query
semantics §8, preamble: declared nullability is hand-derived, never read
from DuckDB, whose result types carry none); render.py refuses the
declaration if the column holds a NULL.

The tables a query names are the datasets of datasets.py (`types`, `nulls`,
`join_left`, `join_right`) and the HAND twins' inputs of twin_inputs.py
(`bool_pairs`, `ints_nullable`, `groups`, `sort_rows`), each built in Python
from its seed or its rows and handed to DuckDB as a pyarrow table: no file
is read back, and nothing komira wrote is an input.

DuckDB runs with `threads = 1`, no extension autoloaded or autoinstalled,
no external access (CONFIG, set when the database opens), `TimeZone =
'UTC'` and `Calendar = 'gregorian'` (set right after, before any query) and
its defaults otherwise (query semantics, preamble): ICU takes its default
TimeZone and Calendar from the process's TZ and locale, so both are pinned. Each query is first held to
sql_discipline.py (every ORDER BY key states ASC/DESC and NULLS FIRST/LAST,
every literal is CAST, no function on its list of those reading more than
their arguments (a clock, a random draw, the session, SQL text, the running
DuckDB), no aggregate whose answer depends on the order rows reach it
(`list`, `string_agg`, `first`...) without an ORDER BY of its own, no
window ROWS frame without an OVER ORDER BY, no LIMIT, OFFSET or DISTINCT
ON without an ORDER BY in its query, no FLOAT or DOUBLE histogram, no
`list_sort` that leaves its direction or NULL placement to the session,
and FROM names only the tables registered here, with no AT clause, its own
CTEs and the allowed table functions), on the exact text that is then run,
and to its policy (sql_discipline.check_order_policy: under `order:
total` the outermost query has an ORDER BY, under `keys=<cols>` one that
leads with exactly those columns), so that no file freezes the order
DuckDB happens to write the rows in.

Then the row-order check (row_order_diffs): the case runs again once per
order of case_orders(), on a connection of its own that registers the
tables the case names again with their rows in that order (register()), and each answer must equal
the first under the case's policy (canon.compare: a multiset under
`order: none`, row for row under `total`, key order with runs of equal
keys as multisets under `keys`; floats within the tolerance). The orders
are every rotation of each table and the reverse of every rotation
(permutation()), so every row of every table the case reads arrives
first in some order and last in some order, and so does every row of any
subset of a table (the rows a WHERE keeps, a group): the check sees any
answer that depends on which row of a table arrives first or which
arrives last, ties among ORDER BY keys and the sign of a zero that min,
max, a GROUP BY or DISTINCT key or a LIMIT over tied keys keeps
included. It does not see every dependence on the order of rows in the
middle (all n! orders), nor one that needs two tables in a combination
of orders no index i gives (each order rotates every table by i modulo
its own size).

The result is rendered by render.py to

    <output directory>/expect/<shard>/<case>.tsv

with, after the policy lines, the line
`# GENERATED by gen_expected.py (duckdb <version>, pyarrow <version>) from oracle/<shard>/<case>.sql`.
"""

import os
import sys

import duckdb
import pyarrow as pa

import canon
import datasets
import oracle_case
import render
import sql_discipline
import twin_inputs


# Every table connect() registers: the only tables a case's FROM may name.
TABLES = list(datasets.NAMES) + list(twin_inputs.NAMES)


# Fixed when the database opens, before the first query. DuckDB 1.5.6 loads
# an extension it knows (inet's html_escape(), the INET type, a `.sqlite`
# path) the first time a query names something it holds, unless
# autoload_known_extensions is off, and downloads it first unless
# autoinstall_known_extensions is off; with enable_external_access off it
# loads no extension by any path and reads no file and no Python variable
# a query names, and a running database refuses to turn it back on. What
# answers a case is then the wheel and the tables registered here.
CONFIG = {
    "threads": 1,
    "autoload_known_extensions": False,
    "autoinstall_known_extensions": False,
    "enable_external_access": False,
}


# The kinds of order of the row-order check (row_order_diffs): an order is
# (kind, i), a table's rows rotated by i, and that rotation reversed.
ORDER_KINDS = ("rotated", "reversed")

_BUILT = {}


def tables():
    """Every table connect() registers, by name, each built once per process."""
    if not _BUILT:
        for name in datasets.NAMES:
            _BUILT[name] = datasets.build(name).table
        for name in twin_inputs.NAMES:
            if name in _BUILT:
                raise oracle_case.CaseError("table %s is both a dataset and a twin input" % name)
            _BUILT[name] = twin_inputs.build(name)
    return _BUILT


def permutation(n, order):
    """The row indices of a table of `n` rows in row order `order`, a
    (kind, i) pair: ("rotated", i) is rows i mod n to n - 1, then 0 to
    i mod n - 1; ("reversed", i) is that, reversed."""
    kind, i = order
    if kind not in ORDER_KINDS:
        raise ValueError("row order %r is not one of %s" % (kind, ORDER_KINDS))
    k = i % n if n else 0
    idx = list(range(k, n)) + list(range(k))
    if kind == "reversed":
        idx.reverse()
    return idx


def row_orders(n):
    """The orders of the row-order check for tables of at most `n` rows:
    every rotation but the identity, and the reverse of every rotation,
    2n - 1 orders. Over i < n every table of m <= n rows takes each of its
    m rotations: row r arrives first rotated by r and last rotated by r +
    1, and the reverse of each rotation runs the other way round."""
    return [("rotated", i) for i in range(1, n)] + [("reversed", i) for i in range(n)]


def order_name(order):
    kind, i = order
    return "rotated by %d" % i if kind == "rotated" else "rotated by %d and reversed" % i


def case_orders(con, sql):
    """row_orders() of the largest table `sql` names: the orders under
    which the row-order check runs it."""
    built = tables()
    n = max([built[t].num_rows for t in sql_discipline.tables_read(con, sql) if t in built] + [0])
    return row_orders(n)


def connect(order=None, names=None):
    """The oracle's connection, every table registered (with `names`,
    those tables only); with `order` (a (kind, i) pair, permutation()),
    each table holds the same rows in that order."""
    con = duckdb.connect(config=CONFIG)
    con.execute("SET threads = 1")
    # ICU (in the wheel) takes its default TimeZone from the process's TZ
    # and its default Calendar from its locale when it loads
    # (icu_extension.cpp, LoadInternal): under LC_ALL=th_TH.UTF-8 the
    # Calendar is `buddhist`, and date_part('year', ...) of a TIMESTAMPTZ in
    # 2026 answers 2569. Both are set here, before the first query: the
    # wheel refuses `Calendar` in the config DuckDB opens with ("options
    # were not recognized").
    con.execute("SET TimeZone = 'UTC'")
    con.execute("SET Calendar = 'gregorian'")
    register(con, order, names)
    return con


def register(con, order=None, names=None):
    """Register on `con` every table (with `names`, those tables only), with
    `order` (a (kind, i) pair, permutation()) in that row order. A name
    registered before is replaced (duckdb-python's RegisterPythonObject
    creates the view with replace set when it registered the name), so the
    row-order check reorders one connection rather than opening one per
    order, which costs tens of milliseconds each."""
    for name, table in tables().items():
        if names is not None and name not in names:
            continue
        if order is not None:
            table = table.take(pa.array(permutation(table.num_rows, order), type=pa.int64()))
        con.register(name, table)


def execute(con, sql):
    """Run `sql` as it is, unchecked; the result as a pyarrow Table."""
    res = con.execute(sql)
    if hasattr(res, "to_arrow_table"):
        table = res.to_arrow_table()
    else:
        table = res.fetch_arrow_table()
    if isinstance(table, pa.RecordBatchReader):
        table = table.read_all()
    return table


def run_query(con, sql):
    """Check `sql` and run that same text; the result as a pyarrow Table."""
    sql_discipline.check(con, sql, TABLES)
    return execute(con, sql)


def row_order_diffs(orders, sql, policy, not_null, text):
    """Every difference between `text` (the case's answer, rendered) and
    the answer of the same `sql` with the tables it names registered in
    each order of `orders` in turn (register(), on one connection of its
    own), compared as
    canon.compare compares a result with its expectation under the case's
    `policy`: as a multiset (`none`), row for row (`total`), or in key
    order with each run of equal keys as a multiset (`keys`), floats
    within the policy's tolerance. [] when every order gives the same
    answer."""
    want = canon.parse(text)
    con = connect(names=())
    names = sql_discipline.tables_read(con, sql)
    diffs = []
    try:
        for order in orders:
            register(con, order, names)
            got = canon.parse(render.render_table(execute(con, sql), policy, (), not_null))
            diffs += ["rows %s: %s" % (order_name(order), d) for d in canon.compare(want, got)]
    finally:
        con.close()
    return diffs


def generated_line(rel):
    return "GENERATED by gen_expected.py (duckdb %s, pyarrow %s) from oracle/%s" % (duckdb.__version__, pa.__version__, rel)


def cases(data):
    found = []
    for shard in sorted(os.listdir(data)):
        for f in sorted(os.listdir(os.path.join(data, shard))):
            if not f.endswith(".sql"):
                raise oracle_case.CaseError("%s/%s is not a .sql case" % (shard, f))
            found.append(shard + "/" + f)
    return found


def main(out, data):
    con = connect()
    for rel in cases(data):
        with open(os.path.join(data, rel), encoding="utf-8") as f:
            sql = f.read()
        try:
            policy, not_null = oracle_case.read_header(sql)
            sql_discipline.check_order_policy(con, sql, policy.order, policy.keys)
            table = run_query(con, sql)
            text = render.render_table(table, policy, [generated_line(rel)], not_null)
            diffs = row_order_diffs(case_orders(con, sql), sql, policy, not_null, text)
            if diffs:
                raise oracle_case.CaseError("the answer depends on the order of the tables' rows, not only on "
                                            "their contents: " + "; ".join(diffs))
        except Exception as e:
            raise oracle_case.CaseError("oracle/%s: %s" % (rel, e)) from e
        dest = os.path.join(out, "expect", rel[: -len(".sql")] + ".tsv")
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
