"""The oracle's generated expectations: well formed, and equal to their HAND twins.

    test_expected.py <the :expected output directory>

In a process of its own (nothing gen_expected.py computed is reused):

1. Every case `oracle/<shard>/<case>.sql` has exactly one generated file
   `expect/<shard>/<case>.tsv`, and nothing else was generated.
2. Each generated file parses as komira_plan_harness's canonical text
   (canon.py: header, schema line, every cell against its column's type),
   is in canonical form (`emit(parse(text)) == text`: every float carries
   its bits, NULL is `\\N`), carries the policy its `.sql` header declares,
   and its first comment line is
   `# GENERATED by gen_expected.py (duckdb <v>, pyarrow <v>) from oracle/<shard>/<case>.sql`
   with the versions this process imports (the pinned wheels).
3. Every case is the twin of a HAND case: its expectation equals the HAND
   expectation `twins/hand/<shard>/<case>.tsv` (a copy of
   komira_plan_conformance's `expect/<shard>/<case>.tsv`) under the HAND
   file's policy, which must also be the ORACLE file's (canon.compare). A
   difference is a defect in the oracle SQL, in the HAND derivation, or in
   the query semantics document; every difference is reported.
4. The twins' inputs (twin_inputs.py) are the HAND cases' inputs: each
   table equals `twins/inputs/<name>.jsonl` (a copy of the corpus's
   dataset) read with pyarrow under the table's own schema, cell for cell
   as render.py writes them (so -0.0 and 0.0 differ).
"""

import os
import sys

import duckdb
import pyarrow as pa
import pyarrow.json as pajson

import canon
import oracle_case
import render
import twin_inputs

HERE = os.path.dirname(os.path.abspath(__file__))
FAILURES = []


def fail(msg):
    FAILURES.append(msg)


def listing(root, suffix):
    out = []
    for dirpath, _, files in os.walk(root):
        for f in files:
            rel = os.path.relpath(os.path.join(dirpath, f), root)
            if not rel.endswith(suffix):
                fail("%s: %s is not a %s file" % (root, rel, suffix))
                continue
            out.append(rel[: -len(suffix)])
    return sorted(out)


def read(path):
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def check_generated(expected_dir):
    cases = listing(os.path.join(HERE, "oracle"), ".sql")
    generated = listing(os.path.join(expected_dir, "expect"), ".tsv")
    if cases != generated:
        fail("cases %s, generated %s" % (cases, generated))
    if not cases:
        fail("no ORACLE case")
    hands = listing(os.path.join(HERE, "twins", "hand"), ".tsv")
    if hands != cases:
        fail("HAND twins %s, ORACLE cases %s: every case has exactly one twin" % (hands, cases))
    for case in cases:
        path = os.path.join(expected_dir, "expect", case + ".tsv")
        if not os.path.exists(path):
            continue
        text = read(path)
        try:
            got = canon.parse(text)
        except ValueError as e:
            fail("%s: does not parse: %s" % (case, e))
            continue
        if canon.emit(got) != text:
            fail("%s: not in canonical form:\n%s---- canonical:\n%s" % (case, text, canon.emit(got)))
        want_line = "# GENERATED by gen_expected.py (duckdb %s, pyarrow %s) from oracle/%s.sql" % (
            duckdb.__version__, pa.__version__, case)
        if got.comments[:1] != [want_line]:
            fail("%s: comment lines %r, want first %r" % (case, got.comments, want_line))
        policy, _ = oracle_case.read_header(read(os.path.join(HERE, "oracle", case + ".sql")))
        head = text.split("\n")[1 : 3 + len(policy.overrides)]
        if head != policy.header_lines()[1:]:
            fail("%s: policy lines %r, the .sql declares %r" % (case, head, policy.header_lines()[1:]))
        twin = os.path.join(HERE, "twins", "hand", case + ".tsv")
        if not os.path.exists(twin):
            continue
        try:
            hand = canon.parse(read(twin))
        except ValueError as e:
            fail("%s: the HAND twin does not parse: %s" % (case, e))
            continue
        diffs = canon.compare(hand, got)
        if diffs:
            fail("%s: ORACLE differs from HAND:\n  %s\n---- ORACLE:\n%s---- HAND:\n%s" % (
                case, "\n  ".join(diffs), text, read(twin)))
        else:
            print("ok %s: ORACLE equals HAND (%d rows, order %s)" % (case, len(got.rows), hand.order))


def check_twin_inputs():
    inputs = listing(os.path.join(HERE, "twins", "inputs"), ".jsonl")
    if inputs != twin_inputs.NAMES:
        fail("twins/inputs holds %s, twin_inputs.py %s" % (inputs, twin_inputs.NAMES))
    for name in twin_inputs.NAMES:
        want = twin_inputs.build(name)
        path = os.path.join(HERE, "twins", "inputs", name + ".jsonl")
        if not os.path.exists(path):
            continue
        got = pajson.read_json(path, parse_options=pajson.ParseOptions(
            explicit_schema=want.schema, unexpected_field_behavior="error"))
        got = got.select(want.column_names).cast(want.schema)
        policy = render.Policy("total")
        if render.render_table(got, policy) != render.render_table(want, policy):
            fail("twin input %s: twin_inputs.py differs from %s:\n%s----\n%s" % (
                name, path, render.render_table(want, policy), render.render_table(got, policy)))


check_generated(sys.argv[1])
check_twin_inputs()
if FAILURES:
    for f in FAILURES:
        print("FAIL", f)
    raise SystemExit("test_expected: %d failures" % len(FAILURES))
print("test_expected: all passed")
