"""The unit census: every build target the per-change check must reach.

  python3 release/ci/unit_census.py --check   # exit 1 when a target is in no unit
  python3 release/ci/unit_census.py --write   # regenerate the checks of release/artifacts.textproto

The per-change check (`kci run --stage pr --affected-by <base>`) builds units
of release/artifacts.textproto: artifacts and checks. An artifact names the
exact labels it is built from; a check names buck2 target PATTERNS
(`//src/<p>/...`, `//:`), which buck2 resolves when the check is built. A new
target in a package a check's pattern covers is in that check with no edit.

The universe is `//...` and `tests//functional/...` (what `./buck2 build //...`
and `./buck2 build tests//functional/...` build), configured for the default
target platform, as `buck2 cquery` sees it: a target incompatible with that
platform is not in it. It is read from the live graph on every run; no list of
it is kept in the tree.

--check refuses a target of the universe that no unit names or matches, and a
check pattern that matches no target of the universe (it names a package that
is gone). For each target in no unit it prints the check its path maps to.
Naming a target that DEPENDS on another is not enough: buck2 builds only the
outputs a dependent consumes, so a library's conda package does not build the
library's own default output, and with it the library's welded tests. The pr
job of .github/workflows/kci.yml runs --check before `kci run`.

--write rewrites the checks of release/artifacts.textproto (everything from
the CHECKS_MARKER line to the end of the file) from the live graph, grouped by
path (check_name). Run it when a package is added or removed.

The welded test src/kci_artifact/tests/test_release_artifacts_file.mojo holds
the checks' shape: each names patterns only, and no package is in two checks.

`buck2` is found on PATH, or set BUCK2 (e.g. BUCK2=./buck2).
"""

import os
import re
import subprocess
import sys

UNIVERSE = ["//...", "tests//functional/..."]
ARTIFACTS = "release/artifacts.textproto"
CHECKS_MARKER = "# The checks (THE CHECKS, above): built by the per-change check only, never"
CHECKS_HEADER = """\
# The checks (THE CHECKS, above): built by the per-change check only, never
# shipped. Generated by `python3 release/ci/unit_census.py --write` from the
# live graph: one check per path group, each naming buck2 target patterns.
"""


def _label(configured):
    """`komira//a:b (cfg)` -> `//a:b`; `tests//a:b (cfg)` -> `tests//a:b`."""
    lab = configured.split(" (")[0].strip()
    if lab.startswith("komira//"):
        lab = lab[len("komira"):]
    return lab


def _buck2(args):
    exe = os.environ.get("BUCK2", "buck2")
    out = subprocess.run([exe] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if out.returncode != 0:
        sys.stderr.write(out.stderr)
        raise SystemExit("unit_census.py: buck2 %s failed (exit %d)" % (" ".join(args), out.returncode))
    return out.stdout


def universe():
    """Every target of the universe, from the live graph, sorted."""
    labels = {_label(l) for l in _buck2(["cquery", " + ".join(UNIVERSE)]).splitlines() if l.strip()}
    if not labels:
        raise SystemExit("unit_census.py: the universe is empty; it cannot be")
    return sorted(labels)


def _split(label):
    """`<cell>//<pkg>:<name>` -> (cell, pkg, name)."""
    cell, _, rest = label.partition("//")
    pkg, _, name = rest.partition(":")
    return cell, pkg, name


def is_pattern(t):
    """`<cell>//<path>/...` (a package and every package below it) or
    `<cell>//<path>:` (the targets of one package; `//:` is the root's)."""
    if "//" not in t:
        return False
    if t.endswith("/..."):
        return len(t.split("//", 1)[1]) > len("/...")
    return t.endswith(":") and ":" not in t[:-1]


def matches(t, label):
    """A unit's target `t` (a pattern or an exact label) names `label`."""
    if not is_pattern(t):
        return t == label
    cell, pkg, _ = _split(label)
    if t.endswith("/..."):
        pcell, _, root = t[: -len("/...")].partition("//")
        return cell == pcell and (pkg == root or pkg.startswith(root + "/"))
    pcell, _, root = t[:-1].partition("//")
    return cell == pcell and pkg == root


def units(path=ARTIFACTS):
    """[(kind, name, [targets])] of the artifacts and checks of the file."""
    out = []
    kind = None
    for line in open(path):
        s = line.strip()
        m = re.match(r"^(artifacts|checks) \{$", line.rstrip())
        if m:
            kind = m.group(1)
            out.append([kind, None, []])
            continue
        if line.startswith("}"):
            kind = None
            continue
        if kind is None:
            continue
        m = re.match(r'^name: "([^"]+)"$', s)
        if m and out[-1][1] is None:
            out[-1][1] = m.group(1)
        m = re.match(r'^targets: "([^"]+)"$', s)
        if m:
            out[-1][2].append(m.group(1))
    return out


def check_name(label, artifacts=frozenset()):
    """The check a target maps to (the grouping by path): `//src/<p>/...` ->
    `<p>` (one check per library package), the root package -> `repo_root`,
    `//tools/<t>/...` -> `tools_<t>`, any other `//<d>/...` -> `<d>`, the
    tests cell -> `functional_tests`; `-` and `.` become `_`. A name an
    artifact holds gets `_package` (the rest of that artifact's package):
    artifacts and checks are one name space."""
    cell, pkg, _ = _split(label)
    if cell == "tests":
        return "functional_tests"
    parts = pkg.split("/")
    if parts == [""]:
        return "repo_root"
    if parts[0] == "src" and len(parts) > 1:
        name = parts[1]
    elif parts[0] == "tools" and len(parts) > 1:
        name = "tools_" + parts[1]
    else:
        name = parts[0]
    name = re.sub(r"[.-]", "_", name)
    if name in artifacts:
        name += "_package"
    return name


def group_pattern(label):
    """The pattern of `label`'s path group (check_name's grouping)."""
    cell, pkg, _ = _split(label)
    if cell == "tests":
        return UNIVERSE[1]
    parts = pkg.split("/")
    if parts == [""]:
        return "//:"
    if parts[0] in ("src", "tools"):
        if len(parts) == 1:
            return "//%s:" % parts[0]
        return "//%s/%s/..." % (parts[0], parts[1])
    return "//%s/..." % parts[0]


def generated_checks(labels, artifacts):
    """{check name: sorted patterns} for the labels."""
    groups = {}
    for lab in labels:
        groups.setdefault(check_name(lab, artifacts), set()).add(group_pattern(lab))
    return {n: sorted(p) for n, p in groups.items()}


def render_checks(checks):
    out = [CHECKS_HEADER]
    for name in sorted(checks, key=lambda n: (checks[n][0].startswith("tests//"), checks[n][0])):
        out.append("checks {\n")
        out.append('  name: "%s"\n' % name)
        out.append('  build_system: "buck2"\n')
        for p in checks[name]:
            out.append('  targets: "%s"\n' % p)
        out.append("}\n")
    return "".join(out)


def write(path=ARTIFACTS):
    text = open(path).read()
    at = text.find(CHECKS_MARKER)
    if at < 0:
        raise SystemExit("unit_census.py: %s has no line '%s'" % (path, CHECKS_MARKER))
    arts = {u[1] for u in units(path) if u[0] == "artifacts"}
    checks = generated_checks(universe(), arts)
    with open(path, "w") as f:
        f.write(text[:at] + render_checks(checks))
    print("unit_census.py: wrote %d checks to %s" % (len(checks), path))


def check(path=ARTIFACTS):
    all_units = units(path)
    arts = {u[1] for u in all_units if u[0] == "artifacts"}
    labels = universe()
    bad = 0
    for lab in labels:
        if not any(matches(t, lab) for u in all_units for t in u[2]):
            print("IN NO UNIT %s (its check: %s, pattern %s)" % (lab, check_name(lab, arts), group_pattern(lab)))
            bad += 1
    for kind, name, targets in all_units:
        if kind != "checks":
            continue
        for t in targets:
            if not is_pattern(t):
                print("NOT A PATTERN %s (check %s)" % (t, name))
                bad += 1
            elif not any(matches(t, lab) for lab in labels):
                print("MATCHES NOTHING %s (check %s)" % (t, name))
                bad += 1
    if bad:
        print("unit_census.py: %d finding(s): run python3 release/ci/unit_census.py --write" % bad)
        return 1
    print("unit_census.py: every target of the universe is in a unit (%d targets, %d units)" % (len(labels), len(all_units)))
    return 0


def main(argv):
    if len(argv) != 2 or argv[1] not in ("--write", "--check"):
        sys.stderr.write(__doc__)
        return 2
    if argv[1] == "--write":
        write()
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main(sys.argv))
