# =============================================================================
# komira_plan_conformance/corpus.mojo -- the checks every case must pass
# before any engine runs it.
# =============================================================================
#
# Nothing in this repository executes a logical plan yet, so these checks are
# what holds the corpus together until it can run. Each returns the problems
# it found as lines naming the case (`<shard>/<id>`) or the file, and
# `check_corpus` gathers all of them: one bad case never hides another.
#
#   check_partition   every case is registered through exactly one shard's
#                     list, the shard it names, and that shard exists.
#   check_files       every case has exactly one expectation file
#                     (expect/<shard>/<id>.tsv, or .err for ERROR), and every
#                     file under expect/ belongs to exactly one case.
#   check_wire        the plan builds; plan_to_bytes encodes it;
#                     plan_wire_admit accepts the bytes; plan_wire_check_values
#                     accepts the built plan; plan_from_bytes decodes it; the
#                     decoded plan has the same structural hash and the same
#                     root output schema (the hash does not cover schemas).
#   check_expectation the file parses; a HAND file carries a `# derivation:`
#                     comment citing a query-semantics item (§) and no
#                     GENERATED mark, an ORACLE file's first comment line is
#                     `# GENERATED by`; its order/float header equals the
#                     case's policy; every cell is a value of its column's
#                     type (check_cells); and its schema line equals the
#                     plan's root output schema. On that last point the EXPECTATION is the
#                     authority: its types come from the semantics document's
#                     result-type table, so a mismatch names both sides and is
#                     a question for review, never a cue to copy the plan.
#   check_dataset     a dataset file matches the schema its cases declare;
#                     every file under datasets/ is a registered dataset.
# =============================================================================

from std.os import listdir
from std.os.path import exists, isdir
from std.pathlib import Path

from komira_arrow.arrow_types import ArrowType
from komira_arrow.schema import Schema
from komira_json import parse_json_value
from komira_plan_harness import CanonText, parse_canon
from komira_plan_harness.type_text import arrow_type_name, schema_entry_of_field
from komira_plan_ir.logical_plan import LogicalPlan
from komira_plan_wire import (
    plan_from_bytes,
    plan_to_bytes,
    plan_wire_admit,
    plan_wire_check_values,
    plan_wire_supported_versions,
)

from .plan_case import (
    DATASET_DIR,
    EXPECT_DIR,
    EXPECT_ERROR,
    EXPECT_HAND,
    EXPECT_ORACLE,
    Case,
    Dataset,
    expect_kind_name,
    parse_err,
)
from .datasets import all_datasets
from .registry import Registered, registered_cases, shard_names


def schema_entries(schema: Schema) raises -> List[String]:
    """The canonical-text schema entries (`name:type[?]`) of `schema`."""
    var res = List[String]()
    for i in range(schema.num_columns()):
        res.append(schema_entry_of_field(schema.field_at(i)))
    return res^


def _joined(xs: List[String]) -> String:
    var s = String()
    for i in range(len(xs)):
        if i > 0:
            s += " | "
        s += xs[i]
    return s^


def _contains(xs: List[String], x: String) -> Bool:
    for y in xs:
        if y == x:
            return True
    return False


# -----------------------------------------------------------------------------
# Partition: every case in exactly one shard
# -----------------------------------------------------------------------------


def check_partition(regs: List[Registered], shards: List[String]) -> List[String]:
    var problems = List[String]()
    for i in range(len(shards)):
        for j in range(i):
            if shards[i] == shards[j]:
                problems.append("partition: shard '" + shards[i] + "' is listed twice")
    for r in regs:
        if not _contains(shards, r.entry.shard):
            problems.append(
                "partition: " + r.entry.label() + " names shard '"
                + r.entry.shard + "', which is not a shard"
            )
        if r.entry.shard != r.registered_in:
            problems.append(
                "partition: " + r.entry.label() + " is registered in shard '"
                + r.registered_in + "' but names shard '" + r.entry.shard + "'"
            )
        if r.entry.id.byte_length() == 0 or r.entry.id.find("/") >= 0:
            problems.append(
                "partition: case id '" + r.entry.id + "' in shard '"
                + r.registered_in + "' is empty or holds a '/'"
            )
    # The same id registered more than once, in any shards.
    for i in range(len(regs)):
        var first = True
        for j in range(i):
            if regs[j].entry.id == regs[i].entry.id:
                first = False
                break
        if not first:
            continue
        var where = List[String]()
        for j in range(i, len(regs)):
            if regs[j].entry.id == regs[i].entry.id:
                where.append(regs[j].registered_in)
        if len(where) > 1:
            var s = String()
            for k in range(len(where)):
                if k > 0:
                    s += ", "
                s += where[k]
            problems.append(
                "partition: case '" + regs[i].entry.id + "' is registered "
                + String(len(where)) + " times, in shards " + s
                + "; a case belongs to exactly one shard"
            )
    return problems^


# -----------------------------------------------------------------------------
# Files: one expectation per case, no orphans
# -----------------------------------------------------------------------------


def check_files(cases: List[Case], files: List[String]) -> List[String]:
    """`files` are paths under the data root (`expect/<shard>/<name>`), every
    file found under expect/."""
    var problems = List[String]()
    for c in cases:
        var want = c.expect_file()
        var stem = String(EXPECT_DIR) + "/" + c.shard + "/" + c.id + "."
        var hits = 0
        var others = List[String]()
        for f in files:
            if f == want:
                hits += 1
            elif f.startswith(stem):
                others.append(f)
        if hits == 0:
            problems.append(
                "files: " + c.label() + " (" + expect_kind_name(c.expect)
                + ") has no expectation file " + want
            )
        for o in others:
            problems.append(
                "files: " + c.label() + " has a second expectation file " + o
                + " beside " + want + "; a case has exactly one"
            )
    for f in files:
        var owners = 0
        for c in cases:
            if c.expect_file() == f:
                owners += 1
        if owners == 0:
            var claimed = False
            for c in cases:
                if f.startswith(String(EXPECT_DIR) + "/" + c.shard + "/" + c.id + "."):
                    claimed = True
            if not claimed:
                problems.append(
                    "files: " + f + " is an orphan: no registered case owns it"
                    + " (expect/<shard>/<case id>.tsv, or .err for ERROR)"
                )
        elif owners > 1:
            problems.append("files: " + f + " is owned by " + String(owners) + " cases")
    return problems^


def list_expect_files(root: String) raises -> List[String]:
    """Every file under <root>/expect, as `expect/<shard>/<name>`; a file
    directly under expect/ is listed as `expect/<name>` (always an orphan)."""
    var res = List[String]()
    var top = root + "/" + EXPECT_DIR
    if not exists(top):
        return res^
    for d in listdir(top):
        var dir_path = top + "/" + d
        if isdir(dir_path):
            for f in listdir(dir_path):
                res.append(String(EXPECT_DIR) + "/" + d + "/" + f)
        else:
            res.append(String(EXPECT_DIR) + "/" + d)
    return res^


# -----------------------------------------------------------------------------
# Wire: build, encode, admit, check values, decode, round trip
# -----------------------------------------------------------------------------


def check_wire(c: Case, mut problems: List[String]) -> Optional[LogicalPlan]:
    """Run every wire leg; return the built plan when it built."""
    var plan: LogicalPlan
    try:
        plan = c.build()
    except e:
        problems.append("wire: " + c.label() + ": the plan does not build: " + String(e))
        return None
    var bytes: List[UInt8]
    try:
        bytes = plan_to_bytes(plan)
    except e:
        problems.append("wire: " + c.label() + ": plan_to_bytes refused it: " + String(e))
        return plan^
    try:
        plan_wire_admit(bytes, plan_wire_supported_versions())
    except e:
        problems.append("wire: " + c.label() + ": plan_wire_admit refused its bytes: " + String(e))
    try:
        plan_wire_check_values(plan)
    except e:
        problems.append("wire: " + c.label() + ": plan_wire_check_values refused the built plan: " + String(e))
    try:
        var decoded = plan_from_bytes(bytes.copy())
        if decoded.structural_hash() != plan.structural_hash():
            problems.append(
                "wire: " + c.label() + ": the structural hash changed in the"
                + " round trip:\n  built:   " + String(plan)
                + "\n  decoded: " + String(decoded)
            )
        var want = schema_entries(plan.output_schema)
        var got = schema_entries(decoded.output_schema)
        if want != got:
            problems.append(
                "wire: " + c.label() + ": the root output schema changed in the"
                + " round trip: built [" + _joined(want) + "], decoded ["
                + _joined(got) + "]"
            )
    except e:
        problems.append("wire: " + c.label() + ": plan_from_bytes refused its bytes: " + String(e))
    return plan^


# -----------------------------------------------------------------------------
# The expectation file
# -----------------------------------------------------------------------------


def _header(c: CanonText) -> String:
    var s = String()
    c.policy.write_header(s)
    return s^


def check_schema(label: String, expected: List[String], plan_schema: List[String]) -> List[String]:
    """The expectation's schema against the plan's root output schema. The
    expectation is the authority on types (query semantics §8); the message
    names both sides and asks for a review, not a copy."""
    var problems = List[String]()
    var tail = String(
        " The expected types come from the query-semantics result-type table"
        " (§8); decide in review which side is wrong."
    )
    if len(expected) != len(plan_schema):
        problems.append(
            "schema: " + label + ": the expectation has " + String(len(expected))
            + " columns [" + _joined(expected) + "], the plan's root output"
            + " schema has " + String(len(plan_schema)) + " ["
            + _joined(plan_schema) + "]." + tail
        )
        return problems^
    for i in range(len(expected)):
        if expected[i] != plan_schema[i]:
            problems.append(
                "schema: " + label + ": column " + String(i) + ": the"
                + " expectation says `" + expected[i] + "`, the plan's root"
                + " output schema says `" + plan_schema[i] + "`." + tail
            )
    return problems^


def _free_comments(text: String) -> List[String]:
    """The comment lines of a canonical-text file that are not its magic
    line or its `order:` / `float:` directives, in order. parse_canon allows
    them only between the header and the schema line."""
    var res = List[String]()
    for raw in text.split("\n"):
        var line = String(raw)
        if not line.startswith("#"):
            break
        if line.startswith("#!") or line.startswith("#  order") or line.startswith("#  float"):
            continue
        res.append(line^)
    return res^


def _derivation_cites(comments: List[String]) -> Bool:
    """The derivation is the `# derivation:` line and every comment line
    after it; one of those lines must cite an item (`§`)."""
    var inside = False
    for line in comments:
        if line.startswith("# derivation:"):
            inside = True
        if inside and line.find("§") >= 0:
            return True
    return False


def _int_bounds(t: String) -> Tuple[Bool, Int]:
    """(signed, bits) for an integer type spelling; bits 0 if not one."""
    if t == "int8":
        return (True, 8)
    if t == "int16":
        return (True, 16)
    if t == "int32":
        return (True, 32)
    if t == "int64":
        return (True, 64)
    if t == "uint8":
        return (False, 8)
    if t == "uint16":
        return (False, 16)
    if t == "uint32":
        return (False, 32)
    if t == "uint64":
        return (False, 64)
    return (False, 0)


def _int_cell_ok(cell: String, signed: Bool, bits: Int) -> Bool:
    """Canonical integer text in range: `-?` (signed only), digits, no
    leading zero, no `-0`."""
    var bs = cell.as_bytes()
    var n = cell.byte_length()
    var i = 0
    var neg = False
    if n > 0 and bs[0] == 45:  # '-'
        if not signed:
            return False
        neg = True
        i = 1
    if i >= n or n - i > 20:
        return False
    if bs[i] == 48 and n - i > 1:  # leading zero
        return False
    var mag = UInt64(0)
    while i < n:
        if bs[i] < 48 or bs[i] > 57:
            return False
        var d = UInt64(Int(bs[i]) - 48)
        if mag > (UInt64.MAX - d) // 10:
            return False
        mag = mag * 10 + d
        i += 1
    if neg and mag == 0:
        return False
    var limit: UInt64
    if not signed:
        limit = UInt64.MAX if bits == 64 else (UInt64(1) << UInt64(bits)) - 1
    elif neg:
        limit = UInt64(1) << UInt64(bits - 1)
    else:
        limit = (UInt64(1) << UInt64(bits - 1)) - 1
    return mag <= limit


def check_cells(where: String, parsed: CanonText) -> List[String]:
    """Every cell must be a value of its declared column type: `\\N` only in
    a nullable (`?`) column, `true`/`false` in a bool column, canonical
    in-range integer text in an integer column. Float cells are already
    checked by parse_canon; other types are not checked here."""
    var problems = List[String]()
    for c in range(parsed.num_columns()):
        var entry = parsed.schema[c]
        var nullable = entry.endswith("?")
        var type_part = String(
            entry[byte = parsed.names[c].byte_length() + 1 : entry.byte_length() - (1 if nullable else 0)]
        )
        var bounds = _int_bounds(type_part)
        for r in range(parsed.num_rows()):
            ref cell = parsed.rows[r][c]
            var bad = False
            if cell == "\\N":
                bad = not nullable
            elif type_part == "bool":
                bad = cell != "true" and cell != "false"
            elif bounds[1] > 0:
                bad = not _int_cell_ok(cell, bounds[0], bounds[1])
            if bad:
                problems.append(
                    "expect: " + where + ": row " + String(r + 1) + " column "
                    + parsed.names[c] + ": `" + cell + "` is not a value of `"
                    + entry + "`"
                )
    return problems^


def check_expectation(c: Case, text: String, plan: LogicalPlan) -> List[String]:
    """See the module header. Where the marks go: a GENERATED file's FIRST
    comment line is `# GENERATED by ...`; a HAND file has no such line
    anywhere, and its derivation (the `# derivation:` line and the comment
    lines after it) cites at least one item (`§`)."""
    var problems = List[String]()
    var where = c.label() + " (" + c.expect_file() + ")"
    if c.expect == EXPECT_ERROR:
        try:
            _ = parse_err(text)
        except e:
            problems.append("expect: " + where + ": " + String(e))
        return problems^
    var parsed: CanonText
    try:
        parsed = parse_canon(text)
    except e:
        problems.append("expect: " + where + ": " + String(e))
        return problems^
    var comments = _free_comments(text)
    var generated_anywhere = False
    for line in comments:
        if line.startswith("# GENERATED by"):
            generated_anywhere = True
    if c.expect == EXPECT_HAND:
        if not _derivation_cites(comments):
            problems.append(
                "expect: " + where + ": a HAND expectation needs a"
                + " `# derivation:` comment citing the query-semantics items it"
                + " rests on (§<n>)"
            )
        if generated_anywhere:
            problems.append(
                "expect: " + where + ": the case is HAND but the file says"
                + " it is GENERATED"
            )
    elif c.expect == EXPECT_ORACLE:
        if len(comments) == 0 or not comments[0].startswith("# GENERATED by"):
            problems.append(
                "expect: " + where + ": an ORACLE expectation starts its"
                + " comments with `# GENERATED by`"
            )
    var want_header = String()
    c.policy.write_header(want_header)
    var got_header = _header(parsed)
    if want_header != got_header:
        problems.append(
            "expect: " + where + ": the file's order/float header differs from"
            + " the case's policy:\n  case:\n" + want_header + "  file:\n"
            + got_header
        )
    for p in check_cells(where, parsed):
        problems.append(p)
    try:
        for p in check_schema(where, parsed.schema, schema_entries(plan.output_schema)):
            problems.append(p)
    except e:
        problems.append("schema: " + where + ": the plan's schema cannot be spelled: " + String(e))
    return problems^


# -----------------------------------------------------------------------------
# Datasets
# -----------------------------------------------------------------------------


def _value_fits(t: ArrowType, v_is_int: Bool, v_is_bool: Bool, v_is_string: Bool) raises -> Bool:
    if t == ArrowType.BOOL:
        return v_is_bool
    if t == ArrowType.INT64:
        return v_is_int
    if t == ArrowType.STRING:
        return v_is_string
    raise Error("no JSON check for column type " + arrow_type_name(t))


def check_dataset(ds: Dataset, text: String) -> List[String]:
    """Every line is one JSON object whose members are the schema's columns
    in order, each value of the column's JSON kind or `null` where the column
    is nullable."""
    var problems = List[String]()
    var line_no = 0
    var where = String("dataset: ") + ds.path()
    for raw in text.split("\n"):
        line_no += 1
        var line = String(raw)
        if line.byte_length() == 0:
            continue
        var at = where + ":" + String(line_no) + ": "
        try:
            var obj = parse_json_value(line)
            if not obj.is_object():
                problems.append(at + "not a JSON object")
                continue
            if obj.num_members() != ds.schema.num_columns():
                problems.append(
                    at + String(obj.num_members()) + " members, the schema "
                    + String(ds.schema.num_columns()) + " columns"
                )
                continue
            for i in range(obj.num_members()):
                var name = ds.schema.field_name(i)
                if obj.key_at(i) != name:
                    problems.append(
                        at + "member " + String(i) + " is '" + obj.key_at(i)
                        + "', the schema's column is '" + name + "'"
                    )
                    continue
                var v = obj.value_at(i)
                if v.is_null():
                    if not ds.schema.field_nullable(i):
                        problems.append(at + "'" + name + "' is null in a non-nullable column")
                    continue
                var t = ds.schema.field_arrow_type(i)
                if not _value_fits(t, v.is_integral_number(), v.is_bool(), v.is_string()):
                    problems.append(
                        at + "'" + name + "' is " + v.serialize()
                        + ", not a " + arrow_type_name(t)
                    )
        except e:
            problems.append(at + String(e))
    return problems^


def check_dataset_files(datasets: List[Dataset], files: List[String]) -> List[String]:
    """`files` are the names under datasets/; each must be a dataset's file,
    and each dataset must have its file."""
    var problems = List[String]()
    for d in datasets:
        var name = d.name + ".jsonl"
        if not _contains(files, name):
            problems.append("dataset: " + d.path() + " is missing")
    for f in files:
        var owned = False
        for d in datasets:
            if d.name + ".jsonl" == f:
                owned = True
        if not owned:
            problems.append(
                "dataset: " + String(DATASET_DIR) + "/" + f
                + " is an orphan: no registered dataset names it"
            )
    return problems^


# -----------------------------------------------------------------------------
# The whole corpus
# -----------------------------------------------------------------------------


def check_corpus(root: String) raises -> List[String]:
    """Every check over every case, dataset and file under `root`. Returns
    all the problems found; an empty list is a pass."""
    var problems = List[String]()
    var regs = registered_cases()
    for p in check_partition(regs, shard_names()):
        problems.append(p)

    # One entry per distinct case (a twice-registered case is reported above
    # and checked once below).
    var cases = List[Case]()
    for r in regs:
        var seen = False
        for c in cases:
            if c.label() == r.entry.label():
                seen = True
        if not seen:
            cases.append(r.entry.copy())

    var files = list_expect_files(root)
    for p in check_files(cases, files):
        problems.append(p)

    for c in cases:
        var plan = check_wire(c, problems)
        if not plan:
            continue
        var path = root + "/" + c.expect_file()
        if not exists(path):
            continue  # reported by check_files
        for p in check_expectation(c, Path(path).read_text(), plan.value()):
            problems.append(p)

    var datasets = all_datasets()
    var ds_files = List[String]()
    if exists(root + "/" + DATASET_DIR):
        ds_files = listdir(root + "/" + DATASET_DIR)
    for p in check_dataset_files(datasets, ds_files):
        problems.append(p)
    for d in datasets:
        var path = root + "/" + d.path()
        if exists(path):
            for p in check_dataset(d, Path(path).read_text()):
                problems.append(p)
    return problems^


def require_corpus(root: String) raises:
    """Raise with EVERY problem, one per line, unless the corpus is clean."""
    var problems = check_corpus(root)
    if len(problems) == 0:
        return
    var s = String("plan_conformance: ") + String(len(problems)) + " problem(s):"
    for p in problems:
        s += "\n  " + p
    raise Error(s)
