# =============================================================================
# komira_plan_conformance/plan_case.mojo -- one conformance case, and its inputs.
# =============================================================================
#
# A case is a logical plan built with komira_plan_ir's factories, the shard
# it belongs to, and how its expected answer was obtained:
#
#   HAND    a person derived the rows from the dataset and the query-semantics
#           document. The file is expect/<shard>/<id>.tsv in canonical text
#           (komira_plan_harness), carrying a `# derivation:` comment (that
#           line and the comment lines after it) citing the document's items
#           (`§1.1`), never engine code.
#   ORACLE  an independent engine computed it; the file is
#           expect/<shard>/<id>.tsv, generated and committed; its first
#           comment line is `# GENERATED by ...`. No case is ORACLE yet.
#   ERROR   the plan must be refused when it runs; the file is
#           expect/<shard>/<id>.err (see `ErrExpectation`).
#
# The case also states how its rows compare (`policy`: row order and float
# tolerance). The expectation file states the same policy in its header, and
# test_corpus requires the two to agree, so neither can drift alone.
#
# A dataset is a hand-written JSON Lines file, datasets/<name>.jsonl, with the
# schema the cases declare for it. JSON Lines rather than CSV: whether an
# empty CSV field is NULL is open, and reading a JSON `null` as NULL is what
# the query-semantics document proposes (§7.13, undecided).
# =============================================================================

from komira_arrow.schema import Schema
from komira_plan_harness import CanonPolicy
from komira_plan_ir.logical_plan import LogicalPlan
from komira_plan_harness.type_text import schema_entry_of_field

comptime EXPECT_HAND: Int = 0
comptime EXPECT_ORACLE: Int = 1
comptime EXPECT_ERROR: Int = 2

comptime EXPECT_DIR = "expect"
comptime DATASET_DIR = "datasets"

comptime BuildFn = def () raises thin -> LogicalPlan
"""A case's plan builder: no captures, so the registry is plain data."""


def expect_kind_name(kind: Int) -> String:
    if kind == EXPECT_HAND:
        return String("HAND")
    if kind == EXPECT_ORACLE:
        return String("ORACLE")
    if kind == EXPECT_ERROR:
        return String("ERROR")
    return String("UNKNOWN(") + String(kind) + ")"


def expect_extension(kind: Int) -> String:
    """`.err` for an ERROR case, `.tsv` for the others."""
    if kind == EXPECT_ERROR:
        return String(".err")
    return String(".tsv")


struct Case(Copyable, Movable):
    """One registered case. `label()` is `<shard>/<id>`, the name every
    report uses."""

    var id: String
    var shard: String
    var build: BuildFn
    var expect: Int
    var policy: CanonPolicy

    def __init__(
        out self,
        id: String,
        shard: String,
        build: BuildFn,
        expect: Int,
        var policy: CanonPolicy,
    ):
        self.id = id
        self.shard = shard
        self.build = build
        self.expect = expect
        self.policy = policy^

    @staticmethod
    def hand(
        id: String, shard: String, build: BuildFn, var policy: CanonPolicy
    ) -> Case:
        return Case(id, shard, build, EXPECT_HAND, policy^)

    @staticmethod
    def oracle(
        id: String, shard: String, build: BuildFn, var policy: CanonPolicy
    ) -> Case:
        return Case(id, shard, build, EXPECT_ORACLE, policy^)

    @staticmethod
    def error(id: String, shard: String, build: BuildFn) -> Case:
        return Case(id, shard, build, EXPECT_ERROR, CanonPolicy())

    def label(self) -> String:
        return self.shard + "/" + self.id

    def expect_file(self) -> String:
        """The expectation's path under the staged data root."""
        return (
            String(EXPECT_DIR) + "/" + self.shard + "/" + self.id
            + expect_extension(self.expect)
        )


struct Dataset(Copyable, Movable):
    """A hand-written input: datasets/<name>.jsonl, one JSON object per line,
    its members exactly the schema's columns in order."""

    var name: String
    var schema: Schema

    def __init__(out self, name: String, var schema: Schema):
        self.name = name
        self.schema = schema^

    def path(self) -> String:
        return String(DATASET_DIR) + "/" + self.name + ".jsonl"

    def schema_text(self) raises -> String:
        var s = String()
        for i in range(self.schema.num_columns()):
            if i > 0:
                s += "\t"
            s += schema_entry_of_field(self.schema.field_at(i))
        return s^


# -----------------------------------------------------------------------------
# ERROR expectations
# -----------------------------------------------------------------------------
#
# expect/<shard>/<id>.err, one `key: value` per line, `#` lines are comments
# (a `# derivation:` belongs here as in a .tsv):
#
#   prefix: PLAN_ENDPOINT_<NAME>(<code>)     required: the stable code
#   kind: <error kind>                       required: the engine's error kind
#   text: <the full message>                 optional, for the few cases whose
#                                            wording is itself the contract
#
# Only the prefix and the kind are asserted by default: the full text is
# komira's own wording, and asserting it everywhere would churn every file on
# a message edit and invite pasting actual output.


struct ErrExpectation(Copyable, Movable):
    var name: String
    var code: Int
    var kind: String
    var text: Optional[String]

    def __init__(out self):
        self.name = String()
        self.code = 0
        self.kind = String()
        self.text = None

    def prefix(self) -> String:
        return "PLAN_ENDPOINT_" + self.name + "(" + String(self.code) + ")"


def _is_name_byte(b: UInt8) -> Bool:
    return (b >= 65 and b <= 90) or (b >= 48 and b <= 57) or b == 95


def _parse_prefix(value: String, mut out: ErrExpectation) raises:
    comptime HEAD = "PLAN_ENDPOINT_"
    if not value.startswith(HEAD):
        raise Error("'prefix: " + value + "' does not start with " + HEAD)
    var bs = value.as_bytes()
    var n = value.byte_length()
    var i = HEAD.byte_length()
    var name_start = i
    while i < n and _is_name_byte(bs[i]):
        i += 1
    if i == name_start or i >= n or bs[i] != 40:  # '('
        raise Error(
            "'prefix: " + value + "' is not PLAN_ENDPOINT_<NAME>(<code>)"
            + " with <NAME> in [A-Z0-9_]"
        )
    var name = String(value[byte=name_start:i])
    i += 1
    var digits_start = i
    if i < n and bs[i] == 45:  # '-'
        i += 1
    var first_digit = i
    while i < n and bs[i] >= 48 and bs[i] <= 57:
        i += 1
    if i == first_digit or i != n - 1 or bs[i] != 41:  # ')'
        raise Error(
            "'prefix: " + value + "' is not PLAN_ENDPOINT_<NAME>(<code>)"
            + " with an integer <code> and nothing after the ')'"
        )
    out.name = name^
    out.code = Int(String(value[byte=digits_start:i]))


def parse_err(text: String) raises -> ErrExpectation:
    """Parse an .err file. Refuses an unknown key, a repeated key, a missing
    prefix or kind, and a malformed prefix."""
    var res = ErrExpectation()
    var seen_prefix = False
    var seen_kind = False
    var line_no = 0
    for raw in text.split("\n"):
        line_no += 1
        var line = String(raw)
        if line.byte_length() == 0 or line.startswith("#"):
            continue
        var colon = line.find(": ")
        if colon < 0:
            raise Error(
                "err: line " + String(line_no) + " is not '<key>: <value>'"
            )
        var key = String(line[byte=0:colon])
        var value = String(line[byte = colon + 2 : line.byte_length()])
        if key == "prefix":
            if seen_prefix:
                raise Error("err: line " + String(line_no) + ": a second prefix")
            _parse_prefix(value, res)
            seen_prefix = True
        elif key == "kind":
            if seen_kind:
                raise Error("err: line " + String(line_no) + ": a second kind")
            if value.byte_length() == 0:
                raise Error("err: line " + String(line_no) + ": an empty kind")
            res.kind = value
            seen_kind = True
        elif key == "text":
            if res.text:
                raise Error("err: line " + String(line_no) + ": a second text")
            res.text = value
        else:
            raise Error(
                "err: line " + String(line_no) + ": unknown key '" + key
                + "' (prefix, kind, text)"
            )
    if not seen_prefix or not seen_kind:
        raise Error("err: a .err file needs both a prefix line and a kind line")
    return res^
