"""The surface x capability matrix: which capability of the plan each surface's end-to-end tests exercise.

The ledger of //:surface_capability_matrix (tools/build/lint/surface_capability_matrix.bzl;
the rules and today's census: docs/surface_capability_matrix.md). Starlark, not a TSV,
so that the build graph resolves every test target a row names: a target that does not
exist fails the build.

SURFACES are the ways a user reaches komira. CAPABILITIES are named by their meaning in
the plan: each is grounded in the plan constants that express it (`contract` for a
promise every surface makes that the plan holds no node for), and NOT_CAPABILITIES says
why each other constant of the grounding families is none (the lint requires every one
to be named). MATRIX has one row per (surface, capability): the surface e2e test target
that exercises the capability end to end against an independent oracle, in
src/tests/e2e/<surface>_e2e/, or `-`, and a note. Fill a cell by naming the target and
raising `floor` in the root BUCK to the new count of filled cells (a review rule: the lint fails only below the floor).
"""

SURFACES = [
    "pandas",
    "polars",
    "sql",
    "mojo_polars",
    "ts_polars",
    # A surface of its own, built on top of the TypeScript SDK.
    "excel",
]

# (name, grounding, meaning)
CAPABILITIES = [
    ("scan_parquet", "PLAN_SCAN,SOURCE_PARQUET", "read Parquet files"),
    ("scan_csv", "PLAN_SCAN,SOURCE_CSV", "read CSV files"),
    ("scan_jsonl", "PLAN_SCAN,SOURCE_NDJSON,SOURCE_JSON", "read JSON Lines files (the row and the columnar decode of the same bytes)"),
    ("scan_orc", "PLAN_SCAN,SOURCE_ORC", "read ORC files"),
    ("scan_avro", "PLAN_SCAN,SOURCE_AVRO", "read Avro object container files"),
    ("scan_arrow_ipc", "PLAN_SCAN,SOURCE_ARROW", "read Arrow IPC files"),
    ("scan_in_memory", "PLAN_SCAN,SOURCE_IN_MEMORY", "query a table the caller holds in memory"),
    ("scan_s3", "PLAN_SCAN,FS_SCHEME_S3", "read from an s3:// prefix"),
    ("scan_gs", "PLAN_SCAN,FS_SCHEME_GCS", "read from a gs:// prefix"),
    ("scan_az", "PLAN_SCAN,FS_SCHEME_AZURE", "read from an az:// prefix"),
    ("filter", "PLAN_FILTER", "keep the rows a predicate holds for"),
    ("project", "PLAN_PROJECT,EXPR_COL_REF,EXPR_COL_IDX,EXPR_ALIAS", "select, reorder and rename columns"),
    ("computed_column", "PLAN_PROJECT,EXPR_LITERAL,EXPR_BINARY_OP,EXPR_UNARY_OP", "add or replace a column computed from literals, arithmetic, comparison and logic"),
    ("cast", "EXPR_CAST", "convert a value to another type"),
    ("case_when", "EXPR_WHEN", "a conditional expression (CASE WHEN, when/then/otherwise)"),
    ("in_list", "EXPR_IN_LIST", "membership of a value in a list of values"),
    ("between", "EXPR_BETWEEN", "a value within a closed range"),
    ("string_functions", "EXPR_STRING_OP,EXPR_STRING_FN,EXPR_STRING_FN_N,EXPR_SUBSTRING", "string functions: case, trim, length, substring, concat, replace, pad, position"),
    ("regexp", "EXPR_REGEXP", "regular-expression match, extract, replace and split"),
    ("temporal_extract", "EXPR_EXTRACT", "extract a date or time field, or truncate to a period"),
    ("math_functions", "EXPR_MATH_FN,EXPR_MATH_FN2", "math functions of one or two arguments"),
    ("nested_access", "EXPR_STRUCT_FIELD,EXPR_STRUCT_FIELD_IDX,EXPR_MAP_GET", "a struct field or a map value by key"),
    ("json_extract", "EXPR_JSON_EXTRACT", "a path extracted from a JSON column"),
    ("join_inner", "PLAN_JOIN,JOIN_INNER", "inner join"),
    ("join_left", "PLAN_JOIN,JOIN_LEFT", "left outer join"),
    ("join_right", "PLAN_JOIN,JOIN_RIGHT", "right outer join"),
    ("join_full", "PLAN_JOIN,JOIN_FULL", "full outer join"),
    ("join_semi", "PLAN_JOIN,JOIN_SEMI", "semi join: left rows with a match"),
    ("join_anti", "PLAN_JOIN,JOIN_ANTI", "anti join: left rows with no match"),
    ("join_cross", "PLAN_JOIN,JOIN_CROSS", "cross join"),
    ("join_asof", "PLAN_ASOF_JOIN", "as-of join: the nearest right row by an ordered key"),
    ("aggregate", "PLAN_AGGREGATE", "aggregates over the whole input (no group keys)"),
    ("group_by", "PLAN_AGGREGATE", "aggregates per group of key values"),
    ("window", "PLAN_PARTITION_BY,EXPR_WINDOW_FN", "window functions over partitions, every row kept"),
    ("sort", "PLAN_SORT,EXPR_SORT_KEY", "order the rows, NULLs first or last"),
    ("topn", "PLAN_TOPN", "the first n rows of an order"),
    ("topn_per_group", "PLAN_PARTITION_TOPN", "the first k rows of an order within each group"),
    ("limit", "PLAN_LIMIT", "the first n rows, with an offset"),
    ("distinct", "PLAN_DISTINCT", "drop duplicate rows, or rows duplicate on some columns"),
    ("union", "PLAN_UNION", "concatenate inputs of one schema (union all)"),
    ("subquery", "EXPR_CORRELATED_SUBQUERY", "a subquery inside an expression, correlated or not"),
    ("view", "PLAN_VIEW_REF", "register a named view and query it"),
    ("udf_map", "UDF_KIND_MAP,EXPR_UDF_CALL", "a user function computing a column, alone or inside an expression"),
    ("udf_filter", "UDF_KIND_FILTER", "a user function as a filter predicate"),
    ("udf_agg", "UDF_KIND_AGG", "a user aggregate function"),
    ("write_parquet", "WFMT_PARQUET", "write a result as Parquet"),
    ("write_csv", "WFMT_CSV", "write a result as CSV"),
    ("write_jsonl", "WFMT_JSONL", "write a result as JSON Lines"),
    ("null_semantics", "contract", "NULL in comparisons, logic, joins, aggregates and ordering, as the surface documents"),
    ("errors", "contract", "an invalid query or a failed read raises to the caller in the surface's own error form"),
    ("output_dtypes", "contract", "results arrive in the surface's own types, every column type converted"),
    ("output_nan_null", "contract", "NaN and NULL stay distinct in results, as the surface represents them"),
]

# (identifiers, why they name no capability)
NOT_CAPABILITIES = [
    ("PLAN_CSE_REF", "made only by the optimizer's common-subexpression rewrite; no surface builds it"),
    ("PLAN_CAST_TO_VARCHAR", "inserted above a text sink by a rewrite; no surface builds it"),
    ("EXPR_AGG_FN", "an aggregate inside an expression, made and consumed by the optimizer's scalar-broadcast rewrite; a surface's aggregates are the aggregate and group_by capabilities"),
    ("SOURCE_BINDING", "the open arm: a source kind named by its binding, not by this enum; a kind gets a capability when a surface reaches it"),
    ("SOURCE_KIND_COLUMNAR,SOURCE_KIND_ROW,SOURCE_KIND_UNSET", "the layout a source format derives, which picks a reader; not something a query asks for"),
    ("JOIN_ALGO_AUTO,JOIN_ALGO_HASH,JOIN_ALGO_SORT_MERGE", "the join algorithm, a physical choice with the same result"),
    ("FS_SCHEME_FILE", "a local path, which every scan_* capability's test reads"),
]

# (surface, capability, test target or "-", note)
MATRIX = [
    ("pandas", "scan_parquet", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_csv", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_jsonl", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_orc", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_avro", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_arrow_ipc", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_in_memory", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_s3", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_gs", "-", "no pandas_e2e package yet"),
    ("pandas", "scan_az", "-", "no pandas_e2e package yet"),
    ("pandas", "filter", "-", "no pandas_e2e package yet"),
    ("pandas", "project", "-", "no pandas_e2e package yet"),
    ("pandas", "computed_column", "-", "no pandas_e2e package yet"),
    ("pandas", "cast", "-", "no pandas_e2e package yet"),
    ("pandas", "case_when", "-", "no pandas_e2e package yet"),
    ("pandas", "in_list", "-", "no pandas_e2e package yet"),
    ("pandas", "between", "-", "no pandas_e2e package yet"),
    ("pandas", "string_functions", "-", "no pandas_e2e package yet"),
    ("pandas", "regexp", "-", "no pandas_e2e package yet"),
    ("pandas", "temporal_extract", "-", "no pandas_e2e package yet"),
    ("pandas", "math_functions", "-", "no pandas_e2e package yet"),
    ("pandas", "nested_access", "-", "no pandas_e2e package yet"),
    ("pandas", "json_extract", "-", "no pandas_e2e package yet"),
    ("pandas", "join_inner", "-", "no pandas_e2e package yet"),
    ("pandas", "join_left", "-", "no pandas_e2e package yet"),
    ("pandas", "join_right", "-", "no pandas_e2e package yet"),
    ("pandas", "join_full", "-", "no pandas_e2e package yet"),
    ("pandas", "join_semi", "-", "no pandas_e2e package yet"),
    ("pandas", "join_anti", "-", "no pandas_e2e package yet"),
    ("pandas", "join_cross", "-", "no pandas_e2e package yet"),
    ("pandas", "join_asof", "-", "no pandas_e2e package yet"),
    ("pandas", "aggregate", "-", "no pandas_e2e package yet"),
    ("pandas", "group_by", "-", "no pandas_e2e package yet"),
    ("pandas", "window", "-", "no pandas_e2e package yet"),
    ("pandas", "sort", "-", "no pandas_e2e package yet"),
    ("pandas", "topn", "-", "no pandas_e2e package yet"),
    ("pandas", "topn_per_group", "-", "no pandas_e2e package yet"),
    ("pandas", "limit", "-", "no pandas_e2e package yet"),
    ("pandas", "distinct", "-", "no pandas_e2e package yet"),
    ("pandas", "union", "-", "no pandas_e2e package yet"),
    ("pandas", "subquery", "-", "no pandas_e2e package yet"),
    ("pandas", "view", "-", "no pandas_e2e package yet"),
    ("pandas", "udf_map", "-", "no pandas_e2e package yet"),
    ("pandas", "udf_filter", "-", "no pandas_e2e package yet"),
    ("pandas", "udf_agg", "-", "no pandas_e2e package yet"),
    ("pandas", "write_parquet", "-", "no pandas_e2e package yet"),
    ("pandas", "write_csv", "-", "no pandas_e2e package yet"),
    ("pandas", "write_jsonl", "-", "no pandas_e2e package yet"),
    ("pandas", "null_semantics", "-", "no pandas_e2e package yet"),
    ("pandas", "errors", "-", "no pandas_e2e package yet"),
    ("pandas", "output_dtypes", "-", "no pandas_e2e package yet"),
    ("pandas", "output_nan_null", "-", "no pandas_e2e package yet"),
    ("polars", "scan_parquet", "-", "no polars_e2e package yet"),
    ("polars", "scan_csv", "-", "no polars_e2e package yet"),
    ("polars", "scan_jsonl", "-", "no polars_e2e package yet"),
    ("polars", "scan_orc", "-", "no polars_e2e package yet"),
    ("polars", "scan_avro", "-", "no polars_e2e package yet"),
    ("polars", "scan_arrow_ipc", "-", "no polars_e2e package yet"),
    ("polars", "scan_in_memory", "-", "no polars_e2e package yet"),
    ("polars", "scan_s3", "-", "no polars_e2e package yet"),
    ("polars", "scan_gs", "-", "no polars_e2e package yet"),
    ("polars", "scan_az", "-", "no polars_e2e package yet"),
    ("polars", "filter", "-", "no polars_e2e package yet"),
    ("polars", "project", "-", "no polars_e2e package yet"),
    ("polars", "computed_column", "-", "no polars_e2e package yet"),
    ("polars", "cast", "-", "no polars_e2e package yet"),
    ("polars", "case_when", "-", "no polars_e2e package yet"),
    ("polars", "in_list", "-", "no polars_e2e package yet"),
    ("polars", "between", "-", "no polars_e2e package yet"),
    ("polars", "string_functions", "-", "no polars_e2e package yet"),
    ("polars", "regexp", "-", "no polars_e2e package yet"),
    ("polars", "temporal_extract", "-", "no polars_e2e package yet"),
    ("polars", "math_functions", "-", "no polars_e2e package yet"),
    ("polars", "nested_access", "-", "no polars_e2e package yet"),
    ("polars", "json_extract", "-", "no polars_e2e package yet"),
    ("polars", "join_inner", "-", "no polars_e2e package yet"),
    ("polars", "join_left", "-", "no polars_e2e package yet"),
    ("polars", "join_right", "-", "no polars_e2e package yet"),
    ("polars", "join_full", "-", "no polars_e2e package yet"),
    ("polars", "join_semi", "-", "no polars_e2e package yet"),
    ("polars", "join_anti", "-", "no polars_e2e package yet"),
    ("polars", "join_cross", "-", "no polars_e2e package yet"),
    ("polars", "join_asof", "-", "no polars_e2e package yet"),
    ("polars", "aggregate", "-", "no polars_e2e package yet"),
    ("polars", "group_by", "-", "no polars_e2e package yet"),
    ("polars", "window", "-", "no polars_e2e package yet"),
    ("polars", "sort", "-", "no polars_e2e package yet"),
    ("polars", "topn", "-", "no polars_e2e package yet"),
    ("polars", "topn_per_group", "-", "no polars_e2e package yet"),
    ("polars", "limit", "-", "no polars_e2e package yet"),
    ("polars", "distinct", "-", "no polars_e2e package yet"),
    ("polars", "union", "-", "no polars_e2e package yet"),
    ("polars", "subquery", "-", "no polars_e2e package yet"),
    ("polars", "view", "-", "no polars_e2e package yet"),
    ("polars", "udf_map", "-", "no polars_e2e package yet"),
    ("polars", "udf_filter", "-", "no polars_e2e package yet"),
    ("polars", "udf_agg", "-", "no polars_e2e package yet"),
    ("polars", "write_parquet", "-", "no polars_e2e package yet"),
    ("polars", "write_csv", "-", "no polars_e2e package yet"),
    ("polars", "write_jsonl", "-", "no polars_e2e package yet"),
    ("polars", "null_semantics", "-", "no polars_e2e package yet"),
    ("polars", "errors", "-", "no polars_e2e package yet"),
    ("polars", "output_dtypes", "-", "no polars_e2e package yet"),
    ("polars", "output_nan_null", "-", "no polars_e2e package yet"),
    ("sql", "scan_parquet", "-", "no sql_e2e package yet"),
    ("sql", "scan_csv", "-", "no sql_e2e package yet"),
    ("sql", "scan_jsonl", "-", "no sql_e2e package yet"),
    ("sql", "scan_orc", "-", "no sql_e2e package yet"),
    ("sql", "scan_avro", "-", "no sql_e2e package yet"),
    ("sql", "scan_arrow_ipc", "-", "no sql_e2e package yet"),
    ("sql", "scan_in_memory", "-", "no sql_e2e package yet"),
    ("sql", "scan_s3", "-", "no sql_e2e package yet"),
    ("sql", "scan_gs", "-", "no sql_e2e package yet"),
    ("sql", "scan_az", "-", "no sql_e2e package yet"),
    ("sql", "filter", "-", "no sql_e2e package yet"),
    ("sql", "project", "-", "no sql_e2e package yet"),
    ("sql", "computed_column", "-", "no sql_e2e package yet"),
    ("sql", "cast", "-", "no sql_e2e package yet"),
    ("sql", "case_when", "-", "no sql_e2e package yet"),
    ("sql", "in_list", "-", "no sql_e2e package yet"),
    ("sql", "between", "-", "no sql_e2e package yet"),
    ("sql", "string_functions", "-", "no sql_e2e package yet"),
    ("sql", "regexp", "-", "no sql_e2e package yet"),
    ("sql", "temporal_extract", "-", "no sql_e2e package yet"),
    ("sql", "math_functions", "-", "no sql_e2e package yet"),
    ("sql", "nested_access", "-", "no sql_e2e package yet"),
    ("sql", "json_extract", "-", "no sql_e2e package yet"),
    ("sql", "join_inner", "-", "no sql_e2e package yet"),
    ("sql", "join_left", "-", "no sql_e2e package yet"),
    ("sql", "join_right", "-", "no sql_e2e package yet"),
    ("sql", "join_full", "-", "no sql_e2e package yet"),
    ("sql", "join_semi", "-", "no sql_e2e package yet"),
    ("sql", "join_anti", "-", "no sql_e2e package yet"),
    ("sql", "join_cross", "-", "no sql_e2e package yet"),
    ("sql", "join_asof", "-", "no sql_e2e package yet"),
    ("sql", "aggregate", "-", "no sql_e2e package yet"),
    ("sql", "group_by", "-", "no sql_e2e package yet"),
    ("sql", "window", "-", "no sql_e2e package yet"),
    ("sql", "sort", "-", "no sql_e2e package yet"),
    ("sql", "topn", "-", "no sql_e2e package yet"),
    ("sql", "topn_per_group", "-", "no sql_e2e package yet"),
    ("sql", "limit", "-", "no sql_e2e package yet"),
    ("sql", "distinct", "-", "no sql_e2e package yet"),
    ("sql", "union", "-", "no sql_e2e package yet"),
    ("sql", "subquery", "-", "no sql_e2e package yet"),
    ("sql", "view", "-", "no sql_e2e package yet"),
    ("sql", "udf_map", "-", "no sql_e2e package yet"),
    ("sql", "udf_filter", "-", "no sql_e2e package yet"),
    ("sql", "udf_agg", "-", "no sql_e2e package yet"),
    ("sql", "write_parquet", "-", "no sql_e2e package yet"),
    ("sql", "write_csv", "-", "no sql_e2e package yet"),
    ("sql", "write_jsonl", "-", "no sql_e2e package yet"),
    ("sql", "null_semantics", "-", "no sql_e2e package yet"),
    ("sql", "errors", "-", "no sql_e2e package yet"),
    ("sql", "output_dtypes", "-", "no sql_e2e package yet"),
    ("sql", "output_nan_null", "-", "no sql_e2e package yet"),
    ("mojo_polars", "scan_parquet", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_csv", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_jsonl", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_orc", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_avro", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_arrow_ipc", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_in_memory", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_s3", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_gs", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "scan_az", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "filter", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "project", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "computed_column", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "cast", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "case_when", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "in_list", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "between", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "string_functions", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "regexp", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "temporal_extract", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "math_functions", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "nested_access", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "json_extract", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_inner", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_left", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_right", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_full", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_semi", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_anti", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_cross", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "join_asof", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "aggregate", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "group_by", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "window", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "sort", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "topn", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "topn_per_group", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "limit", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "distinct", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "union", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "subquery", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "view", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "udf_map", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "udf_filter", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "udf_agg", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "write_parquet", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "write_csv", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "write_jsonl", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "null_semantics", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "errors", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "output_dtypes", "-", "no mojo_polars_e2e package yet"),
    ("mojo_polars", "output_nan_null", "-", "no mojo_polars_e2e package yet"),
    ("ts_polars", "scan_parquet", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_csv", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_jsonl", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_orc", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_avro", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_arrow_ipc", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_in_memory", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_s3", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_gs", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "scan_az", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "filter", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "project", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "computed_column", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "cast", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "case_when", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "in_list", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "between", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "string_functions", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "regexp", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "temporal_extract", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "math_functions", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "nested_access", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "json_extract", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_inner", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_left", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_right", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_full", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_semi", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_anti", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_cross", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "join_asof", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "aggregate", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "group_by", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "window", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "sort", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "topn", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "topn_per_group", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "limit", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "distinct", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "union", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "subquery", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "view", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "udf_map", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "udf_filter", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "udf_agg", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "write_parquet", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "write_csv", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "write_jsonl", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "null_semantics", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "errors", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "output_dtypes", "-", "no ts_polars_e2e package yet"),
    ("ts_polars", "output_nan_null", "-", "no ts_polars_e2e package yet"),
    ("excel", "scan_parquet", "-", "no excel_e2e package yet"),
    ("excel", "scan_csv", "-", "no excel_e2e package yet"),
    ("excel", "scan_jsonl", "-", "no excel_e2e package yet"),
    ("excel", "scan_orc", "-", "no excel_e2e package yet"),
    ("excel", "scan_avro", "-", "no excel_e2e package yet"),
    ("excel", "scan_arrow_ipc", "-", "no excel_e2e package yet"),
    ("excel", "scan_in_memory", "-", "no excel_e2e package yet"),
    ("excel", "scan_s3", "-", "no excel_e2e package yet"),
    ("excel", "scan_gs", "-", "no excel_e2e package yet"),
    ("excel", "scan_az", "-", "no excel_e2e package yet"),
    ("excel", "filter", "-", "no excel_e2e package yet"),
    ("excel", "project", "-", "no excel_e2e package yet"),
    ("excel", "computed_column", "-", "no excel_e2e package yet"),
    ("excel", "cast", "-", "no excel_e2e package yet"),
    ("excel", "case_when", "-", "no excel_e2e package yet"),
    ("excel", "in_list", "-", "no excel_e2e package yet"),
    ("excel", "between", "-", "no excel_e2e package yet"),
    ("excel", "string_functions", "-", "no excel_e2e package yet"),
    ("excel", "regexp", "-", "no excel_e2e package yet"),
    ("excel", "temporal_extract", "-", "no excel_e2e package yet"),
    ("excel", "math_functions", "-", "no excel_e2e package yet"),
    ("excel", "nested_access", "-", "no excel_e2e package yet"),
    ("excel", "json_extract", "-", "no excel_e2e package yet"),
    ("excel", "join_inner", "-", "no excel_e2e package yet"),
    ("excel", "join_left", "-", "no excel_e2e package yet"),
    ("excel", "join_right", "-", "no excel_e2e package yet"),
    ("excel", "join_full", "-", "no excel_e2e package yet"),
    ("excel", "join_semi", "-", "no excel_e2e package yet"),
    ("excel", "join_anti", "-", "no excel_e2e package yet"),
    ("excel", "join_cross", "-", "no excel_e2e package yet"),
    ("excel", "join_asof", "-", "no excel_e2e package yet"),
    ("excel", "aggregate", "-", "no excel_e2e package yet"),
    ("excel", "group_by", "-", "no excel_e2e package yet"),
    ("excel", "window", "-", "no excel_e2e package yet"),
    ("excel", "sort", "-", "no excel_e2e package yet"),
    ("excel", "topn", "-", "no excel_e2e package yet"),
    ("excel", "topn_per_group", "-", "no excel_e2e package yet"),
    ("excel", "limit", "-", "no excel_e2e package yet"),
    ("excel", "distinct", "-", "no excel_e2e package yet"),
    ("excel", "union", "-", "no excel_e2e package yet"),
    ("excel", "subquery", "-", "no excel_e2e package yet"),
    ("excel", "view", "-", "no excel_e2e package yet"),
    ("excel", "udf_map", "-", "no excel_e2e package yet"),
    ("excel", "udf_filter", "-", "no excel_e2e package yet"),
    ("excel", "udf_agg", "-", "no excel_e2e package yet"),
    ("excel", "write_parquet", "-", "no excel_e2e package yet"),
    ("excel", "write_csv", "-", "no excel_e2e package yet"),
    ("excel", "write_jsonl", "-", "no excel_e2e package yet"),
    ("excel", "null_semantics", "-", "no excel_e2e package yet"),
    ("excel", "errors", "-", "no excel_e2e package yet"),
    ("excel", "output_dtypes", "-", "no excel_e2e package yet"),
    ("excel", "output_nan_null", "-", "no excel_e2e package yet"),
]
