# =============================================================================
# test_name_registry_full.mojo -- a table filled to MAX_REGISTERED_NAMES
# =============================================================================
#
# Registers 256 distinct names ("n000".."n255"; all 256 ids differ, and only
# 178 distinct low bytes among them, so many share a home slot and probe on),
# then one more ("n256"). Verifies:
#   1. Every one of the 256 registrations succeeds, including names whose
#      home slot is taken (the probe moves to the next slot and wraps).
#   2. Every name reads back by id, from `lookup` and `contains`, however far
#      it was displaced from its home slot.
#   3. On the full table a 257th name is refused: `try_register` returns
#      False after probing every slot, and the count stays at 256.
#   4. An id absent from the full table is absent to `lookup` and `contains`,
#      which also probe every slot and then stop.
# =============================================================================

from std.testing import assert_equal, assert_true, assert_false

from komira_name_registry import (
    MAX_REGISTERED_NAMES,
    NameRegistry,
    name_id,
    name_id_of,
)


def _expected_name(i: Int) -> String:
    var digits = String(i)
    while digits.byte_length() < 3:
        digits = "0" + digits
    return "n" + digits


def _fill(mut reg: NameRegistry, mut ids: List[UInt32]) -> Int:
    """Registers n000..n255 (one `try_register` instantiation per name, the
    only way to register a literal) and returns how many succeeded; `ids`
    gets each name's id, computed at run time from the same text."""
    for i in range(MAX_REGISTERED_NAMES):
        ids.append(name_id_of(_expected_name(i)))
    var oks = 0
    oks += Int(reg.try_register["n000"]())
    oks += Int(reg.try_register["n001"]())
    oks += Int(reg.try_register["n002"]())
    oks += Int(reg.try_register["n003"]())
    oks += Int(reg.try_register["n004"]())
    oks += Int(reg.try_register["n005"]())
    oks += Int(reg.try_register["n006"]())
    oks += Int(reg.try_register["n007"]())
    oks += Int(reg.try_register["n008"]())
    oks += Int(reg.try_register["n009"]())
    oks += Int(reg.try_register["n010"]())
    oks += Int(reg.try_register["n011"]())
    oks += Int(reg.try_register["n012"]())
    oks += Int(reg.try_register["n013"]())
    oks += Int(reg.try_register["n014"]())
    oks += Int(reg.try_register["n015"]())
    oks += Int(reg.try_register["n016"]())
    oks += Int(reg.try_register["n017"]())
    oks += Int(reg.try_register["n018"]())
    oks += Int(reg.try_register["n019"]())
    oks += Int(reg.try_register["n020"]())
    oks += Int(reg.try_register["n021"]())
    oks += Int(reg.try_register["n022"]())
    oks += Int(reg.try_register["n023"]())
    oks += Int(reg.try_register["n024"]())
    oks += Int(reg.try_register["n025"]())
    oks += Int(reg.try_register["n026"]())
    oks += Int(reg.try_register["n027"]())
    oks += Int(reg.try_register["n028"]())
    oks += Int(reg.try_register["n029"]())
    oks += Int(reg.try_register["n030"]())
    oks += Int(reg.try_register["n031"]())
    oks += Int(reg.try_register["n032"]())
    oks += Int(reg.try_register["n033"]())
    oks += Int(reg.try_register["n034"]())
    oks += Int(reg.try_register["n035"]())
    oks += Int(reg.try_register["n036"]())
    oks += Int(reg.try_register["n037"]())
    oks += Int(reg.try_register["n038"]())
    oks += Int(reg.try_register["n039"]())
    oks += Int(reg.try_register["n040"]())
    oks += Int(reg.try_register["n041"]())
    oks += Int(reg.try_register["n042"]())
    oks += Int(reg.try_register["n043"]())
    oks += Int(reg.try_register["n044"]())
    oks += Int(reg.try_register["n045"]())
    oks += Int(reg.try_register["n046"]())
    oks += Int(reg.try_register["n047"]())
    oks += Int(reg.try_register["n048"]())
    oks += Int(reg.try_register["n049"]())
    oks += Int(reg.try_register["n050"]())
    oks += Int(reg.try_register["n051"]())
    oks += Int(reg.try_register["n052"]())
    oks += Int(reg.try_register["n053"]())
    oks += Int(reg.try_register["n054"]())
    oks += Int(reg.try_register["n055"]())
    oks += Int(reg.try_register["n056"]())
    oks += Int(reg.try_register["n057"]())
    oks += Int(reg.try_register["n058"]())
    oks += Int(reg.try_register["n059"]())
    oks += Int(reg.try_register["n060"]())
    oks += Int(reg.try_register["n061"]())
    oks += Int(reg.try_register["n062"]())
    oks += Int(reg.try_register["n063"]())
    oks += Int(reg.try_register["n064"]())
    oks += Int(reg.try_register["n065"]())
    oks += Int(reg.try_register["n066"]())
    oks += Int(reg.try_register["n067"]())
    oks += Int(reg.try_register["n068"]())
    oks += Int(reg.try_register["n069"]())
    oks += Int(reg.try_register["n070"]())
    oks += Int(reg.try_register["n071"]())
    oks += Int(reg.try_register["n072"]())
    oks += Int(reg.try_register["n073"]())
    oks += Int(reg.try_register["n074"]())
    oks += Int(reg.try_register["n075"]())
    oks += Int(reg.try_register["n076"]())
    oks += Int(reg.try_register["n077"]())
    oks += Int(reg.try_register["n078"]())
    oks += Int(reg.try_register["n079"]())
    oks += Int(reg.try_register["n080"]())
    oks += Int(reg.try_register["n081"]())
    oks += Int(reg.try_register["n082"]())
    oks += Int(reg.try_register["n083"]())
    oks += Int(reg.try_register["n084"]())
    oks += Int(reg.try_register["n085"]())
    oks += Int(reg.try_register["n086"]())
    oks += Int(reg.try_register["n087"]())
    oks += Int(reg.try_register["n088"]())
    oks += Int(reg.try_register["n089"]())
    oks += Int(reg.try_register["n090"]())
    oks += Int(reg.try_register["n091"]())
    oks += Int(reg.try_register["n092"]())
    oks += Int(reg.try_register["n093"]())
    oks += Int(reg.try_register["n094"]())
    oks += Int(reg.try_register["n095"]())
    oks += Int(reg.try_register["n096"]())
    oks += Int(reg.try_register["n097"]())
    oks += Int(reg.try_register["n098"]())
    oks += Int(reg.try_register["n099"]())
    oks += Int(reg.try_register["n100"]())
    oks += Int(reg.try_register["n101"]())
    oks += Int(reg.try_register["n102"]())
    oks += Int(reg.try_register["n103"]())
    oks += Int(reg.try_register["n104"]())
    oks += Int(reg.try_register["n105"]())
    oks += Int(reg.try_register["n106"]())
    oks += Int(reg.try_register["n107"]())
    oks += Int(reg.try_register["n108"]())
    oks += Int(reg.try_register["n109"]())
    oks += Int(reg.try_register["n110"]())
    oks += Int(reg.try_register["n111"]())
    oks += Int(reg.try_register["n112"]())
    oks += Int(reg.try_register["n113"]())
    oks += Int(reg.try_register["n114"]())
    oks += Int(reg.try_register["n115"]())
    oks += Int(reg.try_register["n116"]())
    oks += Int(reg.try_register["n117"]())
    oks += Int(reg.try_register["n118"]())
    oks += Int(reg.try_register["n119"]())
    oks += Int(reg.try_register["n120"]())
    oks += Int(reg.try_register["n121"]())
    oks += Int(reg.try_register["n122"]())
    oks += Int(reg.try_register["n123"]())
    oks += Int(reg.try_register["n124"]())
    oks += Int(reg.try_register["n125"]())
    oks += Int(reg.try_register["n126"]())
    oks += Int(reg.try_register["n127"]())
    oks += Int(reg.try_register["n128"]())
    oks += Int(reg.try_register["n129"]())
    oks += Int(reg.try_register["n130"]())
    oks += Int(reg.try_register["n131"]())
    oks += Int(reg.try_register["n132"]())
    oks += Int(reg.try_register["n133"]())
    oks += Int(reg.try_register["n134"]())
    oks += Int(reg.try_register["n135"]())
    oks += Int(reg.try_register["n136"]())
    oks += Int(reg.try_register["n137"]())
    oks += Int(reg.try_register["n138"]())
    oks += Int(reg.try_register["n139"]())
    oks += Int(reg.try_register["n140"]())
    oks += Int(reg.try_register["n141"]())
    oks += Int(reg.try_register["n142"]())
    oks += Int(reg.try_register["n143"]())
    oks += Int(reg.try_register["n144"]())
    oks += Int(reg.try_register["n145"]())
    oks += Int(reg.try_register["n146"]())
    oks += Int(reg.try_register["n147"]())
    oks += Int(reg.try_register["n148"]())
    oks += Int(reg.try_register["n149"]())
    oks += Int(reg.try_register["n150"]())
    oks += Int(reg.try_register["n151"]())
    oks += Int(reg.try_register["n152"]())
    oks += Int(reg.try_register["n153"]())
    oks += Int(reg.try_register["n154"]())
    oks += Int(reg.try_register["n155"]())
    oks += Int(reg.try_register["n156"]())
    oks += Int(reg.try_register["n157"]())
    oks += Int(reg.try_register["n158"]())
    oks += Int(reg.try_register["n159"]())
    oks += Int(reg.try_register["n160"]())
    oks += Int(reg.try_register["n161"]())
    oks += Int(reg.try_register["n162"]())
    oks += Int(reg.try_register["n163"]())
    oks += Int(reg.try_register["n164"]())
    oks += Int(reg.try_register["n165"]())
    oks += Int(reg.try_register["n166"]())
    oks += Int(reg.try_register["n167"]())
    oks += Int(reg.try_register["n168"]())
    oks += Int(reg.try_register["n169"]())
    oks += Int(reg.try_register["n170"]())
    oks += Int(reg.try_register["n171"]())
    oks += Int(reg.try_register["n172"]())
    oks += Int(reg.try_register["n173"]())
    oks += Int(reg.try_register["n174"]())
    oks += Int(reg.try_register["n175"]())
    oks += Int(reg.try_register["n176"]())
    oks += Int(reg.try_register["n177"]())
    oks += Int(reg.try_register["n178"]())
    oks += Int(reg.try_register["n179"]())
    oks += Int(reg.try_register["n180"]())
    oks += Int(reg.try_register["n181"]())
    oks += Int(reg.try_register["n182"]())
    oks += Int(reg.try_register["n183"]())
    oks += Int(reg.try_register["n184"]())
    oks += Int(reg.try_register["n185"]())
    oks += Int(reg.try_register["n186"]())
    oks += Int(reg.try_register["n187"]())
    oks += Int(reg.try_register["n188"]())
    oks += Int(reg.try_register["n189"]())
    oks += Int(reg.try_register["n190"]())
    oks += Int(reg.try_register["n191"]())
    oks += Int(reg.try_register["n192"]())
    oks += Int(reg.try_register["n193"]())
    oks += Int(reg.try_register["n194"]())
    oks += Int(reg.try_register["n195"]())
    oks += Int(reg.try_register["n196"]())
    oks += Int(reg.try_register["n197"]())
    oks += Int(reg.try_register["n198"]())
    oks += Int(reg.try_register["n199"]())
    oks += Int(reg.try_register["n200"]())
    oks += Int(reg.try_register["n201"]())
    oks += Int(reg.try_register["n202"]())
    oks += Int(reg.try_register["n203"]())
    oks += Int(reg.try_register["n204"]())
    oks += Int(reg.try_register["n205"]())
    oks += Int(reg.try_register["n206"]())
    oks += Int(reg.try_register["n207"]())
    oks += Int(reg.try_register["n208"]())
    oks += Int(reg.try_register["n209"]())
    oks += Int(reg.try_register["n210"]())
    oks += Int(reg.try_register["n211"]())
    oks += Int(reg.try_register["n212"]())
    oks += Int(reg.try_register["n213"]())
    oks += Int(reg.try_register["n214"]())
    oks += Int(reg.try_register["n215"]())
    oks += Int(reg.try_register["n216"]())
    oks += Int(reg.try_register["n217"]())
    oks += Int(reg.try_register["n218"]())
    oks += Int(reg.try_register["n219"]())
    oks += Int(reg.try_register["n220"]())
    oks += Int(reg.try_register["n221"]())
    oks += Int(reg.try_register["n222"]())
    oks += Int(reg.try_register["n223"]())
    oks += Int(reg.try_register["n224"]())
    oks += Int(reg.try_register["n225"]())
    oks += Int(reg.try_register["n226"]())
    oks += Int(reg.try_register["n227"]())
    oks += Int(reg.try_register["n228"]())
    oks += Int(reg.try_register["n229"]())
    oks += Int(reg.try_register["n230"]())
    oks += Int(reg.try_register["n231"]())
    oks += Int(reg.try_register["n232"]())
    oks += Int(reg.try_register["n233"]())
    oks += Int(reg.try_register["n234"]())
    oks += Int(reg.try_register["n235"]())
    oks += Int(reg.try_register["n236"]())
    oks += Int(reg.try_register["n237"]())
    oks += Int(reg.try_register["n238"]())
    oks += Int(reg.try_register["n239"]())
    oks += Int(reg.try_register["n240"]())
    oks += Int(reg.try_register["n241"]())
    oks += Int(reg.try_register["n242"]())
    oks += Int(reg.try_register["n243"]())
    oks += Int(reg.try_register["n244"]())
    oks += Int(reg.try_register["n245"]())
    oks += Int(reg.try_register["n246"]())
    oks += Int(reg.try_register["n247"]())
    oks += Int(reg.try_register["n248"]())
    oks += Int(reg.try_register["n249"]())
    oks += Int(reg.try_register["n250"]())
    oks += Int(reg.try_register["n251"]())
    oks += Int(reg.try_register["n252"]())
    oks += Int(reg.try_register["n253"]())
    oks += Int(reg.try_register["n254"]())
    oks += Int(reg.try_register["n255"]())
    return oks


def test_full_table_every_name_registers_and_reads_back() raises:
    """All 256 names register and read back by id, displaced or not."""
    var reg = NameRegistry()
    var ids = List[UInt32]()
    var oks = _fill(reg, ids)
    assert_equal(len(ids), MAX_REGISTERED_NAMES)
    # The run-time ids agree with the comptime ids the table was keyed by.
    assert_equal(ids[0], name_id["n000"]())
    assert_equal(ids[137], name_id["n137"]())
    assert_equal(ids[255], name_id["n255"]())
    assert_equal(oks, MAX_REGISTERED_NAMES, "every registration succeeds")
    assert_equal(reg.count(), MAX_REGISTERED_NAMES, "count is the capacity")
    var homes = List[Bool](length=MAX_REGISTERED_NAMES, fill=False)
    var shared = 0
    for i in range(len(ids)):
        var want = _expected_name(i)
        var home = Int(ids[i]) & (MAX_REGISTERED_NAMES - 1)
        if homes[home]:
            shared += 1
        homes[home] = True
        assert_true(reg.contains(ids[i]), String("contains ", want))
        var got = reg.lookup(ids[i])
        assert_true(Bool(got), String("lookup finds ", want))
        assert_equal(got.value(), want, "lookup returns its own name")
    # The fixture is only a probing test if names share home slots.
    assert_true(shared > 0, "some names share a home slot")


def test_full_table_refuses_another_name() raises:
    """The 257th name is refused once every slot is taken."""
    var reg = NameRegistry()
    var ids = List[UInt32]()
    _ = _fill(reg, ids)
    var extra = name_id["n256"]()
    assert_equal(extra, name_id_of(String("n256")))
    for i in range(len(ids)):
        assert_true(ids[i] != extra, "n256 is a new id")
    assert_false(reg.try_register["n256"](), "full table refuses")
    assert_equal(reg.count(), MAX_REGISTERED_NAMES, "count unchanged")
    # An already-registered name is still a no-op on the full table.
    assert_false(reg.try_register["n000"](), "re-registration is a no-op")
    assert_equal(reg.count(), MAX_REGISTERED_NAMES, "count unchanged")


def test_full_table_absent_id_is_absent() raises:
    """lookup and contains of an unregistered id on the full table probe
    every slot and report absent."""
    var reg = NameRegistry()
    var ids = List[UInt32]()
    _ = _fill(reg, ids)
    var absent = List[UInt32]()
    absent.append(name_id["n256"]())
    absent.append(UInt32(0xDEADBEEF))
    for k in range(len(absent)):
        assert_false(reg.contains(absent[k]), "absent id not contained")
        assert_false(Bool(reg.lookup(absent[k])), "absent id has no name")


def main() raises:
    print("test_name_registry_full")
    print("=======================")
    test_full_table_every_name_registers_and_reads_back()
    test_full_table_refuses_another_name()
    test_full_table_absent_id_is_absent()
    print()
    print("ALL TESTS PASS")
