# =============================================================================
# test_wkt_value_null_field.mojo — JSON `null` in a generated message's fields.
# =============================================================================
#
# The proto3 JSON mapping reads `null` in a singular `google.protobuf.Value`
# field as NULL_VALUE (the Value IS the JSON value, and `null` is one) and in
# every other field as "absent", the field's default. The JSON decoder skips
# a null-valued key before it knows the field's type, so a Value field's
# `null` reaches its arm only when the generated `decode` names the key to
# the decoder (`keep_null_fields`). komira-ai/komira#62.
#
# `Holder` (tests/value_null.proto) is generated by protoc-gen-mojo for this
# target, so these tests run the generator's output, not a hand-written copy:
#   * a plain, an `optional` and a oneof-arm Value read `null` as
#     NULL_VALUE, and `{"v":null}` round-trips byte for byte. Fails if the
#     generator stops naming a Value field to the decoder, or the decoder
#     ignores the names it is given.
#   * `null` in every other field shape (repeated and map of Value, Struct,
#     ListValue, a wrapper, an ordinary message, string, int64, optional
#     bool, repeated string) is still absent. Fails if the generator names a
#     non-Value field, or the decoder yields every null-valued key.
# =============================================================================

from std.testing import assert_equal, assert_false, assert_true

from komira_proto_codec import decode_json, encode_json
from komira_wkt import VALUE_KIND_NULL, VALUE_KIND_NUMBER

from value_null_proto.value_null import Holder


def test_plain_value_field_null_is_null_value() raises:
    var h = decode_json[Holder](String('{"v":null}'))
    assert_true(Bool(h.v), "a null Value field decoded as absent")
    assert_equal(h.v.value().kind, VALUE_KIND_NULL)


def test_value_field_null_round_trips() raises:
    # The generated encoder also writes Holder's plain scalars `s` and `n`
    # at their defaults, so the canonical text is not `{"v":null}` alone;
    # what matters is that the `null` is written back and survives again.
    var text = encode_json[Holder](decode_json[Holder](String('{"v":null}')))
    assert_true(text.startswith('{"v":null,'), text)
    assert_equal(encode_json[Holder](decode_json[Holder](text)), text)


def test_optional_value_field_null_is_null_value() raises:
    var h = decode_json[Holder](String('{"optV":null}'))
    assert_true(Bool(h.opt_v), "a null optional Value decoded as absent")
    assert_equal(h.opt_v.value().kind, VALUE_KIND_NULL)
    # The proto spelling of the key is accepted too.
    var p = decode_json[Holder](String('{"opt_v":null}'))
    assert_equal(p.opt_v.value().kind, VALUE_KIND_NULL)


def test_oneof_value_arm_null_sets_the_arm() raises:
    var h = decode_json[Holder](String('{"armV":null}'))
    assert_equal(h._oneof0_case, 1)
    assert_equal(h.arm_v.value().kind, VALUE_KIND_NULL)
    assert_true(encode_json[Holder](h).find('"armV":null') >= 0)


def test_value_field_non_null_is_unchanged() raises:
    var h = decode_json[Holder](String('{"v":2}'))
    assert_equal(h.v.value().kind, VALUE_KIND_NUMBER)
    assert_equal(h.v.value().number_value, 2.0)


def test_null_is_absent_for_every_other_field_type() raises:
    var h = decode_json[Holder](
        String(
            '{"listV":null,"mapV":null,"st":null,"lv":null,"wrapped":null,'
            + '"inner":null,"s":null,"n":null,"b":null,"names":null,'
            + '"armS":null}'
        )
    )
    assert_false(Bool(h.v))
    assert_false(Bool(h.opt_v))
    assert_equal(h._oneof0_case, 0)
    assert_equal(len(h.list_v), 0)
    assert_equal(len(h.map_v), 0)
    assert_false(Bool(h.st))
    assert_false(Bool(h.lv))
    assert_false(Bool(h.wrapped))
    assert_false(Bool(h.inner))
    assert_equal(h.s, String(""))
    assert_equal(h.n, Int64(0))
    assert_false(Bool(h.b))
    assert_equal(len(h.names), 0)
    # And it writes exactly what the empty document does.
    assert_equal(
        encode_json[Holder](h), encode_json[Holder](decode_json[Holder]("{}"))
    )


def main() raises:
    test_plain_value_field_null_is_null_value()
    test_value_field_null_round_trips()
    test_optional_value_field_null_is_null_value()
    test_oneof_value_arm_null_sets_the_arm()
    test_value_field_non_null_is_unchanged()
    test_null_is_absent_for_every_other_field_type()
    print("test_wkt_value_null_field: all tests passed")
