# =============================================================================
# test_corpus_checks.mojo -- each check in corpus.mojo, fed planted defects.
# =============================================================================
#
# test_corpus passes on a clean corpus; this file shows the checks can fail,
# on made-up registrations, file lists and texts (no file is read):
#   partition: a case registered in two shards, or under a shard it does not
#     name, or under no shard; an id holding '/', an empty id; a shard listed
#     twice;
#   files: a case with no expectation, with two, and an orphan file;
#   wire: a build function that raises; a plan nested past the wire's depth
#     limit (plan_wire_admit and plan_from_bytes refuse it);
#   expectation: a column type that differs from the plan's, with a message
#     naming both sides; no derivation, and one citing no item (§) or citing
#     it only before the derivation; a HAND file marked GENERATED; an ORACLE
#     file without `# GENERATED by` as its first comment line; an order header
#     and a float header that differ from the case's policy; cells that are no
#     value of their column (NULL in a non-nullable column, `True` in bool,
#     `1.0` and out-of-range values in integer columns);
#   .err files: the accepted form and each refusal;
#   datasets: a wrong member, a wrong kind, a null in a non-nullable column,
#     a string, a bool and an out-of-range number (1e400, -1e400) in a
#     float64 column, values past either end of int32 and a non-integral
#     one in an int32 column, a missing and an orphan dataset file; for a
#     dataset with any member order, an unknown and a repeated member (and
#     the same permuted line refused by an ordered dataset);
#   inputs: a registered input that is not staged, and an orphan;
#   sparse datasets: a missing nullable column passes, a missing
#     non-nullable one, an undeclared member not named, and a named one
#     twice are refused;
#   oracle rows: one changed cell (22 for 23), a missing and an extra row,
#     a filter boundary row (temp 0) kept, and columns in another order;
#   Avro header: a widened and a narrowed type, a union against a
#     non-nullable column, a renamed field, an unmodelled type, no magic.
#
# NOT planted here, because each needs a broken codec rather than a broken
# case: plan_to_bytes refusing a plan, plan_wire_check_values refusing one,
# and a round trip that changes the structural hash or the root schema. Those
# legs only report what komira_plan_wire's own tests already prove it raises.
# =============================================================================

from std.testing import TestSuite, assert_equal, assert_raises, assert_true

from komira_plan_expr.expr import BIN_EQ, Expr
from komira_plan_expr.scalar_value import ScalarValue
from komira_plan_harness import CanonPolicy, parse_canon
from komira_plan_ir.logical_plan import LogicalPlan
from komira_arrow.arrow_types import ArrowType
from komira_arrow.schema import Field, Schema, SchemaBuilder
from komira_plan_conformance import (
    Case,
    Dataset,
    Registered,
    all_datasets,
    check_cells,
    check_dataset,
    check_dataset_files,
    check_expectation,
    check_files,
    check_input_files,
    check_partition,
    check_schema,
    check_wire,
    parse_err,
)
from komira_plan_conformance.datasets import (
    all_inputs,
    avro_input,
    bool_pairs,
    ints_nullable,
    scan,
    scan_key_order,
    scan_rows,
    scan_sparse,
    sort_rows,
)
from komira_plan_conformance.oracle_checks import (
    RowsFrom,
    check_avro_schema,
    check_rows_from,
)


def _ints() raises -> LogicalPlan:
    return scan(ints_nullable())


def _too_deep() raises -> LogicalPlan:
    var p = scan(ints_nullable())
    for _ in range(40):
        p = LogicalPlan.filter(
            Expr.binary(
                BIN_EQ,
                Expr.col_ref("id"),
                Expr.literal(ScalarValue.from_int64(Int64(1))),
            ),
            p^,
        )
    return p^


def _boom() raises -> LogicalPlan:
    raise Error("boom: planted")


def _case(id: String, shard: String) -> Case:
    return Case.hand(id, shard, _ints, CanonPolicy.unordered())


def _any_contains(problems: List[String], needle: String) -> Bool:
    for p in problems:
        if p.find(needle) >= 0:
            return True
    return False


def _shards() -> List[String]:
    return [String("filter_3vl"), String("agg_grouping")]


def test_partition_clean() raises:
    var regs: List[Registered] = [
        Registered("filter_3vl", _case("a", "filter_3vl")),
        Registered("agg_grouping", _case("b", "agg_grouping")),
    ]
    assert_equal(len(check_partition(regs, _shards())), 0)


def test_partition_case_in_two_shards() raises:
    var regs: List[Registered] = [
        Registered("filter_3vl", _case("a", "filter_3vl")),
        Registered("agg_grouping", _case("a", "filter_3vl")),
    ]
    var p = check_partition(regs, _shards())
    assert_true(_any_contains(p, "registered 2 times, in shards filter_3vl, agg_grouping"))
    assert_true(_any_contains(p, "registered in shard 'agg_grouping' but names shard 'filter_3vl'"))


def test_partition_unknown_shard() raises:
    var regs: List[Registered] = [Registered("nope", _case("a", "nope"))]
    assert_true(_any_contains(check_partition(regs, _shards()), "which is not a shard"))


def test_partition_bad_ids_and_repeated_shard() raises:
    var regs: List[Registered] = [
        Registered("filter_3vl", _case("a/b", "filter_3vl")),
        Registered("filter_3vl", _case("", "filter_3vl")),
    ]
    var p = check_partition(regs, [String("filter_3vl"), String("filter_3vl")])
    assert_true(_any_contains(p, "shard 'filter_3vl' is listed twice"))
    assert_true(_any_contains(p, "case id 'a/b' in shard 'filter_3vl' is empty or holds a '/'"))
    assert_true(_any_contains(p, "case id '' in shard 'filter_3vl' is empty or holds a '/'"))
    assert_equal(len(p), 3)


def test_files_clean() raises:
    var cases: List[Case] = [_case("a", "filter_3vl")]
    assert_equal(len(check_files(cases, [String("expect/filter_3vl/a.tsv")])), 0)


def test_files_missing_second_and_orphan() raises:
    var cases: List[Case] = [_case("a", "filter_3vl"), _case("b", "filter_3vl")]
    var p = check_files(
        cases,
        [
            String("expect/filter_3vl/a.tsv"),
            String("expect/filter_3vl/a.err"),
            String("expect/filter_3vl/zzz.tsv"),
            String("expect/stray.tsv"),
        ],
    )
    assert_true(_any_contains(p, "filter_3vl/b (HAND) has no expectation file expect/filter_3vl/b.tsv"))
    assert_true(_any_contains(p, "second expectation file expect/filter_3vl/a.err"))
    assert_true(_any_contains(p, "expect/filter_3vl/zzz.tsv is an orphan"))
    assert_true(_any_contains(p, "expect/stray.tsv is an orphan"))
    assert_equal(len(p), 4)


def test_wire_refuses_a_plan_past_the_depth_limit() raises:
    var problems = List[String]()
    _ = check_wire(Case.hand("deep", "filter_3vl", _too_deep, CanonPolicy.unordered()), problems)
    assert_true(_any_contains(problems, "plan_wire_admit refused its bytes: PLAN_WIRE_TOO_DEEP"))
    assert_true(_any_contains(problems, "plan_from_bytes refused its bytes: PLAN_WIRE_TOO_DEEP"))


def test_wire_build_raises() raises:
    var problems = List[String]()
    var plan = check_wire(Case.hand("boom", "filter_3vl", _boom, CanonPolicy.unordered()), problems)
    assert_true(not plan)
    assert_equal(len(problems), 1)
    assert_true(problems[0].find("filter_3vl/boom: the plan does not build: boom: planted") >= 0)


def test_wire_clean() raises:
    var problems = List[String]()
    var plan = check_wire(_case("a", "filter_3vl"), problems)
    assert_equal(len(problems), 0)
    assert_true(Bool(plan))


comptime _HEAD = "#! komira-plan-conformance v1\n#  order: none\n#  float: ulps=0\n"


def test_expectation_clean() raises:
    var plan = _ints()
    var text = String(_HEAD) + "# derivation: §1.2\nid:int64\tx:int64?\n1\t1\n"
    assert_equal(len(check_expectation(_case("a", "filter_3vl"), text, plan)), 0)


def test_expectation_wrong_type_names_both_sides() raises:
    var plan = _ints()
    var text = String(_HEAD) + "# derivation: §1.2\nid:int64\tx:int32?\n"
    var p = check_expectation(_case("a", "filter_3vl"), text, plan)
    assert_equal(len(p), 1)
    assert_true(p[0].find("the expectation says `x:int32?`") >= 0)
    assert_true(p[0].find("the plan's root output schema says `x:int64?`") >= 0)
    assert_true(p[0].find("which side is wrong") >= 0)


def test_schema_column_count() raises:
    var p = check_schema("l", [String("a:int64")], [String("a:int64"), String("b:bool?")])
    assert_true(_any_contains(p, "the expectation has 1 columns [a:int64]"))


def test_expectation_needs_a_derivation() raises:
    var plan = _ints()
    var text = String(_HEAD) + "id:int64\tx:int64?\n"
    assert_true(_any_contains(check_expectation(_case("a", "filter_3vl"), text, plan), "needs a `# derivation:` comment"))
    # A derivation that cites no item is refused too.
    var uncited = String(_HEAD) + "# derivation: by inspection\nid:int64\tx:int64?\n"
    assert_true(_any_contains(check_expectation(_case("a", "filter_3vl"), uncited, plan), "needs a `# derivation:` comment"))


def test_expectation_policy_must_match_the_case() raises:
    var plan = _ints()
    var text = String(
        "#! komira-plan-conformance v1\n#  order: total\n#  float: ulps=0\n"
        "# derivation: §1.2\nid:int64\tx:int64?\n"
    )
    assert_true(_any_contains(check_expectation(_case("a", "filter_3vl"), text, plan), "order/float header differs"))


def test_derivation_must_cite_inside_the_derivation() raises:
    var plan = _ints()
    var before = String(_HEAD) + "# see §1.2\n# derivation: by inspection\nid:int64\tx:int64?\n"
    assert_true(_any_contains(check_expectation(_case("a", "filter_3vl"), before, plan), "needs a `# derivation:` comment"))
    var continued = String(_HEAD) + "# derivation: x = NULL is NULL\n# (§1.2)\nid:int64\tx:int64?\n"
    assert_equal(len(check_expectation(_case("a", "filter_3vl"), continued, plan)), 0)


def test_hand_marked_generated() raises:
    var plan = _ints()
    var text = String(_HEAD) + "# derivation: §1.2\n# GENERATED by oracle/gen_expected.py\nid:int64\tx:int64?\n"
    var p = check_expectation(_case("a", "filter_3vl"), text, plan)
    assert_equal(len(p), 1)
    assert_true(p[0].find("the case is HAND but the file says it is GENERATED") >= 0)


def test_oracle_needs_generated_first() raises:
    var plan = _ints()
    var oracle = Case.oracle("a", "filter_3vl", _ints, CanonPolicy.unordered())
    var missing = String(_HEAD) + "# derivation: §1.2\nid:int64\tx:int64?\n"
    assert_true(_any_contains(check_expectation(oracle, missing, plan), "starts its comments with `# GENERATED by`"))
    var late = String(_HEAD) + "# note\n# GENERATED by oracle/gen_expected.py\nid:int64\tx:int64?\n"
    assert_true(_any_contains(check_expectation(oracle, late, plan), "starts its comments with `# GENERATED by`"))
    var good = String(_HEAD) + "# GENERATED by oracle/gen_expected.py\nid:int64\tx:int64?\n"
    assert_equal(len(check_expectation(oracle, good, plan)), 0)


def test_float_header_must_match_the_case() raises:
    var plan = _ints()
    var text = String(
        "#! komira-plan-conformance v1\n#  order: none\n#  float: ulps=1\n"
        "# derivation: §1.2\nid:int64\tx:int64?\n"
    )
    var p = check_expectation(_case("a", "filter_3vl"), text, plan)
    assert_equal(len(p), 1)
    assert_true(p[0].find("order/float header differs") >= 0)
    assert_true(p[0].find("ulps=1") >= 0)


def test_expectation_checks_cells() raises:
    # check_expectation itself must run check_cells, not only the direct
    # call below: a NULL in the non-nullable id column is refused.
    var plan = _ints()
    var text = String(_HEAD) + "# derivation: §1.2\nid:int64\tx:int64?\n\\N\t1\n"
    var p = check_expectation(_case("a", "filter_3vl"), text, plan)
    assert_equal(len(p), 1)
    assert_equal(
        p[0],
        "expect: filter_3vl/a (expect/filter_3vl/a.tsv): row 1 column id:"
        + " `\\N` is not a value of `id:int64`",
    )


def test_cells_must_be_values_of_their_type() raises:
    var parsed = parse_canon(
        "#! komira-plan-conformance v1\n#  order: none\n#  float: ulps=0\n"
        "id:int64\tb:bool?\tn:int64?\tt:int8\tu:uint8?\n"
        "1\ttrue\t1\t-128\t255\n"
        "\\N\t\\N\t\\N\t127\t0\n"
        "2\tTrue\t1.0\t128\t-1\n"
        "-0\tfalse\t01\t-129\t256\n"
    )
    var p = check_cells("w", parsed)
    assert_true(_any_contains(p, "row 2 column id: `\\N` is not a value of `id:int64`"))
    assert_true(_any_contains(p, "row 3 column b: `True` is not a value of `b:bool?`"))
    assert_true(_any_contains(p, "row 3 column n: `1.0` is not a value of `n:int64?`"))
    assert_true(_any_contains(p, "row 3 column t: `128`"))
    assert_true(_any_contains(p, "row 3 column u: `-1`"))
    assert_true(_any_contains(p, "row 4 column id: `-0`"))
    assert_true(_any_contains(p, "row 4 column n: `01`"))
    assert_true(_any_contains(p, "row 4 column t: `-129`"))
    assert_true(_any_contains(p, "row 4 column u: `256`"))
    assert_equal(len(p), 9)


def test_err_accepted() raises:
    var e = parse_err("# derivation: §5.3\nprefix: PLAN_ENDPOINT_EXEC_FAILED(-3)\nkind: Arithmetic\n")
    assert_equal(e.prefix(), "PLAN_ENDPOINT_EXEC_FAILED(-3)")
    assert_equal(e.kind, "Arithmetic")
    assert_true(not e.text)


def test_err_refusals() raises:
    with assert_raises(contains="needs both"):
        _ = parse_err("prefix: PLAN_ENDPOINT_X(1)\n")
    with assert_raises(contains="does not start with"):
        _ = parse_err("prefix: ENDPOINT_X(1)\nkind: k\n")
    with assert_raises(contains="integer <code>"):
        _ = parse_err("prefix: PLAN_ENDPOINT_X(1a)\nkind: k\n")
    with assert_raises(contains="<NAME> in [A-Z0-9_]"):
        _ = parse_err("prefix: PLAN_ENDPOINT_x(1)\nkind: k\n")
    with assert_raises(contains="unknown key"):
        _ = parse_err("prefix: PLAN_ENDPOINT_X(1)\nkind: k\nwhy: no\n")
    with assert_raises(contains="a second kind"):
        _ = parse_err("prefix: PLAN_ENDPOINT_X(1)\nkind: k\nkind: j\n")


def test_dataset_clean() raises:
    assert_equal(len(check_dataset(bool_pairs(), '{"id": 1, "a": true, "b": null}\n')), 0)


def test_dataset_defects() raises:
    var p = check_dataset(
        bool_pairs(),
        '{"id": 1, "b": true, "a": null}\n{"id": null, "a": true, "b": true}\n'
        + '{"id": 3, "a": 1, "b": true}\n{"id": 4, "a": true}\n[1]\n',
    )
    assert_true(_any_contains(p, ":1: member 1 is 'b', the schema's column is 'a'"))
    assert_true(_any_contains(p, ":2: 'id' is null in a non-nullable column"))
    assert_true(_any_contains(p, ":3: 'a' is 1, not a bool"))
    assert_true(_any_contains(p, ":4: 2 members, the schema 3 columns"))
    assert_true(_any_contains(p, ":5: not a JSON object"))


def test_dataset_float_column() raises:
    # A float64 column takes a JSON number with a finite value, -0.0
    # included; a string, a bool and 1e400 (+inf once read) are refused.
    assert_equal(
        len(check_dataset(sort_rows(), '{"id": 1, "a": 1, "b": null, "f": -0.0}\n')), 0
    )
    var p = check_dataset(
        sort_rows(),
        '{"id": 1, "a": 1, "b": 2, "f": "1.5"}\n{"id": 2, "a": 1, "b": 2, "f": true}\n'
        + '{"id": 3, "a": 1, "b": 2, "f": 1e400}\n{"id": 4, "a": 1, "b": 2, "f": -1e400}\n',
    )
    assert_true(_any_contains(p, ":1: 'f' is \"1.5\", not a float64"))
    assert_true(_any_contains(p, ":2: 'f' is true, not a float64"))
    assert_true(_any_contains(p, ":3: 'f' is 1e400, not a finite float64"))
    assert_true(_any_contains(p, ":4: 'f' is -1e400, not a finite float64"))
    assert_equal(len(p), 4)


def test_dataset_files() raises:
    var p = check_dataset_files(
        all_datasets(),
        [
            String("bool_pairs.jsonl"), String("groups.jsonl"),
            String("join_left.jsonl"), String("join_right.jsonl"),
            String("sort_rows.jsonl"), String("int_pairs.jsonl"),
            String("window_rows.jsonl"), String("rank_rows.jsonl"),
            String("stat_rows.jsonl"), String("avg_rows.jsonl"),
            String("div_pairs.jsonl"), String("float_pairs.jsonl"),
            String("set_left.jsonl"), String("set_right.jsonl"),
            String("str_rows.jsonl"), String("scan_rows.jsonl"),
            String("scan_key_order.jsonl"), String("scan_sparse.jsonl"),
            String("scan_numbers.jsonl"), String("frame_rows.jsonl"),
            String("asof_left.jsonl"), String("asof_right.jsonl"),
            String("weather.jsonl"), String("extra.csv"),
        ],
    )
    assert_true(_any_contains(p, "datasets/ints_nullable.jsonl is missing"))
    assert_true(_any_contains(p, "datasets/extra.csv is an orphan"))
    assert_equal(len(p), 2)


def _weather_like() -> Schema:
    """test.Weather's columns, built here rather than taken from
    datasets.weather_schema, so a drift planted there is caught by
    test_corpus, not hidden behind these tests."""
    var sb = SchemaBuilder()
    sb.add_field(Field("station", ArrowType.STRING, False))
    sb.add_field(Field("time", ArrowType.INT64, False))
    sb.add_field(Field("temp", ArrowType.INT32, False))
    return sb.build()


def test_dataset_int32_column() raises:
    # temp is int32: both ends of the range pass; one past either
    # end, a fraction and a string are refused.
    assert_equal(
        len(check_dataset(
            Dataset("w", _weather_like()),
            '{"station": "a", "time": -1, "temp": -2147483648}\n'
            + '{"station": "b", "time": 1, "temp": 2147483647}\n',
        )),
        0,
    )
    var p = check_dataset(
        Dataset("w", _weather_like()),
        '{"station": "a", "time": 1, "temp": 2147483648}\n'
        + '{"station": "a", "time": 1, "temp": -2147483649}\n'
        + '{"station": "a", "time": 1, "temp": 1.0}\n'
        + '{"station": "a", "time": 1, "temp": "1"}\n',
    )
    assert_true(_any_contains(p, ":1: 'temp' is 2147483648, not in the range of int32"))
    assert_true(_any_contains(p, ":2: 'temp' is -2147483649, not in the range of int32"))
    assert_true(_any_contains(p, ":3: 'temp' is 1.0, not a int32"))
    assert_true(_any_contains(p, ":4: 'temp' is \"1\", not a int32"))
    assert_equal(len(p), 4)


def test_dataset_any_member_order() raises:
    # scan_key_order takes each column once in any order; an unknown member
    # and a repeated one are refused, and the kind and null checks still
    # apply by name. scan_rows, the ordered twin, refuses the permuted line.
    var permuted = String('{"s": "", "id": 2, "x": null}\n')
    assert_equal(len(check_dataset(scan_key_order(), permuted)), 0)
    assert_true(
        _any_contains(check_dataset(scan_rows(), permuted), ":1: member 0 is 's', the schema's column is 'id'")
    )
    var p = check_dataset(
        scan_key_order(),
        '{"x": 1, "id": 1, "t": "a"}\n{"x": 1, "id": 1, "x": 2}\n'
        + '{"s": "a", "x": 1, "id": null}\n{"s": 1, "x": 1, "id": 1}\n',
    )
    assert_true(_any_contains(p, ":1: member 't' is not a column of the schema"))
    assert_true(_any_contains(p, ":2: member 'x' appears twice"))
    assert_true(_any_contains(p, ":3: 'id' is null in a non-nullable column"))
    assert_true(_any_contains(p, ":4: 's' is 1, not a string"))
    assert_equal(len(p), 4)


def test_input_files() raises:
    var inputs = all_inputs()
    assert_equal(len(inputs), 4)
    var staged = inputs.copy()
    assert_equal(len(check_input_files(inputs, staged)), 0)
    _ = staged.pop()
    staged.append(String("inputs/avro/weather-bzip2.avro"))
    var p = check_input_files(inputs, staged)
    assert_true(_any_contains(p, "input: " + inputs[3] + " is missing"))
    assert_true(_any_contains(p, "input: inputs/avro/weather-bzip2.avro is an orphan"))
    assert_equal(len(p), 2)
    with assert_raises(contains="no Avro weather file for codec 'bzip2'"):
        _ = avro_input("bzip2")


def test_dataset_sparse() raises:
    assert_equal(
        len(check_dataset(
            scan_sparse(),
            '{"id": 1, "x": 10}\n{"id": 2, "s": "b", "note": "extra"}\n'
            + '{"s": "c", "note": 7, "id": 3, "x": 30}\n',
        )),
        0,
    )
    var p = check_dataset(
        scan_sparse(),
        '{"x": 10}\n{"id": 2, "other": 1}\n{"id": 3, "note": 1, "note": 2}\n',
    )
    assert_true(_any_contains(p, ":1: column 'id' is missing, and it is not nullable"))
    assert_true(_any_contains(p, ":2: member 'other' is not a column of the schema"))
    assert_true(_any_contains(p, ":3: member 'note' appears twice"))
    assert_equal(len(p), 3)
    # A strict any-order dataset still refuses a missing column.
    assert_true(
        _any_contains(check_dataset(scan_key_order(), '{"id": 1, "x": 2}\n'), ":1: 2 members, the schema 3 columns")
    )


comptime _WEATHER = (
    '{"station":"011990-99999","time":-619524000000,"temp":0}\n'
    + '{"station":"011990-99999","time":-619506000000,"temp":22}\n'
    + '{"station":"012650-99999","time":-655531200000,"temp":111}\n'
)


def _cols(a: String, b: String) -> List[String]:
    return [a, b]


def test_rows_from_clean_and_filtered() raises:
    var all = String(_HEAD) + "station:string\ttemp:int32\n" + "011990-99999\t22\n012650-99999\t111\n011990-99999\t0\n"
    assert_equal(len(check_rows_from("c", RowsFrom("w", _cols("station", "temp")), all, _WEATHER)), 0)
    # temp > 0 drops the boundary row temp = 0; keeping it is refused.
    var p = check_rows_from("c", RowsFrom("w", _cols("station", "temp"), "temp", 0), all, _WEATHER)
    assert_equal(len(p), 1)
    assert_equal(p[0], "oracle: c: expected row 3 `011990-99999\t0` is not a row of w")


def test_rows_from_changed_cell() raises:
    # 22 written 23: one row the oracle lacks, one oracle row unexpected.
    var text = String(_HEAD) + "station:string\ttemp:int32\n" + "011990-99999\t0\n011990-99999\t23\n012650-99999\t111\n"
    var p = check_rows_from("scan_avro/full_scan", RowsFrom("datasets/weather.jsonl", _cols("station", "temp")), text, _WEATHER)
    assert_true(_any_contains(p, "oracle: scan_avro/full_scan: expected row 2 `011990-99999\t23` is not a row of datasets/weather.jsonl"))
    assert_true(_any_contains(p, "the row `011990-99999\t22` of datasets/weather.jsonl is missing from the expectation"))
    assert_equal(len(p), 2)


def test_rows_from_missing_extra_and_columns() raises:
    var spec = RowsFrom("w", _cols("station", "temp"))
    var short = String(_HEAD) + "station:string\ttemp:int32\n011990-99999\t0\n011990-99999\t22\n"
    assert_true(_any_contains(check_rows_from("c", spec, short, _WEATHER), "the row `012650-99999\t111` of w is missing"))
    var extra = short + "012650-99999\t111\n012650-99999\t111\n"
    assert_true(_any_contains(check_rows_from("c", spec, extra, _WEATHER), "expected row 4 `012650-99999\t111` is not a row of w"))
    var swapped = String(_HEAD) + "temp:int32\tstation:string\n"
    assert_true(_any_contains(check_rows_from("c", spec, swapped, _WEATHER), "the expectation's columns are [temp, station], the oracle's [station, temp]"))


def _put_zz(mut res: List[UInt8], n: Int):
    """Append `n` as an Avro zig-zag varint."""
    var z = UInt64((n << 1) ^ (n >> 63))
    while z >= 0x80:
        res.append(UInt8((z & 0x7F) | 0x80))
        z >>= 7
    res.append(UInt8(z))


def _ocf_header(schema_json: String) -> List[UInt8]:
    """The header of an Avro object container file: magic, a one-entry
    metadata map holding `avro.schema`, the map's end, a sync marker."""
    var res: List[UInt8] = [0x4F, 0x62, 0x6A, 0x01]
    _put_zz(res, 1)
    var key = String("avro.schema")
    _put_zz(res, key.byte_length())
    for b in key.as_bytes():
        res.append(b)
    _put_zz(res, schema_json.byte_length())
    for b in schema_json.as_bytes():
        res.append(b)
    _put_zz(res, 0)
    for _ in range(16):
        res.append(0xAB)
    return res^


def _weather_avsc(station: String, time: String, temp: String, temp_name: String = "temp") -> String:
    return (
        '{"type":"record","name":"Weather","namespace":"test","fields":['
        + '{"name":"station","type":' + station + '},'
        + '{"name":"time","type":' + time + '},'
        + '{"name":"' + temp_name + '","type":' + temp + '}]}'
    )


def test_avro_schema_clean() raises:
    var h = _ocf_header(_weather_avsc('"string"', '"long"', '"int"'))
    assert_equal(len(check_avro_schema("f", h, _weather_like())), 0)


def test_avro_schema_defects() raises:
    var widened = check_avro_schema("f", _ocf_header(_weather_avsc('"string"', '"long"', '"long"')), _weather_like())
    assert_equal(len(widened), 1)
    assert_equal(widened[0], "avro: f: field 'temp' is int64 in the header, the declared column int32")
    var narrowed = check_avro_schema("f", _ocf_header(_weather_avsc('"string"', '"int"', '"int"')), _weather_like())
    assert_true(_any_contains(narrowed, "field 'time' is int32 in the header, the declared column int64"))
    var union = check_avro_schema("f", _ocf_header(_weather_avsc('["null","string"]', '"long"', '"int"')), _weather_like())
    assert_true(_any_contains(union, "field 'station' is string? in the header, the declared column string"))
    var renamed = check_avro_schema("f", _ocf_header(_weather_avsc('"string"', '"long"', '"int"', "tmp")), _weather_like())
    assert_true(_any_contains(renamed, "field 2 is 'tmp', the declared column is 'temp'"))
    var unmodelled = check_avro_schema("f", _ocf_header(_weather_avsc('"string"', '"double"', '"int"')), _weather_like())
    assert_true(_any_contains(unmodelled, "field 1 'time' has type \"double\", which this check does not model"))
    var not_avro: List[UInt8] = [0x50, 0x41, 0x52, 0x31]
    assert_true(_any_contains(check_avro_schema("f", not_avro, _weather_like()), "not an Avro object container file"))


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
