"""Layer 1: the coarse library pages and the map, rendered from a tree.

A pure function of (tree, docs/kg.toml): read every build file's library rules (Buck2
`BUCK` files are Starlark, which Python's `ast` parses), each library's package header, and
the front matter of every doc; render one page per library and one map. Nothing here
writes; `ops` stages what this renders. Nothing here runs buck2.

INPUTS OF A PAGE, ALL OF THEM: its build rule (the label, and whether `test_srcs` is
non-empty), its package header (`__init__.mojo`'s docstring, or a directory library's
README.md front matter), the front matter of the docs that govern it, the files its header
declares, the `[cells]` of `.buckconfig`, docs/kg.toml and the generator. NOT ON A PAGE:
counts, file lists, deps, line numbers -- they change every commit and would make every
commit rewrite pages. Deps and test files are in the Buck2 graph (`graph.py`).
"""
from __future__ import annotations

import ast
import os
import posixpath
import re

from . import KgError, PAGE_FORMAT
from . import frontmatter, tomlsub
from .gitio import blob_id

GENERATED = ("<!-- GENERATED by `kg build` (page format %d). Do not edit. "
             "On a conflict: `python3 tools/kg/kg.py fix`. -->" % PAGE_FORMAT)
SUMMARY_CAP = 400      # characters of a library summary
NAMES_CAP = 12         # declared entry points / key files per library
PAGE_CAP = 2048        # bytes of a page
MAP_LINE_CAP = 160     # bytes of a map line
SHIM_CAP = 600         # bytes of each provider shim
IMPLEMENTED_VERBS = ("setup", "status", "build", "fix", "check", "hook", "graph", "deps", "rdeps",
                     "tests", "owner")
RESERVED_VERBS = ("ask", "lib", "doc", "where", "outline", "drift", "rules", "selftest")
_ID = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_.-]*$")
_DECL_LINE = re.compile(r"^\s*(Entry points|Key files):\s*(.+?)\s*$", re.M)
_ENTRY = re.compile(r"^([A-Za-z_][\w.]*)\s*(?:\(([^()]+)\))?$")
_VERB_REF = re.compile(r"kg\.py\s+([a-z][a-z-]*)")


class Config:
    KEYS = {"format", "generator", "entry", "pages", "docs", "areas", "shims", "libraries", "ids",
            "canonical", "docs_graph", "graph"}

    def __init__(self, data, name="docs/kg.toml"):
        unknown = sorted(set(data) - self.KEYS)
        if unknown:
            raise KgError("%s: unknown key(s) %s" % (name, ", ".join(unknown)))
        if data.get("format") != PAGE_FORMAT:
            raise KgError("%s: format = %r, but this kg renders page format %d; use the kg that "
                          "matches the tree" % (name, data.get("format"), PAGE_FORMAT))
        self.generator = self._strs(data, "generator", name, required=True)
        self.entry = data.get("entry", "tools/kg/kg.py")
        self.pages = data.get("pages", "docs/libraries").rstrip("/")
        self.docs = data.get("docs", "docs").rstrip("/")
        self.areas = self._strs(data, "areas", name)
        self.shims = self._strs(data, "shims", name)
        # The docs graph: the canonical-doc table and the committed graph file.
        self.canonical = data.get("canonical", "")
        self.docs_graph = data.get("docs_graph", "")
        # The Buck2 code graph (graph.py): the committed file, the query universe, and the
        # `-c section.key=value` overrides that let a checkout without `.buckconfig.local` load it,
        # and the cells deliberately left out of the universe (every other cell must be in it).
        g = data.get("graph", {})
        if not isinstance(g, dict) or set(g) - {"out", "universe", "config", "exclude"}:
            raise KgError("%s: [graph] takes only out, universe, config and exclude" % name)
        self.graph_out = g.get("out", "")
        self.graph_universe = self._strs(g, "universe", name)
        self.graph_config = self._strs(g, "config", name)
        self.graph_exclude = self._strs(g, "exclude", name)
        for k in ("canonical", "docs_graph"):
            if not isinstance(getattr(self, k), str):
                raise KgError("%s: `%s` must be a string" % (name, k))
        if self.graph_out and not self.graph_universe:
            raise KgError("%s: [graph] out is set but universe is empty" % name)
        lib = data.get("libraries", {})
        if not isinstance(lib, dict) or set(lib) - {"rules", "dirs", "exclude", "build_files", "test_attrs"}:
            raise KgError("%s: [libraries] takes only rules, dirs, exclude, build_files and test_attrs" % name)
        self.rules = self._strs(lib, "rules", name) or ["mojo_library"]
        self.build_files = self._strs(lib, "build_files", name) or ["BUCK"]
        self.test_attrs = self._strs(lib, "test_attrs", name) or ["test_srcs"]
        self.dirs = [d.rstrip("/") for d in self._strs(lib, "dirs", name)]
        self.exclude = [d.rstrip("/") + "/" for d in self._strs(lib, "exclude", name)]
        ids = data.get("ids", {})
        if not isinstance(ids, dict) or not all(isinstance(v, str) and _ID.match(v) for v in ids.values()):
            raise KgError("%s: [ids] maps a library directory to an id ([A-Za-z0-9_.-])" % name)
        self.ids = {k.rstrip("/"): v for k, v in ids.items()}

    @staticmethod
    def _strs(d, k, name, required=False):
        v = d.get(k, [])
        if not isinstance(v, list) or not all(isinstance(x, str) and x for x in v) or (required and not v):
            raise KgError("%s: `%s` must be a%s list of strings" % (name, k, " non-empty" if required else ""))
        return v


def load_config(data, name="docs/kg.toml"):
    return Config(tomlsub.loads(data.decode("utf-8") if isinstance(data, bytes) else data, name), name)


class Lib:
    __slots__ = ("id", "dir", "label", "tests", "header", "summary", "entries", "keyfiles", "designs")

    def __init__(self, lid, d, label, tests, header):
        self.id, self.dir, self.label, self.tests, self.header = lid, d, label, tests, header
        self.summary, self.entries, self.keyfiles, self.designs = "", [], [], []


class Model:
    def __init__(self):
        self.libs = {}          # id -> Lib
        self.problems = []      # (library id or None, the source path to change, message): caps and
                                # unreadable front matter. Counted everywhere; `check --base` refuses
                                # the ones whose source path the change touched.
        self.notes = []         # counted, not refused (e.g. a `governs:` naming an unknown id)
        self.refused = []       # refused wherever they are found: dead doc references (docsgraph)


def cells(tree):
    """[(directory, cell name)] from `.buckconfig` [cells], longest directory first; the root
    cell is the one whose directory is `.`. Empty when the tree has no `.buckconfig`."""
    got = tree.read([".buckconfig"]).get(".buckconfig")
    if got is None:
        return []
    res, sect = [], None
    for line in got.decode("utf-8", "replace").splitlines():
        s = line.strip()
        if not s or s.startswith(("#", ";")):
            continue
        if s.startswith("["):
            sect = s.strip("[]").strip()
            continue
        if sect == "cells" and "=" in s:
            k, v = (x.strip() for x in s.split("=", 1))
            d = posixpath.normpath(v)
            res.append(("" if d == "." else d, k))
    return sorted(res, key=lambda x: (-len(x[0]), x[0]))


def buck_label(cellmap, pkg, name=None):
    """The Buck2 label of package `pkg` (a repository path), `cell//pkg:name`."""
    for d, c in cellmap:
        if d == "" or pkg == d or pkg.startswith(d + "/"):
            rel = pkg[len(d):].lstrip("/") if d else pkg
            return "%s//%s%s" % (c, rel, ":" + name if name else "")
    return "//%s%s" % (pkg, ":" + name if name else "")


def _build_files(tree, cfg):
    for p in sorted(tree.paths()):
        if posixpath.basename(p) in cfg.build_files and tree.is_file(p):
            if not any(p.startswith(x) for x in cfg.exclude) and not p.startswith(cfg.pages + "/"):
                yield p


def _pkg_dir_hint(kw):
    """What the rule itself would use when `package_dir` is absent: the directory of the first
    `__init__.mojo` in `srcs` (a literal path), or the literal prefix of a `glob` pattern."""
    srcs = kw.get("srcs")
    if isinstance(srcs, (ast.List, ast.Tuple)):
        for e in srcs.elts:
            if isinstance(e, ast.Constant) and isinstance(e.value, str) and e.value.endswith("__init__.mojo") \
                    and not e.value.startswith((":", "/", "@")):
                return ("file", posixpath.dirname(e.value))
    if isinstance(srcs, ast.Call) and isinstance(srcs.func, ast.Name) and srcs.func.id == "glob" and srcs.args \
            and isinstance(srcs.args[0], ast.List):
        pats = [e.value for e in srcs.args[0].elts if isinstance(e, ast.Constant) and isinstance(e.value, str)]
        return ("glob", [re.split(r"[*?\[]", x, maxsplit=1)[0] for x in pats])
    return None


def _rules(path, text, rule_names, test_attrs=("test_srcs",)):
    try:
        mod = ast.parse(text, filename=path)
    except SyntaxError as e:
        raise KgError("%s:%s: kg cannot read this build file (%s); fix it, or list its directory "
                      "under [libraries] exclude in docs/kg.toml" % (path, e.lineno, e.msg))
    for n in ast.walk(mod):
        if isinstance(n, ast.Call) and isinstance(n.func, ast.Name) and n.func.id in rule_names:
            kw = {k.arg: k.value for k in n.keywords if k.arg}
            name, pdir = kw.get("name"), kw.get("package_dir")
            if not (isinstance(name, ast.Constant) and isinstance(name.value, str)):
                continue
            has_tests = False
            for a in test_attrs:
                t = kw.get(a)
                has_tests = has_tests or (t is not None and not (isinstance(t, (ast.List, ast.Tuple)) and not t.elts))
            if isinstance(pdir, ast.Constant) and isinstance(pdir.value, str):
                yield name.value, ("dir", pdir.value.rstrip("/")), has_tests, n.lineno
            elif pdir is None:
                yield name.value, _pkg_dir_hint(kw), has_tests, n.lineno
            else:
                yield name.value, None, has_tests, n.lineno


def _resolve_dir(tree, pkg, hint):
    if hint is None:
        return None
    kind, v = hint
    if kind == "dir":
        return v
    if kind == "file":
        return posixpath.join(pkg, v) if v else pkg
    inits = []
    for prefix in v:
        base = posixpath.join(pkg, prefix) if prefix else pkg
        inits += [p for p in tree.paths() if p.startswith(base) and p.endswith("/__init__.mojo")]
    if not inits:
        return None
    return posixpath.dirname(min(inits, key=lambda p: (p.count("/"), p)))


def _mojo_header(text):
    """-> (summary, {'Entry points': [...], 'Key files': [...]}) from a leading docstring."""
    lines = text.splitlines()
    i = 0
    while i < len(lines) and (not lines[i].strip() or lines[i].lstrip().startswith("#")):
        i += 1
    body = "\n".join(lines[i:])
    m = re.match(r'[rR]?"""(.*?)"""', body, re.S)
    if not m:
        return "", {}
    doc = m.group(1)
    para = re.split(r"\n\s*\n", doc.strip(), maxsplit=1)[0]
    decl = {k: [x.strip() for x in v.split(",") if x.strip()] for k, v in _DECL_LINE.findall(doc)}
    if _DECL_LINE.match(para):
        para = ""
    return " ".join(para.split()), decl


def _add_cap(model, lib, path, msg):
    model.problems.append((lib, path, msg))


def derive(tree, cfg):
    model = Model()
    by_dir, non_literal = {}, 0
    builds = list(_build_files(tree, cfg))
    blobs = tree.read(builds)
    cellmap = cells(tree)
    for p in builds:
        pkg = posixpath.dirname(p)
        for name, hint, has_tests, line in _rules(p, blobs[p].decode("utf-8", "replace"), cfg.rules, cfg.test_attrs):
            pdir = _resolve_dir(tree, pkg, hint)
            if pdir is None:
                non_literal += 1
                continue
            lab = buck_label(cellmap, pkg, name)
            if pdir in by_dir:
                raise KgError("%s:%d: the package directory %r is already the library %s; one library per "
                              "directory" % (p, line, pdir, by_dir[pdir][0]))
            by_dir[pdir] = (lab, has_tests, pdir + "/__init__.mojo")
    for d in cfg.dirs:
        if d in by_dir:
            raise KgError("docs/kg.toml: [libraries] dirs names %r, which a build rule already declares" % d)
        pkg_label = buck_label(cellmap, d) if any(tree.is_file(d + "/" + b) for b in cfg.build_files) else None
        by_dir[d] = (pkg_label, False, d + "/README.md")
    if non_literal:
        model.notes.append("%d library rule(s) whose package directory is not in the BUILD text (generated "
                           "sources, or a computed package_dir) have no page" % non_literal)
    ids = {}
    for d in sorted(by_dir):
        ids.setdefault(cfg.ids.get(d, posixpath.basename(d)), []).append(d)
    clash = {i: ds for i, ds in ids.items() if len(ds) > 1}
    if clash:
        i, ds = sorted(clash.items())[0]
        raise KgError("library id %r is claimed by %d directories (%s)%s; give each its own id in "
                      "docs/kg.toml [ids], e.g. \"%s\" = \"<id>\"" % (
                          i, len(ds), ", ".join(ds), " and %d more ids clash" % (len(clash) - 1) if len(clash) > 1 else "",
                          ds[0]))
    for i, (d,) in ids.items():
        label, tests, header = by_dir[d]
        model.libs[i] = Lib(i, d, label, tests, header)

    # Headers, then the files they declare.
    heads = tree.read(sorted({lib.header for lib in model.libs.values()}))
    want = set()
    for lib in model.libs.values():
        raw = heads.get(lib.header)
        if raw is None:
            continue
        if lib.header.endswith(".md"):
            try:
                fm = frontmatter.parse(raw, lib.header) or {}
            except KgError as e:
                model.problems.append((lib.id, lib.header, str(e)))
                fm = {}
            summary = fm.get("summary", "")
            decl = {"Entry points": fm.get("entry_points", []), "Key files": fm.get("key_files", [])}
            if not isinstance(summary, str) or not all(isinstance(v, list) for v in decl.values()):
                model.problems.append((lib.id, lib.header, "summary must be a string, entry_points and key_files lists"))
                summary, decl = "", {}
        else:
            summary, decl = _mojo_header(raw[:65536].decode("utf-8", "replace"))
        if len(summary) > SUMMARY_CAP:
            _add_cap(model, lib.id, lib.header, "summary is %d characters (cap %d)" % (len(summary), SUMMARY_CAP))
            summary = summary[:SUMMARY_CAP - 1].rstrip() + "…"
        lib.summary = summary
        for k in ("Entry points", "Key files"):
            names = decl.get(k, [])
            if len(names) > NAMES_CAP:
                _add_cap(model, lib.id, lib.header, "%d %s declared (cap %d)" % (len(names), k.lower(), NAMES_CAP))
                names = names[:NAMES_CAP]
            if k == "Key files":
                lib.keyfiles = names
                want.update(posixpath.join(lib.dir, f) for f in names)
            else:
                for item in names:
                    m = _ENTRY.match(item)
                    lib.entries.append((m.group(1), m.group(2).strip() if m and m.group(2) else None) if m else (item, None))
                    if m and m.group(2):
                        want.add(posixpath.join(lib.dir, m.group(2).strip()))
    files = tree.read(sorted(want))
    for lib in model.libs.values():
        resolved = []
        for name, f in lib.entries:
            ok = False
            if f is not None:
                src = files.get(posixpath.join(lib.dir, f))
                sym = re.escape(name.rsplit(".", 1)[-1])
                ok = src is not None and re.search(
                    (r"^[ \t]*(?:@\w[^\n]*\n[ \t]*)*(?:struct|trait|fn|def|class|alias|comptime|var)\s+%s\b" % sym).encode(),
                    src, re.M) is not None
            resolved.append((name, f, ok))
        lib.entries = resolved
        lib.keyfiles = [(f, posixpath.join(lib.dir, f) in files) for f in lib.keyfiles]

    # Governing docs.
    prefix = cfg.docs + "/"
    docs = sorted(p for p in tree.paths() if p.startswith(prefix) and p.endswith(".md")
                  and not p.startswith(cfg.pages + "/") and tree.is_file(p))
    unknown = 0
    for p, raw in sorted(tree.read(docs).items()):
        try:
            fm = frontmatter.parse(raw, p)
        except KgError as e:
            model.problems.append((None, p, str(e)))
            continue
        if not fm or "governs" not in fm:
            continue
        gov = fm["governs"] if isinstance(fm["governs"], list) else [fm["governs"]]
        status = fm.get("status", "record")
        for g in gov:
            if ":" in g:        # `repo:<id>`, a library of another repository
                continue
            if g in model.libs:
                model.libs[g].designs.append((p, status))
            else:
                unknown += 1
    if unknown:
        model.notes.append("%d `governs:` entr%s name no library in this tree" % (unknown, "y" if unknown == 1 else "ies"))
    return model


def _rel(frm_dir, path):
    return posixpath.relpath(path, frm_dir)


def render(model, cfg):
    """-> {path: bytes}: every page and the map."""
    pages, lines = {}, []
    for i in sorted(model.libs):
        lib = model.libs[i]
        out = [GENERATED, "# " + i, lib.summary or "(no summary declared in %s)" % lib.header]
        if lib.label:
            out.append("- Buck2: `%s`" % lib.label + (" · welded tests: its `test_srcs` run when it is built "
                                                       "(`kg tests %s`)" % lib.label if lib.tests
                                                       else " · no welded tests"))
        else:
            out.append("- Buck2: no package")
        out.append("- Dir: `%s/`" % lib.dir)
        if lib.designs:
            out.append("- Designs: " + " · ".join(
                "[%s](%s) (%s)" % (posixpath.splitext(posixpath.basename(p))[0], _rel(cfg.pages, p), s)
                for p, s in sorted(lib.designs)))
        if lib.entries:
            out.append("- Entry points: " + " · ".join(
                "`%s`%s%s" % (n, " (%s)" % f if f else "", "" if ok else " (unresolved)") for n, f, ok in lib.entries))
        if lib.keyfiles:
            out.append("- Key files: " + ", ".join(f + ("" if ok else " (missing)") for f, ok in lib.keyfiles))
        body = ("\n".join(out) + "\n").encode("utf-8")
        if len(body) > PAGE_CAP:
            model.problems.append((i, lib.header, "page is %d bytes (cap %d)" % (len(body), PAGE_CAP)))
        pages["%s/%s.md" % (cfg.pages, i)] = body
        first = re.split(r"(?<=[.!?])\s", lib.summary, maxsplit=1)[0] if lib.summary else "(no summary)"
        tail = " · " + posixpath.splitext(posixpath.basename(sorted(lib.designs)[0][0]))[0] if lib.designs else ""
        head = "- [%s](%s.md) — " % (i, i)
        room = MAP_LINE_CAP - len((head + tail).encode("utf-8"))
        fb = first.encode("utf-8")
        if len(fb) > room:
            first = fb[:max(0, room - 3)].decode("utf-8", "ignore").rstrip() + "…"
        lines.append(head + first + tail)
    pages[cfg.pages + "/README.md"] = ("\n".join(
        [GENERATED, "# Library map", "",
         "One line per library: its page, the first sentence of its summary, and its first governing design.", ""]
        + lines) + "\n").encode("utf-8")
    return pages


def diff(tree, pages, cfg):
    """-> (changed, removed): rendered pages whose bytes differ from the tree's (or that it
    lacks), and paths under the pages directory that nothing renders."""
    changed = sorted(p for p, b in pages.items() if tree.oid(p) != blob_id(b, tree.algo) or p in tree.unmerged)
    under = cfg.pages + "/"
    removed = sorted(p for p in set(tree.paths()) | tree.unmerged if p.startswith(under) and p not in pages)
    return changed, removed


def check_shims(tree, cfg):
    """-> list of problems with the provider shims (CLAUDE.md, AGENTS.md, GEMINI.md)."""
    if not cfg.shims:
        return []
    probs, bodies = [], {}
    got = tree.read(cfg.shims)
    for s in cfg.shims:
        if s not in got:
            probs.append("%s is missing (docs/kg.toml `shims` names it)" % s)
            continue
        b = got[s]
        if len(b) > SHIM_CAP:
            probs.append("%s is %d bytes (cap %d)" % (s, len(b), SHIM_CAP))
        text = b.decode("utf-8", "replace")
        bodies[s] = text.splitlines()[1:]
        for v in _VERB_REF.findall(text):
            if v not in IMPLEMENTED_VERBS + RESERVED_VERBS:
                probs.append("%s names `kg.py %s`, which is not a kg verb" % (s, v))
    if len({tuple(v) for v in bodies.values()}) > 1:
        probs.append("%s differ after line 1; only line 1 may differ" % ", ".join(sorted(bodies)))
    return probs
