# =============================================================================
# test_implicit_presence_json.mojo — which fields a generated message writes
# into proto3 JSON at their default value.
# =============================================================================
#
# The proto3 JSON mapping omits a field holding its default value when the
# field has implicit presence (a plain proto3 scalar or enum); a REST body
# that carries `"name":""` or `"state":"STATE_UNSPECIFIED"` asks some APIs to
# set that value. A field with explicit presence (`optional`, a oneof member,
# a message) is written whenever it is set, at its default too. A repeated or
# map field is omitted when empty; its elements and entries are written as
# they are. komira-ai/komira#349.
#
# `Plain` (tests/implicit_presence.proto) is generated by protoc-gen-mojo for
# this target, so these tests run the generator's output. Each case decodes a
# document and checks the canonical text it encodes back to:
#   * every implicit-presence kind at its default encodes to `{}`. Fails if
#     the generated guard is missing for any one scalar kind or for enums.
#   * every implicit-presence kind off its default is written. Fails if a
#     guard is inverted or tests the wrong default (a `-0.0` float is not the
#     default: its sign is data, so the float guard reads the bits).
#   * `optional`, oneof members and messages at their default are written.
#     Fails if the guard is applied to an explicit-presence field.
#   * the protobuf binary encoding still writes the defaults: the omission is
#     the JSON backend's choice (`OMITS_IMPLICIT_DEFAULTS`), not a change of
#     binary bytes. Fails if the guard stops reading the encoder's constant.
# =============================================================================

from std.testing import assert_equal, assert_true

from komira_proto_codec import decode_json, encode_json, encode_proto

from implicit_presence_proto.implicit_presence import Plain


def _canonical(doc: String) raises -> String:
    return encode_json[Plain](decode_json[Plain](doc))


def _same(doc: String) raises:
    """`doc` is canonical: it encodes back byte for byte."""
    assert_equal(_canonical(doc), doc)


def test_implicit_defaults_are_omitted() raises:
    assert_equal(_canonical(String("{}")), String("{}"))
    assert_equal(
        _canonical(
            String(
                '{"s":"","by":"","b":false,"i32":0,"i64":"0","u32":0,'
                + '"u64":"0","si32":0,"si64":"0","f32x":0,"f64x":"0",'
                + '"sf32":0,"sf64":"0","fl":0,"db":0,'
                + '"color":"COLOR_UNSPECIFIED"}'
            )
        ),
        String("{}"),
    )
    # One at a time, so a failure names the kind.
    var defaults = List[String]()
    defaults.append(String('{"s":""}'))
    defaults.append(String('{"by":""}'))
    defaults.append(String('{"b":false}'))
    defaults.append(String('{"i32":0}'))
    defaults.append(String('{"i64":"0"}'))
    defaults.append(String('{"u32":0}'))
    defaults.append(String('{"u64":"0"}'))
    defaults.append(String('{"si32":0}'))
    defaults.append(String('{"si64":"0"}'))
    defaults.append(String('{"f32x":0}'))
    defaults.append(String('{"f64x":"0"}'))
    defaults.append(String('{"sf32":0}'))
    defaults.append(String('{"sf64":"0"}'))
    defaults.append(String('{"fl":0}'))
    defaults.append(String('{"db":0}'))
    defaults.append(String('{"color":"COLOR_UNSPECIFIED"}'))
    for d in defaults:
        assert_equal(_canonical(d), String("{}"), d)


def test_implicit_values_are_written() raises:
    _same(String('{"s":"x"}'))
    _same(String('{"by":"AQ=="}'))
    _same(String('{"b":true}'))
    _same(String('{"i32":-1}'))
    _same(String('{"i64":"-1"}'))
    _same(String('{"u32":1}'))
    _same(String('{"u64":"1"}'))
    _same(String('{"si32":-1}'))
    _same(String('{"si64":"-1"}'))
    _same(String('{"f32x":1}'))
    _same(String('{"f64x":"1"}'))
    _same(String('{"sf32":-1}'))
    _same(String('{"sf64":"-1"}'))
    _same(String('{"fl":1.5}'))
    _same(String('{"db":2.5}'))
    _same(String('{"color":"COLOR_RED"}'))
    # A negative zero is not the default.
    assert_true(_canonical(String('{"db":-0.0}')).startswith('{"db":-0'))
    assert_true(_canonical(String('{"fl":-0.0}')).startswith('{"fl":-0'))


def test_explicit_presence_is_written_at_the_default() raises:
    _same(String('{"optS":""}'))
    _same(String('{"optN":"0"}'))
    _same(String('{"optB":false}'))
    _same(String('{"optColor":"COLOR_UNSPECIFIED"}'))
    assert_true(_canonical(String('{"optD":0}')).startswith('{"optD":0'))
    _same(String('{"armS":""}'))
    _same(String('{"armN":"0"}'))
    _same(String('{"armColor":"COLOR_UNSPECIFIED"}'))
    _same(String('{"inner":{}}'))
    # The message is written; its own implicit default is not.
    assert_equal(_canonical(String('{"inner":{"name":""}}')), '{"inner":{}}')


def test_repeated_and_map_fields() raises:
    assert_equal(_canonical(String('{"names":[],"counts":{}}')), String("{}"))
    _same(String('{"names":[""],"counts":{"":"0"}}'))


def test_binary_still_writes_the_defaults() raises:
    var bytes = encode_proto[Plain](decode_json[Plain](String("{}")))
    # Field 1 (`s`), length-delimited, empty: tag 0x0A, length 0.
    assert_true(len(bytes) >= 2)
    assert_equal(Int(bytes[0]), 0x0A)
    assert_equal(Int(bytes[1]), 0x00)


def main() raises:
    test_implicit_defaults_are_omitted()
    test_implicit_values_are_written()
    test_explicit_presence_is_written_at_the_default()
    test_repeated_and_map_fields()
    test_binary_still_writes_the_defaults()
    print("test_implicit_presence_json: all tests passed")
