# =============================================================================
# komira_git_conformance/tests/test_digests.mojo -- komira_git's `Sha1dc`
# against sha1collisiondetection's C, digest and verdict, under every
# combination of the four switches.
# =============================================================================
#
# WHAT EACH TEST CATCHES:
#   * test_corpus: a digest or verdict that differs from upstream's on
#     ordinary input: every length 0 to 300 (every padding position) and
#     multi-block lengths, generated bytes, fed whole to both.
#   * test_chunked: buffering differences: the same 70000 bytes fed to each
#     side in pieces of generated sizes (0 to 200 bytes), different on each
#     side.
#   * test_collision_files: the verdict and digest on the two SHAttered
#     PDFs and upstream's reduced-round collision, under all 16 switch
#     combinations: detection, the safe hash, the bit-condition filter and
#     reduced-round detection must each act as upstream's do. All three
#     files are detected through one disturbance vector, DV 27 (II(52,0),
#     recompressed from step 65); test_recompression pins the other DVs.
#   * test_near_collisions: the recompression and the comparison that
#     decides a collision, on near misses: each SHAttered PDF's first 384
#     bytes (its collision blocks are bytes 192 to 319) with one bit flipped,
#     for every bit of those two blocks, under the default switches and with
#     the filter off (every DV recompressed). A detection that fires where
#     upstream's does not, or stops firing where upstream's still does, is
#     a different verdict.
# =============================================================================

from std.pathlib import Path
from std.testing import assert_equal

from komira_git import Sha1dc

from komira_git_conformance import CSha1dc


def _hex(d: InlineArray[UInt8, 20]) -> String:
    var s = String()
    for i in range(20):
        var v = Int(d[i])
        s += chr(48 + (v >> 4) if (v >> 4) < 10 else 87 + (v >> 4))
        s += chr(48 + (v & 15) if (v & 15) < 10 else 87 + (v & 15))
    return s^


def _corpus(n: Int, seed: UInt64) -> List[UInt8]:
    var out = List[UInt8](capacity=n)
    var x = seed
    for _ in range(n):
        x = x * 6364136223846793005 + 1442695040888963407
        out.append(UInt8((x >> 33) & 0xFF))
    return out^


def _ours(data: Span[UInt8, _], combo: Int) -> String:
    var h = Sha1dc()
    h.set_safe_hash((combo & 1) == 0)
    h.set_use_ubc((combo & 2) == 0)
    h.set_detect_collision((combo & 4) == 0)
    h.set_detect_reduced_round_collision((combo & 8) != 0)
    h.update(data)
    var d = InlineArray[UInt8, 20](fill=0)
    var found = h.finalize_into(d)
    return _hex(d) + (" coll" if found else " ok")


def _theirs(data: Span[UInt8, _], combo: Int) -> String:
    var h = CSha1dc()
    h.set_safe_hash((combo & 1) == 0)
    h.set_use_ubc((combo & 2) == 0)
    h.set_detect_collision((combo & 4) == 0)
    h.set_detect_reduced_round_collision((combo & 8) != 0)
    h.update(data)
    var d = InlineArray[UInt8, 20](fill=0)
    var found = h.finalize_into(d)
    return _hex(d) + (" coll" if found else " ok")


def _same(data: Span[UInt8, _], combo: Int, what: String) raises:
    assert_equal(
        _ours(data, combo), _theirs(data, combo), what + ", switches " + String(combo)
    )


def test_corpus() raises:
    var lengths = List[Int]()
    for n in range(301):
        lengths.append(n)
    lengths.append(1024)
    lengths.append(4096 + 61)
    lengths.append(65536 + 3)
    for i in range(len(lengths)):
        var n = lengths[i]
        var data = _corpus(n, UInt64(n) * 31 + 5)
        for combo in range(16):
            _same(Span(data), combo, "length " + String(n))


def test_chunked() raises:
    var data = _corpus(70000, 99)
    var ours = Sha1dc()
    var theirs = CSha1dc()
    var x: UInt64 = 12345
    var a = 0
    var b = 0
    while a < len(data) or b < len(data):
        x = x * 6364136223846793005 + 1442695040888963407
        var na = min(Int((x >> 40) % 201), len(data) - a)
        var nb = min(Int((x >> 20) % 201), len(data) - b)
        ours.update(Span(data)[a : a + na])
        theirs.update(Span(data)[b : b + nb])
        a += na
        b += nb
    var d1 = InlineArray[UInt8, 20](fill=0)
    var d2 = InlineArray[UInt8, 20](fill=0)
    var f1 = ours.finalize_into(d1)
    var f2 = theirs.finalize_into(d2)
    assert_equal(_hex(d1), _hex(d2))
    assert_equal(f1, f2)


def test_collision_files() raises:
    var names = List[String]()
    names.append("shattered-1.pdf")
    names.append("shattered-2.pdf")
    names.append("sha1_reducedsha_coll.bin")
    for i in range(len(names)):
        var data = Path(String("sha1dc/test/") + names[i]).read_bytes()
        for combo in range(16):
            _same(Span(data), combo, names[i])


def test_near_collisions() raises:
    for f in range(2):
        var name = String("shattered-") + String(f + 1) + ".pdf"
        var full = Path(String("sha1dc/test/") + name).read_bytes()
        var data = List[UInt8](capacity=384)
        for i in range(384):
            data.append(full[i])
        _same(Span(data), 0, name + " first 384 bytes")
        for bit in range(192 * 8, 320 * 8):
            var byte = bit // 8
            var flip = UInt8(1) << UInt8(bit % 8)
            data[byte] ^= flip
            var what = name + " bit " + String(bit) + " flipped"
            _same(Span(data), 0, what)
            _same(Span(data), 2, what)
            data[byte] ^= flip


def main() raises:
    test_corpus()
    test_chunked()
    test_collision_files()
    test_near_collisions()
    print("komira_git_conformance digest tests passed")
