# =============================================================================
# semantics-locking tests for Decimal128 arithmetic,
# comparison, and casts.
# =============================================================================
#
# Primary oracle: DuckDB.  The expected values below were generated by
# shelling out to a local `duckdb` at dev time; the literals are pasted in
# here so the test has no live-oracle dependency (CI has no duckdb-on-PATH
# guarantee).  Where DuckDB and the spec rule diverge it is noted:
#
#   - decimal `/` : DuckDB-the-engine promotes `DECIMAL / DECIMAL` to DOUBLE
#     and does float division (verified: `typeof(1.0::DECIMAL(10,2)/3.0::
#     DECIMAL(10,2))` is `DOUBLE`).  We implement a true DECIMAL division
#     per the arrow-rs/Hive rule (result_scale = min(s1+4, 38)) with HALF_UP
#     rounding (round half away from zero) — that is what PostgreSQL's
#     `numeric / numeric` does, and what Python `decimal.Decimal` with
#     ROUND_HALF_UP gives.  arrow-rs's `div` kernel TRUNCATES toward zero;
#     we deliberately diverge.  The division expectations below were
#     cross-checked with `python3 -c "from decimal import *; ..."` (HALF_UP).
#   - mul result *precision*: DuckDB uses a bucketed `p1+p2`; the spec rule
#     (which we follow) is `min(p1+p2+1, 38)`.  The *value* and *scale* are
#     the same either way — we assert value+scale, not the precision tag.
#   - decimal->int : HALF_UP (round half away from zero) — MEASURED DuckDB
#     v1.5.3, (3.5 -> 4, -2.5 -> -3, 3.99 -> 4). This line used to
#     say "TRUNCATE toward zero (DuckDB + DataFusion + arrow-rs; only
#     PostgreSQL rounds)", and the test below pinned 3.99 -> 3: the test
#     ASSERTED the silent wrong answer.
#
# The engine-dispatch cases exercise the executor's compute layer
# (_eval_column_expr / _eval_predicate — the same path PipelineCompiler
# drives) over hand-built RecordBatches + Exprs, not just the kernels.
# =============================================================================

from std.testing import TestSuite, assert_equal, assert_true, assert_false

from komira_core.arrow import PrimitiveArray, BooleanArray, Bitmap
from komira_core.arrow.column import Column
from komira_core.arrow.arrow_types import ArrowType
from komira_core.arrow.decimal_array import Decimal128Array
from komira_core.arrow.schema import Schema, SchemaBuilder, Field, RecordBatch, RecordBatchBuilder
from komira_core.arrow.string_array import StringArray
from komira_core.eval.decimal_arith import (
    I128,
    decimal_add_i128, decimal_sub_i128, decimal_mul_i128, decimal_div_i128,
    decimal_add_result_ps, decimal_mul_result_ps, decimal_div_result_ps,
)
from komira_core.eval.decimal_compare import (
    decimal_cmp_i128, DEC_CMP_LT, DEC_CMP_LE, DEC_CMP_GT, DEC_CMP_GE, DEC_CMP_EQ, DEC_CMP_NE,
)
from komira_core.eval.decimal_cast import (
    int_to_decimal_i128, float_to_decimal_i128, decimal_to_float64,
    decimal_to_int64, decimal_rescale_i128, decimal_to_string, string_to_decimal_i128,
)
from komira_core.plan.expr import Expr, BIN_ADD, BIN_SUB, BIN_MUL, BIN_DIV, BIN_GT, BIN_LT, BIN_EQ, BIN_GE
from komira_core.plan.scalar_value import ScalarValue
from komira_compiler.compiler_eval_column import _eval_column_expr
from komira_compiler.compiler_eval_predicate import _eval_predicate


# =============================================================================
# Helpers
# =============================================================================


def _max_dec128() raises -> I128:
    """10^38 - 1 — the largest-magnitude Decimal128 value."""
    var m = I128(10)
    for _ in range(37):
        m = m * I128(10)
    return m - I128(1)


def _i(v: I128) -> Int:
    """Truncate an int128 to a platform Int (for asserts on small values)."""
    return Int(v.cast[DType.int64]())


def _dec_col(vals: List[Int64], precision: Int, scale: Int, name: String = "a") raises -> RecordBatch:
    """One-column non-null DECIMAL128 RecordBatch from already-scaled i64s."""
    var n = len(vals)
    var arr = Decimal128Array.allocate(n, precision, scale)
    for i in range(n):
        arr.set_i128(i, I128(Int(vals[i])))
    var sb = SchemaBuilder()
    sb.add_field(Field.decimal128(name, precision, scale, False))
    var rbb = RecordBatchBuilder()
    rbb.add_column(Column.from_decimal128(arr^))
    return rbb.build(sb.build())


def _two_dec_col(
    a_vals: List[Int64], a_p: Int, a_s: Int,
    b_vals: List[Int64], b_p: Int, b_s: Int,
) raises -> RecordBatch:
    """Two-column DECIMAL128 RecordBatch ('a' and 'b')."""
    var n = len(a_vals)
    var aa = Decimal128Array.allocate(n, a_p, a_s)
    for i in range(n):
        aa.set_i128(i, I128(Int(a_vals[i])))
    var bb = Decimal128Array.allocate(n, b_p, b_s)
    for i in range(n):
        bb.set_i128(i, I128(Int(b_vals[i])))
    var sb = SchemaBuilder()
    sb.add_field(Field.decimal128("a", a_p, a_s, False))
    sb.add_field(Field.decimal128("b", b_p, b_s, False))
    var rbb = RecordBatchBuilder()
    rbb.add_column(Column.from_decimal128(aa^))
    rbb.add_column(Column.from_decimal128(bb^))
    return rbb.build(sb.build())


# =============================================================================
# Arithmetic — add / sub
# =============================================================================


def test_decimal_add_scale_tracking() raises:
    # 1.23 (D(3,2)) + 4.5 (D(2,1))  ->  5.73 at scale 2  [DuckDB: D(4,2) 5.73]
    var ps = decimal_add_result_ps(3, 2, 2, 1)
    assert_equal(ps[1], 2)        # result scale = max(s1,s2)
    assert_equal(ps[0], 4)        # result precision = max(p1-s1,p2-s2)+s+1 = 1+2+1
    var r = decimal_add_i128(I128(123), 2, I128(45), 1, ps[1])
    assert_equal(_i(r), 573)
    # 100.00 (D(5,2)) - 0.01 (D(3,2))  ->  99.99  [DuckDB: D(6,2) 99.99]
    var r2 = decimal_sub_i128(I128(10000), 2, I128(1), 2, 2)
    assert_equal(_i(r2), 9999)
    # mixed scales: 1.5 (D(2,1)) + 2.250 (D(4,3))  ->  3.750 at scale 3
    var ps3 = decimal_add_result_ps(2, 1, 4, 3)
    assert_equal(ps3[1], 3)
    var r3 = decimal_add_i128(I128(15), 1, I128(2250), 3, ps3[1])
    assert_equal(_i(r3), 3750)
    # 0 + 0 -> 0
    var r4 = decimal_add_i128(I128(0), 0, I128(0), 0, 0)
    assert_equal(_i(r4), 0)
    # negative: -5.50 (D(3,2)) + 3.25 (D(3,2))  ->  -2.25  [DuckDB: -2.25]
    var r5 = decimal_add_i128(I128(-550), 2, I128(325), 2, 2)
    assert_equal(_i(r5), -225)


def test_decimal_add_overflow_raises() raises:
    # (10^38 - 1) + 1  ->  raises (overflow-checked by default)
    var m = _max_dec128()
    var raised = False
    try:
        _ = decimal_add_i128(m, 0, I128(1), 0, 0)
    except e:
        raised = True
    assert_true(raised)
    # -(10^38 - 1) - 1  ->  raises (negative overflow)
    var raised2 = False
    try:
        _ = decimal_sub_i128(-m, 0, I128(1), 0, 0)
    except e:
        raised2 = True
    assert_true(raised2)
    # also: rescaling-up overflows.  Max D(38,0) value, add at scale 1 with a
    # scale-0 operand needing *10 to align -> 10^39 -> overflow.
    var raised3 = False
    try:
        _ = decimal_add_i128(m, 0, I128(0), 0, 1)
    except e:
        raised3 = True
    assert_true(raised3)


# =============================================================================
# Arithmetic — mul
# =============================================================================


def test_decimal_mul_scale_tracking() raises:
    # 1.23 (D(3,2)) * 4.5 (D(2,1))  ->  5.535 at scale 3 (= 2+1)
    var ps = decimal_mul_result_ps(3, 2, 2, 1)
    assert_equal(ps[1], 3)
    var r = decimal_mul_i128(I128(123), I128(45))
    assert_equal(_i(r), 5535)
    # 0.10 (D(3,2)) * 0.10 (D(3,2))  ->  0.0100 at scale 4  [DuckDB: 0.0100]
    var ps2 = decimal_mul_result_ps(3, 2, 3, 2)
    assert_equal(ps2[1], 4)
    var r2 = decimal_mul_i128(I128(10), I128(10))
    assert_equal(_i(r2), 100)
    # 12345.67 (D(7,2)) * 1.0 (D(2,1))  ->  12345.670 at scale 3  [DuckDB: D(9,3)]
    var r3 = decimal_mul_i128(I128(1234567), I128(10))
    assert_equal(_i(r3), 12345670)
    # negative: -5.50 (D(3,2)) * 2.0 (D(2,1))  ->  -11.000 at scale 3
    var r4 = decimal_mul_i128(I128(-550), I128(20))
    assert_equal(_i(r4), -11000)


def test_decimal_mul_overflow_and_scale_limit() raises:
    # (10^38 - 1) * 10  ->  raises (value overflow)
    var m = _max_dec128()
    var raised = False
    try:
        _ = decimal_mul_i128(m, I128(10))
    except e:
        raised = True
    assert_true(raised)
    # mul where s1 + s2 > 38  ->  result-type computation raises (matches
    # DuckDB's "Needed scale 40 ... out of range").  D(38,20) * D(38,20).
    var raised2 = False
    try:
        _ = decimal_mul_result_ps(38, 20, 38, 20)
    except e:
        raised2 = True
    assert_true(raised2)
    # mul with p1+p2+1 > 38 but s1+s2 <= 38: precision clamps to 38, value
    # raises only on true >38-digit overflow.  D(20,2) * D(20,2) -> p clamps.
    var ps = decimal_mul_result_ps(20, 2, 20, 2)
    assert_equal(ps[0], 38)
    assert_equal(ps[1], 4)


# =============================================================================
# Arithmetic — div  (HALF_UP, deliberate divergence from arrow-rs)
# =============================================================================


def test_decimal_div_half_up_rounding() raises:
    # 1.00 / 3.00  (D(10,2)/D(10,2)) -> scale min(2+4,38)=6 -> 0.333333
    #   100*10^6/300 = 333333.33..  -> HALF_UP (7th digit 3) -> 333333
    #   Cross-check: python decimal HALF_UP gave 333333.  (DuckDB-the-engine
    #   would give DOUBLE 0.3333... — different shape; we match PG/Python.)
    var ps = decimal_div_result_ps(10, 2, 10, 2)
    assert_equal(ps[1], 6)
    var r = decimal_div_i128(I128(100), 2, I128(300), 2, ps[1])
    assert_equal(_i(r), 333333)
    # 2.00 / 3.00 -> 666666.66.. -> HALF_UP (7th digit 6) -> 666667
    var r2 = decimal_div_i128(I128(200), 2, I128(300), 2, ps[1])
    assert_equal(_i(r2), 666667)
    # 10.00 / 4.00 -> 2.500000 exact
    var r3 = decimal_div_i128(I128(1000), 2, I128(400), 2, ps[1])
    assert_equal(_i(r3), 2500000)
    # -7.5 / 2.5  (D(3,1)/D(3,1)) -> scale min(1+4,38)=5 -> -3.00000
    var psn = decimal_div_result_ps(3, 1, 3, 1)
    assert_equal(psn[1], 5)
    var r4 = decimal_div_i128(I128(-75), 1, I128(25), 1, psn[1])
    assert_equal(_i(r4), -300000)
    # half-up tie, both signs: 1 / 8 = 0.125 exact at scale >= 3; force a tie
    # by using scale s1+4 where the last kept digit ties.  1 / 2 at scale 0
    # numerator: D(1,0)/D(1,0) -> scale min(0+4,38)=4 -> 1*10^4 / 2 = 5000 ->
    # 0.5000 exact.  Use 1 / 4 ... still exact.  Force a true tie: 5 / 2 at
    # scale 0 -> D(1,0)/D(1,0) -> scale 4 -> 5*10^4 / 2 = 25000 -> 2.5000.
    # To get a tie at the result scale we need a remainder of exactly half:
    # 1 / 8 with one fewer digit than needed: at scale 2 -> 100/8 = 12 r 4;
    # 2*4 = 8 == 8 (div) -> round up -> 13 -> 0.13.  Verify via direct call:
    var r5 = decimal_div_i128(I128(1), 0, I128(8), 0, 2)   # 1/8 -> 0.13 (HALF_UP at scale 2)
    assert_equal(_i(r5), 13)
    var r6 = decimal_div_i128(I128(-1), 0, I128(8), 0, 2)  # -1/8 -> -0.13 (away from zero)
    assert_equal(_i(r6), -13)
    # ⛔ NEGATIVE NON-TIES: the -1/8 tie above rounds right by
    # coincidence; -1/3 at scale 2 is -0.333.. -> -0.33, and was -0.34 while
    # the remainder was Mojo's FLOORED `%`. -2/3 -> -0.67 (not a tie either).
    assert_equal(_i(decimal_div_i128(I128(-1), 0, I128(3), 0, 2)), -33)
    assert_equal(_i(decimal_div_i128(I128(-2), 0, I128(3), 0, 2)), -67)
    assert_equal(_i(decimal_div_i128(I128(1), 0, I128(-3), 0, 2)), -33)
    assert_equal(_i(decimal_div_i128(I128(-1), 0, I128(-3), 0, 2)), 33)


def test_decimal_div_by_zero_raises() raises:
    var raised = False
    try:
        _ = decimal_div_i128(I128(1), 0, I128(0), 0, 4)
    except e:
        raised = True
    assert_true(raised)
    # zero numerator / nonzero denom -> 0, no raise.
    var r = decimal_div_i128(I128(0), 2, I128(300), 2, 6)
    assert_equal(_i(r), 0)


# =============================================================================
# Comparison — scale-aligned
# =============================================================================


def test_decimal_compare_scale_mismatch() raises:
    # 1.20 (D(3,2)) == 1.2 (D(2,1))  -> TRUE  [DuckDB: true]
    assert_true(decimal_cmp_i128(I128(120), 2, I128(12), 1, DEC_CMP_EQ))
    # 1.5 (D(2,1)) < 1.50 (D(3,2))  -> FALSE (equal)
    assert_false(decimal_cmp_i128(I128(15), 1, I128(150), 2, DEC_CMP_LT))
    assert_true(decimal_cmp_i128(I128(15), 1, I128(150), 2, DEC_CMP_LE))
    # 1.500 (D(4,3)) > 1.49 (D(3,2))  -> TRUE  [DuckDB: true]
    assert_true(decimal_cmp_i128(I128(1500), 3, I128(149), 2, DEC_CMP_GT))
    # negatives
    assert_true(decimal_cmp_i128(I128(-225), 2, I128(-3), 0, DEC_CMP_GT))   # -2.25 > -3
    assert_true(decimal_cmp_i128(I128(0), 2, I128(0), 5, DEC_CMP_EQ))
    # NE / GE round out the op map.
    assert_true(decimal_cmp_i128(I128(120), 2, I128(13), 1, DEC_CMP_NE))    # 1.20 != 1.3
    assert_true(decimal_cmp_i128(I128(120), 2, I128(12), 1, DEC_CMP_GE))


def test_decimal_compare_i256_extreme() raises:
    # D(38,0) huge value vs D(38,38) tiny value — the rescale of the D(38,0)
    # value up by 10^38 overflows i128 but fits i256 (10^76 < 2^255).  Lock
    # that the comparison is correct so a future change can't silently break
    # the i256-comparison path.
    var huge = _max_dec128()                # 10^38 - 1 at scale 0  (~1e38)
    var tiny = I128(1)                       # 1 at scale 38  (= 1e-38)
    assert_true(decimal_cmp_i128(huge, 0, tiny, 38, DEC_CMP_GT))
    assert_false(decimal_cmp_i128(tiny, 38, huge, 0, DEC_CMP_GT))
    assert_true(decimal_cmp_i128(huge, 0, huge, 0, DEC_CMP_EQ))


# =============================================================================
# Casts
# =============================================================================


def test_cast_int_to_decimal() raises:
    assert_equal(_i(int_to_decimal_i128(Int64(42), 10, 2)), 4200)     # 42::D(10,2) = 4200
    assert_equal(_i(int_to_decimal_i128(Int64(42), 2, 0)), 42)        # 42::D(2,0)
    assert_equal(_i(int_to_decimal_i128(Int64(-7), 5, 3)), -7000)
    # 1000 :: D(3,0)  ->  raises (doesn't fit precision)
    var raised = False
    try:
        _ = int_to_decimal_i128(Int64(1000), 3, 0)
    except e:
        raised = True
    assert_true(raised)


def test_cast_float_to_decimal() raises:
    # 3.14159 :: D(10,2) -> 3.14  (HALF_UP: 314.159 -> 314)  [DuckDB: 3.14]
    var f1 = float_to_decimal_i128(Float64(3.14159), 10, 2)
    assert_true(Bool(f1))
    assert_equal(_i(f1.value()), 314)
    # 2.5 :: D(3,0) -> 3 (round half away from zero)  [DuckDB: 3]
    var f2 = float_to_decimal_i128(Float64(2.5), 3, 0)
    assert_equal(_i(f2.value()), 3)
    # -2.5 :: D(3,0) -> -3 (away from zero)  [DuckDB: -3]
    var f3 = float_to_decimal_i128(Float64(-2.5), 3, 0)
    assert_equal(_i(f3.value()), -3)
    # 0.005 :: D(10,2) -> 0.01  (the IEEE double nearest 0.005 is slightly
    # ABOVE 0.005, so *100 = 0.5000..0104 -> HALF_UP -> 1)  [DuckDB: 0.01]
    var f4 = float_to_decimal_i128(Float64(0.005), 10, 2)
    assert_equal(_i(f4.value()), 1)
    # NaN / +Inf / -Inf  ->  NULL (safe-cast semantics)
    var nan = Float64(0.0) / Float64(0.0)
    assert_false(Bool(float_to_decimal_i128(nan, 10, 2)))
    var inf = Float64(1.0) / Float64(0.0)
    assert_false(Bool(float_to_decimal_i128(inf, 10, 2)))
    assert_false(Bool(float_to_decimal_i128(-inf, 10, 2)))
    # 1e40 :: D(38,0)  ->  NULL (float->decimal overflow in safe mode)
    assert_false(Bool(float_to_decimal_i128(Float64(1.0e40), 38, 0)))


def test_cast_decimal_to_int_rounds_half_away_from_zero() raises:
    # Every expectation MEASURED on DuckDB v1.5.3, e.g.
    # `SELECT CAST(3.99::DECIMAL(12,2) AS INTEGER)` -> 4. Until that date this
    # test was `..._truncates` and asserted 3.99 -> 3 / -3.99 -> -3 — pinning
    # the engine's silent wrong answer as the contract.
    assert_equal(Int(decimal_to_int64(I128(399), 2)), 4)     # 3.99  -> 4
    assert_equal(Int(decimal_to_int64(I128(-399), 2)), -4)   # -3.99 -> -4
    assert_equal(Int(decimal_to_int64(I128(500), 2)), 5)     # 5.00  -> 5
    # ⭐ THE TIES, BOTH SIGNS — the cells that separate HALF_UP from half to
    # EVEN (DOUBLE -> BIGINT's rule): 2.5 -> 3 (even would say 2), -2.5 -> -3.
    assert_equal(Int(decimal_to_int64(I128(250), 2)), 3)     # 2.50  -> 3
    assert_equal(Int(decimal_to_int64(I128(-250), 2)), -3)   # -2.50 -> -3
    assert_equal(Int(decimal_to_int64(I128(35000), 4)), 4)   # 3.5000 -> 4
    # Just under a tie stays down; scale 0 is the identity.
    assert_equal(Int(decimal_to_int64(I128(749), 2)), 7)     # 7.49  -> 7
    assert_equal(Int(decimal_to_int64(I128(-749), 2)), -7)   # -7.49 -> -7
    assert_equal(Int(decimal_to_int64(I128(-42), 0)), -42)


def test_cast_decimal_to_float() raises:
    # 3.14 :: DOUBLE -> 3.14 (within tolerance)
    var f = decimal_to_float64(I128(314), 2)
    assert_true(f > 3.139 and f < 3.141)
    var fz = decimal_to_float64(I128(0), 2)
    assert_equal(fz, 0.0)


def test_cast_decimal_rescale() raises:
    # 1.5 (D(2,1)) :: D(10,4) -> 1.5000  [DuckDB: 1.5000]
    assert_equal(_i(decimal_rescale_i128(I128(15), 1, 10, 4)), 15000)
    # 1.2345 (D(5,4)) :: D(5,2) -> 1.23  (HALF_UP on 2345 -> next digit 4 rounds down)
    assert_equal(_i(decimal_rescale_i128(I128(12345), 4, 5, 2)), 123)
    # 1.2355 (D(5,4)) :: D(5,2) -> 1.24  (next digit 5 -> round up)
    assert_equal(_i(decimal_rescale_i128(I128(12355), 4, 5, 2)), 124)
    # 1.99 (D(3,2)) :: D(2,0) -> 2  (rescale-down rounds; 2 is 1 digit, fits)
    assert_equal(_i(decimal_rescale_i128(I128(199), 2, 2, 0)), 2)
    # 99.99 (D(4,2)) :: D(2,2)  ->  raises (value 9999 has 4 digits > prec 2)
    var raised = False
    try:
        _ = decimal_rescale_i128(I128(9999), 2, 2, 2)
    except e:
        raised = True
    assert_true(raised)
    # 99.99 (D(4,2)) :: D(5,4)  ->  raises (UPSCALE overflows precision:
    # 999900 has 6 digits > precision 5)
    var raised2 = False
    try:
        _ = decimal_rescale_i128(I128(9999), 2, 5, 4)
    except e:
        raised2 = True
    assert_true(raised2)


def test_cast_decimal_to_string() raises:
    # No trailing-zero trimming; '-' prefix; '0.' left-pad; no point at scale 0.
    assert_equal(decimal_to_string(I128(500), 2), "5.00")          # [DuckDB: 5.00]
    assert_equal(decimal_to_string(I128(5), 2), "0.05")           # [DuckDB: 0.05]
    assert_equal(decimal_to_string(I128(-1230), 2), "-12.30")     # [DuckDB: -12.30]
    assert_equal(decimal_to_string(I128(1234), 0), "1234")        # [DuckDB: 1234]
    assert_equal(decimal_to_string(I128(0), 2), "0.00")
    assert_equal(decimal_to_string(I128(-5), 2), "-0.05")
    assert_equal(decimal_to_string(I128(50), 2), "0.50")          # [PG: 0.50]


def test_cast_string_to_decimal() raises:
    assert_equal(_i(string_to_decimal_i128(String("5"), 10, 2)), 500)       # '5' -> 5.00 (pad)
    assert_equal(_i(string_to_decimal_i128(String("5.00"), 10, 2)), 500)
    assert_equal(_i(string_to_decimal_i128(String("5.005"), 10, 2)), 501)   # HALF_UP -> 5.01
    assert_equal(_i(string_to_decimal_i128(String("1.5e3"), 10, 2)), 150000)  # scientific -> 1500.00
    assert_equal(_i(string_to_decimal_i128(String(" 1.50 "), 10, 2)), 150)  # surrounding ws trimmed
    assert_equal(_i(string_to_decimal_i128(String("-12.30"), 10, 2)), -1230)
    # garbage / empty / embedded whitespace -> raises
    for bad in [String("abc"), String(""), String("1 2"), String("  ")]:
        var raised = False
        try:
            _ = string_to_decimal_i128(bad, 10, 2)
        except e:
            raised = True
        assert_true(raised)


def test_decimal_string_roundtrip() raises:
    # (v :: VARCHAR) :: DECIMAL(p,s) == v  for a spread of values at scale 2.
    var vals = [I128(0), I128(500), I128(-1230), I128(99999), I128(-7), I128(123456789)]
    for v in vals:
        var s = decimal_to_string(v, 2)
        var back = string_to_decimal_i128(s, 18, 2)
        assert_equal(_i(back), _i(v))


# =============================================================================
# Engine dispatch — exercises _eval_column_expr / _eval_predicate (the
# executor's compute layer), not just the kernels.
# =============================================================================


def test_engine_decimal_add_projection() raises:
    # SELECT a + b  over two DECIMAL128 columns; result column carries (p,s).
    # a = [1.23, 100.00, -5.50] at D(7,2); b = [4.50, 0.01, 3.25] at D(7,2)
    var batch = _two_dec_col(
        [Int64(123), Int64(10000), Int64(-550)], 7, 2,
        [Int64(450), Int64(1), Int64(325)], 7, 2,
    )
    var e = Expr.binary(BIN_ADD, Expr.col_ref("a"), Expr.col_ref("b"))
    var col = _eval_column_expr(e, batch)
    assert_true(col.arrow_type == ArrowType.DECIMAL128)
    assert_equal(col.decimal_scale(), 2)
    var out = col.as_decimal128()
    assert_equal(_i(out.get_i128(0)), 573)    # 5.73
    assert_equal(_i(out.get_i128(1)), 10001)  # 100.01
    assert_equal(_i(out.get_i128(2)), -225)   # -2.25


def test_engine_decimal_mul_projection() raises:
    # SELECT a * b  -> scale = s1 + s2.
    var batch = _two_dec_col(
        [Int64(123), Int64(10)], 7, 2,
        [Int64(45), Int64(10)], 5, 1,
    )
    var e = Expr.binary(BIN_MUL, Expr.col_ref("a"), Expr.col_ref("b"))
    var col = _eval_column_expr(e, batch)
    assert_true(col.arrow_type == ArrowType.DECIMAL128)
    assert_equal(col.decimal_scale(), 3)
    var out = col.as_decimal128()
    assert_equal(_i(out.get_i128(0)), 5535)   # 1.23 * 4.5 = 5.535
    assert_equal(_i(out.get_i128(1)), 100)    # 0.10 * 1.0 = 0.100


def test_engine_decimal_cast_projection() raises:
    # SELECT CAST(a AS DECIMAL(10,4))  (upscale rescale)
    var batch = _dec_col([Int64(123), Int64(-50)], 5, 2, "a")
    var e = Expr.cast_to_decimal(Expr.col_ref("a"), 10, 4)
    var col = _eval_column_expr(e, batch)
    assert_true(col.arrow_type == ArrowType.DECIMAL128)
    assert_equal(col.decimal_scale(), 4)
    var out = col.as_decimal128()
    assert_equal(_i(out.get_i128(0)), 12300)  # 1.23 -> 1.2300
    assert_equal(_i(out.get_i128(1)), -5000)  # -0.50 -> -0.5000
    # SELECT CAST(a AS DOUBLE)
    var e2 = Expr.cast(Expr.col_ref("a"), DType.float64)
    var col2 = _eval_column_expr(e2, batch)
    assert_true(col2.arrow_type == ArrowType.FLOAT64)
    var out2 = col2.as_primitive[DType.float64]()
    assert_true(out2.get(0) > 1.229 and out2.get(0) < 1.231)


def _nullable_dec_col(name: String) raises -> RecordBatch:
    """One nullable DECIMAL(12,2) column: [10.25, NULL, 30.75]."""
    var arr = Decimal128Array.allocate_nullable(3, 12, 2)
    arr.set_i128(0, I128(1025))
    arr.set_null(1)
    arr.set_i128(2, I128(3075))
    var sb = SchemaBuilder()
    sb.add_field(Field.decimal128(name, 12, 2, True))
    var rbb = RecordBatchBuilder()
    rbb.add_column(Column.from_decimal128(arr^))
    return rbb.build(sb.build())


def test_engine_float_over_decimal_keeps_a_null_null() raises:
    """`CAST(120 AS DOUBLE) / d` over a DECIMAL `d` holding a NULL -> NULL.

    ⛔ RED BEFORE: the mixed decimal/float
    arm of `_eval_column_expr` promoted the decimal side to float64 (its
    validity kept) and divided, but returned the kernel's result WITHOUT
    `merge_binary_arith_validity` -- the one arithmetic arm that skipped it --
    so the NULL row came back VALID holding `120 / 0 = inf`. MEASURED at the
    untyped Mojo and typed doors: `lit(120) / col("v")` over decimal128(12,2)
    answered inf where DuckDB 1.5.3 answers NULL (`proj_truediv`, allnull /
    nulls). The same arm serves `+`, `-`, `*`."""
    var batch = _nullable_dec_col(String("d"))
    var lhs = Expr.cast(Expr.literal(ScalarValue.from_int(120)), DType.float64)
    var e = Expr.binary(BIN_DIV, lhs^, Expr.col_ref("d"))
    var col = _eval_column_expr(e, batch)
    assert_true(col.arrow_type == ArrowType.FLOAT64)
    assert_true(col.is_null_at(1), "120 / NULL must be NULL, not inf")
    assert_false(col.is_null_at(0))
    assert_false(col.is_null_at(2))
    var out = col.as_primitive[DType.float64]()
    assert_true(out.get(0) > 11.7073 and out.get(0) < 11.7074, "120 / 10.25")
    # `d * CAST(2 AS DOUBLE)` through the same arm, the decimal on the LEFT.
    var rhs = Expr.cast(Expr.literal(ScalarValue.from_int(2)), DType.float64)
    var e2 = Expr.binary(BIN_MUL, Expr.col_ref("d"), rhs^)
    var col2 = _eval_column_expr(e2, batch)
    assert_true(col2.is_null_at(1), "NULL * 2.0 must be NULL")
    assert_false(col2.is_null_at(0))


def test_engine_decimal_predicate() raises:
    # WHERE a > 100.50  over a D(7,2) column.  Literal as a decimal literal.
    var batch = _dec_col([Int64(5000), Int64(10049), Int64(10051), Int64(20000)], 7, 2, "a")
    var lit = ScalarValue.decimal128_i128(I128(10050), 7, 2)   # 100.50
    var e = Expr.binary(BIN_GT, Expr.col_ref("a"), Expr.literal(lit^))
    var mask = _eval_predicate(e, batch)
    assert_false(mask.get(0))   # 50.00 > 100.50 ? no
    assert_false(mask.get(1))   # 100.49 > 100.50 ? no
    assert_true(mask.get(2))    # 100.51 > 100.50 ? yes
    assert_true(mask.get(3))    # 200.00 > 100.50 ? yes
    # WHERE a == 100.51 (different scale literal: 1.0051e2 at scale 2 vs col scale 2)
    var lit2 = ScalarValue.decimal128_i128(I128(10051), 7, 2)
    var e2 = Expr.binary(BIN_EQ, Expr.col_ref("a"), Expr.literal(lit2^))
    var mask2 = _eval_predicate(e2, batch)
    assert_false(mask2.get(0))
    assert_true(mask2.get(2))
    # int literal promoted: WHERE a >= 100  ->  rows 1,2,3
    var e3 = Expr.binary(BIN_GE, Expr.col_ref("a"), Expr.literal(ScalarValue.from_int(100)))
    var mask3 = _eval_predicate(e3, batch)
    assert_false(mask3.get(0))
    assert_true(mask3.get(1))
    assert_true(mask3.get(2))
    assert_true(mask3.get(3))


def test_engine_decimal_col_vs_col_predicate() raises:
    # WHERE a < b  over two DECIMAL128 columns with different scales.
    var batch = _two_dec_col(
        [Int64(100), Int64(250), Int64(150)], 5, 2,   # 1.00, 2.50, 1.50
        [Int64(15), Int64(20), Int64(149)], 5, 1,     # 1.5, 2.0, 14.9
    )
    var e = Expr.binary(BIN_LT, Expr.col_ref("a"), Expr.col_ref("b"))
    var mask = _eval_predicate(e, batch)
    assert_true(mask.get(0))    # 1.00 < 1.5 ? yes
    assert_false(mask.get(1))   # 2.50 < 2.0 ? no
    assert_true(mask.get(2))    # 1.50 < 14.9 ? yes


def test_engine_decimal_nullable_arith() raises:
    # NULL propagation: a + b where some 'a' rows are NULL -> result NULL.
    var n = 3
    var aa = Decimal128Array.allocate_nullable(n, 7, 2)
    aa.set_i128(0, I128(123))
    aa.set_null(1)
    aa.set_i128(2, I128(500))
    var bb = Decimal128Array.allocate(n, 7, 2)
    bb.set_i128(0, I128(100))
    bb.set_i128(1, I128(999))
    bb.set_i128(2, I128(50))
    var sb = SchemaBuilder()
    sb.add_field(Field.decimal128("a", 7, 2, True))
    sb.add_field(Field.decimal128("b", 7, 2, False))
    var rbb = RecordBatchBuilder()
    rbb.add_column(Column.from_decimal128(aa^))
    rbb.add_column(Column.from_decimal128(bb^))
    var batch = rbb.build(sb.build())
    var e = Expr.binary(BIN_ADD, Expr.col_ref("a"), Expr.col_ref("b"))
    var col = _eval_column_expr(e, batch)
    var out = col.as_decimal128()
    assert_false(out.is_null(0))
    assert_equal(_i(out.get_i128(0)), 223)
    assert_true(out.is_null(1))    # NULL + 9.99 -> NULL
    assert_false(out.is_null(2))
    assert_equal(_i(out.get_i128(2)), 550)


# =============================================================================
# Type-layer round-trips
# =============================================================================


def test_scalar_value_decimal_roundtrip() raises:
    var v = I128(123456789012345)
    var sv = ScalarValue.decimal128_i128(v, 18, 4)
    assert_true(sv.is_decimal128())
    assert_equal(sv.dec128_precision, 18)
    assert_equal(sv.dec128_scale, 4)
    assert_equal(_i(sv.decimal_value_i128()), _i(v))
    # negative + max-magnitude
    var vn = -_max_dec128()
    var svn = ScalarValue.decimal128_i128(vn, 38, 0)
    assert_equal(_i(svn.decimal_value_i128()), _i(vn))
    # equality respects (p, s)
    var a = ScalarValue.decimal128_i128(I128(100), 10, 2)
    var b = ScalarValue.decimal128_i128(I128(100), 10, 2)
    var c = ScalarValue.decimal128_i128(I128(100), 10, 3)
    assert_true(a == b)
    assert_false(a == c)


def test_column_decimal_roundtrip() raises:
    var arr = Decimal128Array.from_i128_list([I128(12345), I128(-67), I128(0)], 10, 2)
    var col = Column.from_decimal128(arr)
    assert_true(col.arrow_type == ArrowType.DECIMAL128)
    assert_equal(col.decimal_precision(), 10)
    assert_equal(col.decimal_scale(), 2)
    var back = col.as_decimal128()
    assert_equal(back.precision, 10)
    assert_equal(back.scale, 2)
    assert_equal(_i(back.get_i128(0)), 12345)
    assert_equal(_i(back.get_i128(1)), -67)
    assert_equal(_i(back.get_i128(2)), 0)


def test_field_decimal_constraints() raises:
    # 0 <= scale <= precision <= 38 enforced.
    var ok = Field.decimal128("x", 10, 2, True)
    assert_equal(ok.decimal_precision, 10)
    assert_equal(ok.decimal_scale, 2)
    for bad in [(0, 0), (39, 2), (5, 6), (5, -1)]:
        var raised = False
        try:
            _ = Field.decimal128("x", bad[0], bad[1], True)
        except e:
            raised = True
        assert_true(raised)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
