# =============================================================================
# semantics-locking tests for regexp_like /
# regexp_matches / regexp_extract.
# =============================================================================
#
# Primary oracle: DuckDB (RE2, a Thompson-NFA engine — same engine class as
# our pure-Mojo Pike VM, so the dialect matches by construction).  Expected
# values below were generated by shelling out to a local `duckdb` at dev
# time (`duckdb -csv -c "SELECT regexp_matches(...)..."`) and pasted in as
# literals — the test has no live-oracle dependency (CI has no
# duckdb-on-PATH guarantee).  Secondary cross-check: PostgreSQL `~` /
# `regexp_match` (POSIX ERE) — agrees with DuckDB on every case here.
#
# Known divergences from DuckDB, deliberate (noted at the call sites):
#   - The flags-string letter `m`: DuckDB's `'m'` option means
#     "newline-sensitive `.`" (RE2's `n` option); our `m` (and DataFusion's,
#     and PCRE's, and RE2's *inline* `(?m)`) means "multiline anchors
#     (`^`/`$` match line boundaries)".  We follow the design doc /
#     DataFusion meaning.  DuckDB's `(?m)` *inline* flag IS multiline
#     anchors, so we cross-check `(?m)` against DuckDB; the flags-string
#     `m` is tested against RE2-API semantics with a comment.
#   - `regexp_extract(s, p, group)` where `group` > the pattern's
#     capture-group count: DuckDB returns `''` (the group "didn't
#     participate"); only `group < 0` or `group > 9` errors.  We match.
#
# The engine-dispatch cases run `_eval_column_expr` / `_eval_predicate` —
# the same compute path PipelineCompiler drives — over hand-built
# RecordBatches + `Expr.regexp_*` nodes, not just the NFA kernel.  (The SDK
# `df.col("s").regexp_like(...)` Expr-overload surface is separate; the
# contract those overloads target — `Expr.regexp_like` / `Expr.regexp_extract`
# — is defined and exercised here.)
# =============================================================================

from std.testing import TestSuite, assert_equal, assert_true, assert_false

from komira_core.arrow import BooleanArray, Bitmap
from komira_core.io.heap_region import HeapRegion
from komira_core.arrow.column import Column
from komira_core.arrow.arrow_types import ArrowType
from komira_core.arrow.schema import Schema, SchemaBuilder, Field, RecordBatch, RecordBatchBuilder
from komira_core.arrow.string_array import StringArray
from komira_core.plan.expr import Expr
from komira_core.eval.regexp_nfa import RegexProgram
from komira_core.eval.regexp_functions import (
    eval_regexp_like, eval_regexp_extract, regexp_like_scalar, regexp_extract_scalar,
)
from komira_compiler.compiler_eval_column import _eval_column_expr
from komira_compiler.compiler_eval_predicate import _eval_predicate


# ---------------------------------------------------------------------------
# Helpers.
# ---------------------------------------------------------------------------

def _like(subject: String, pattern: String, flags: String = "") raises -> Bool:
    var prog = RegexProgram.compile(pattern, flags)
    return regexp_like_scalar(subject, prog)


def _extract(subject: String, pattern: String, group: Int = 0, flags: String = "") raises -> String:
    var prog = RegexProgram.compile(pattern, flags)
    return regexp_extract_scalar(subject, prog, group)


def _raises(pattern: String, flags: String = "") -> Bool:
    try:
        _ = RegexProgram.compile(pattern, flags)
        return False
    except e:
        return True


def _str_col(vals: List[String], name: String = "s") raises -> RecordBatch:
    var arr = StringArray.from_strings(vals)
    var sb = SchemaBuilder()
    sb.add_field(Field(name, ArrowType.STRING, False))
    var rbb = RecordBatchBuilder()
    rbb.add_column(Column.from_string(arr^))
    return rbb.build(sb.build())


# ---------------------------------------------------------------------------
# Basic literal / unanchored proof.   DuckDB:
#   regexp_matches('abc','b')=t  regexp_matches('abc','x')=f
#   regexp_matches('abc','abc')=t  regexp_matches('abc','abcd')=f
#   regexp_matches('foobar','oob')=t  regexp_matches('foobar','^bar')=f
#   regexp_matches('foobar','bar$')=t
# ---------------------------------------------------------------------------

def test_basic_literal() raises:
    assert_true(_like("abc", "b"))
    assert_false(_like("abc", "x"))
    assert_true(_like("abc", "abc"))
    assert_false(_like("abc", "abcd"))


def test_unanchored() raises:
    # Proves regexp_like is NOT accidentally whole-string-anchored.
    assert_true(_like("foobar", "oob"))
    assert_false(_like("foobar", "^bar"))
    assert_true(_like("foobar", "bar$"))


# ---------------------------------------------------------------------------
# Anchors.  DuckDB:
#   regexp_matches('abc','^abc$')=t  regexp_matches('xabc','^abc')=f
#   regexp_matches('abcx','abc$')=f
#   regexp_matches('foo bar','\bbar\b')=t  regexp_matches('foobar','\bbar\b')=f
#   regexp_matches(chr10-joined 'a\nworld','(?m)^world$')=t  (inline (?m))
# ---------------------------------------------------------------------------

def test_anchors() raises:
    assert_true(_like("abc", "^abc$"))
    assert_false(_like("xabc", "^abc"))
    assert_false(_like("abcx", "abc$"))
    # \A / \z absolute anchors (RE2 / Perl).
    assert_true(_like("abc", "\\Aabc\\z"))
    assert_false(_like("xabc", "\\Aabc"))


def test_word_boundary() raises:
    assert_true(_like("foo bar", "\\bbar\\b"))
    assert_false(_like("foobar", "\\bbar\\b"))
    assert_true(_like("foobar", "\\Bbar\\b"))   # 'bar' preceded by a word byte


def test_multiline() raises:
    # Inline (?m) — DuckDB cross-check: regexp_matches('a\nworld', '(?m)^world$')=t.
    var s = String("a") + chr(10) + "world"
    assert_true(_like(s, "(?m)^world$"))
    assert_false(_like(s, "^world$"))    # without multiline, ^ == \A
    # The flags-string `m` means "multiline anchors" in our dialect / RE2-API
    # / DataFusion (DuckDB's flags-string `m` means newline-sensitive `.`
    # instead — a documented divergence; we follow the design doc).
    assert_true(_like(s, "^world$", "m"))


# ---------------------------------------------------------------------------
# Char classes.  DuckDB:
#   regexp_matches('555-1234','\d{3}-\d{4}')=t  regexp_matches('55-1234','\d{3}-\d{4}')=f
#   regexp_matches('Hello','[[:alpha:]]+')=t
# ---------------------------------------------------------------------------

def test_char_classes() raises:
    assert_true(_like("555-1234", "\\d{3}-\\d{4}"))
    assert_false(_like("55-1234", "\\d{3}-\\d{4}"))
    assert_true(_like("Hello", "[[:alpha:]]+"))
    assert_true(_like("abc", "[a-c]+"))
    assert_false(_like("a1c", "^[a-c]+$"))    # '1' not in [a-c]
    assert_true(_like("a1c", "[^0-9]"))       # contains a non-digit
    assert_false(_like("123", "^[^0-9]+$"))
    assert_true(_like("foo_bar", "\\w+"))
    assert_true(_like("a b", "\\s"))
    assert_false(_like("ab", "\\s"))
    # Negated predefined: \D = non-digit.
    assert_true(_like("a1", "\\D"))
    assert_false(_like("123", "^\\D"))
    # Escaped metachar inside / outside a class.
    assert_true(_like("a.b", "a\\.b"))
    assert_false(_like("axb", "^a\\.b$"))
    assert_true(_like("[3.14]", "[\\d.]+"))   # \d and . both literal-ish in class


def test_dot_and_dotall() raises:
    assert_true(_like("axb", "a.b"))
    assert_false(_like(String("a") + chr(10) + "b", "a.b"))      # `.` doesn't match \n
    assert_true(_like(String("a") + chr(10) + "b", "a.b", "s"))  # ...unless dotall
    assert_true(_like(String("a") + chr(10) + "b", "(?s)a.b"))   # ...or inline (?s)


# ---------------------------------------------------------------------------
# Quantifiers.  DuckDB:
#   regexp_matches('','a*')=t  regexp_matches('','a+')=f
#   regexp_matches('aaaa','a{2,3}')=t  regexp_matches('aaaa','a{2,3}$')=t
#   regexp_matches('aaa','(?:a*)*')=t
# ---------------------------------------------------------------------------

def test_quantifiers() raises:
    assert_true(_like("", "a*"))
    assert_false(_like("", "a+"))
    assert_true(_like("aaaa", "a{2,3}"))
    assert_true(_like("aaaa", "a{2,3}$"))    # chars 2-4 = 'aaa', then $ -> true
    assert_false(_like("a", "^a{2,3}$"))
    assert_true(_like("aa", "^a{2,3}$"))
    assert_true(_like("aaa", "^a{2,3}$"))
    assert_false(_like("aaaa", "^a{2,3}$"))
    assert_true(_like("aaa", "(?:a*)*"))     # nested grouped quantifier — legal
    assert_true(_like("xxx", "^x{3}$"))
    assert_false(_like("xx", "^x{3}$"))
    assert_true(_like("xxxx", "^x{3,}$"))
    assert_false(_like("xx", "^x{3,}$"))
    assert_true(_like("ab", "^a?b$"))
    assert_true(_like("b", "^a?b$"))
    assert_false(_like("aab", "^a?b$"))


# ---------------------------------------------------------------------------
# Alternation + grouping.   DuckDB:
#   regexp_matches('I have a dog','(cat|dog|bird)')=t
# ---------------------------------------------------------------------------

def test_alternation() raises:
    assert_true(_like("I have a dog", "(cat|dog|bird)"))
    assert_false(_like("I have a fish", "^(cat|dog|bird)$"))
    # Alternation precedence: `a|bc` = `a` OR `bc`, not `(ab)|c`.
    assert_true(_like("a", "^(?:a|bc)$"))
    assert_true(_like("bc", "^(?:a|bc)$"))
    assert_false(_like("ab", "^(?:a|bc)$"))
    assert_false(_like("c", "^(?:a|bc)$"))
    # Three-way at top level.
    assert_true(_like("y", "^x|y|z$"))


# ---------------------------------------------------------------------------
# Capture extraction (regexp_extract).   DuckDB:
#   regexp_extract('','(\d+)-(\d+)',1)='2026'
#   regexp_extract('','(\d+)-(\d+)',0)='2026-05'
#   regexp_extract('','(\d+)-(\d+)')='2026-05'
#   regexp_extract('abc','x',0)=''
#   regexp_extract('John Smith','(\w+) (\w+)',2)='Smith'
#   regexp_extract('ab','((a)(b))',1)='ab'  regexp_extract('ab','((a)(b))',2)='a'
#   regexp_extract('b','(a)?(b)',1)=''  regexp_extract('b','(a)?(b)',2)='b'
#   regexp_extract('<a><b>','<(.*?)>',1)='a'  regexp_extract('<a><b>','<(.*)>',1)='a><b'
#   regexp_extract('','(a)',1)=''
# ---------------------------------------------------------------------------

def test_extract_basic() raises:
    assert_equal(_extract("2026-05-11", "(\\d+)-(\\d+)", 1), "2026")
    assert_equal(_extract("2026-05-11", "(\\d+)-(\\d+)", 0), "2026-05")
    assert_equal(_extract("2026-05-11", "(\\d+)-(\\d+)"), "2026-05")   # default group 0
    assert_equal(_extract("abc", "x", 0), "")                          # no match -> '' (NOT NULL)
    assert_equal(_extract("abc", "x"), "")
    assert_equal(_extract("", "(a)", 1), "")
    assert_equal(_extract("John Smith", "(\\w+) (\\w+)", 2), "Smith")
    assert_equal(_extract("John Smith", "(\\w+) (\\w+)", 1), "John")


def test_extract_nested_groups() raises:
    assert_equal(_extract("ab", "((a)(b))", 0), "ab")
    assert_equal(_extract("ab", "((a)(b))", 1), "ab")
    assert_equal(_extract("ab", "((a)(b))", 2), "a")
    assert_equal(_extract("ab", "((a)(b))", 3), "b")


def test_extract_optional_group() raises:
    # Group 1 (the `(a)?`) did not participate on input "b" -> '', not error.
    assert_equal(_extract("b", "(a)?(b)", 1), "")
    assert_equal(_extract("b", "(a)?(b)", 2), "b")
    assert_equal(_extract("ab", "(a)?(b)", 1), "a")


def test_extract_greedy_vs_nongreedy() raises:
    assert_equal(_extract("<a><b>", "<(.*?)>", 1), "a")        # non-greedy
    assert_equal(_extract("<a><b>", "<(.*)>", 1), "a><b")      # greedy
    assert_equal(_extract("aaa", "a*", 0), "aaa")              # greedy whole-match
    assert_equal(_extract("aaa", "a*?", 0), "")               # non-greedy: prefers empty


def test_extract_out_of_range_group() raises:
    # DuckDB: group index > n_groups but <= 9 -> '' (group didn't participate).
    assert_equal(_extract("abc", "(a)(b)(c)", 5), "")
    # group < 0 or > 9 -> error (DuckDB: "Group index must be between 0 and 9").
    var raised1 = False
    try:
        _ = _extract("abc", "(a)(b)(c)", 10)
    except e:
        raised1 = True
    assert_true(raised1)
    var raised2 = False
    try:
        _ = _extract("abc", "(a)(b)(c)", -1)
    except e:
        raised2 = True
    assert_true(raised2)


# ---------------------------------------------------------------------------
# Case-insensitive.   DuckDB:
#   regexp_matches('ABC','abc','i')=t  regexp_matches('ABC','(?i)abc')=t
#   regexp_matches('ABC','abc')=f  regexp_matches('aBc','a(?i:b)c')=t
# ---------------------------------------------------------------------------

def test_case_insensitive() raises:
    assert_true(_like("ABC", "abc", "i"))
    assert_true(_like("ABC", "(?i)abc"))
    assert_false(_like("ABC", "abc"))
    assert_true(_like("aBc", "a(?i:b)c"))         # scoped (?i:...)
    assert_false(_like("aBc", "a(?-i:b)c", "i"))  # scoped (?-i:...) turns it off
    assert_true(_like("HELLO", "[a-z]+", "i"))    # case-fold a char class
    assert_true(_like("AbC", "(?i)[a-c]+"))


# ---------------------------------------------------------------------------
# Empty pattern / empty input.   DuckDB:
#   regexp_matches('','')=t  regexp_matches('abc','')=t  regexp_matches('','a')=f
# ---------------------------------------------------------------------------

def test_empty() raises:
    assert_true(_like("", ""))
    assert_true(_like("abc", ""))      # empty pattern matches at position 0
    assert_false(_like("", "a"))
    assert_equal(_extract("abc", "", 0), "")   # whole match of '' is the empty string


# ---------------------------------------------------------------------------
# Invalid / unsupported patterns -> error at compile time.   DuckDB:
#   'a**'    -> "bad repetition operator: **"
#   '[a-'    -> "missing ]: [a-"
#   '(a'     -> "missing ): (a"
#   'a{2,1}' -> "invalid repetition size: {2,1}"
#   'a\1'    -> "invalid escape sequence: \1" (backref-in-pattern unsupported)
#   '(?=a)b' -> "invalid perl operator: (?=" (lookahead unsupported)
# ---------------------------------------------------------------------------

def test_invalid_patterns() raises:
    assert_true(_raises("a**"))           # adjacent quantifiers — RE2-class error, NOT treated as `a*`
    assert_true(_raises("a*+"))
    assert_true(_raises("[a-"))           # unterminated char class
    assert_true(_raises("[abc"))
    assert_true(_raises("(a"))            # unbalanced paren (missing ')')
    assert_true(_raises("a)"))            # unbalanced paren (extra ')')
    assert_true(_raises("a{2,1}"))        # m < n
    assert_true(_raises("a\\1"))          # backreference in pattern
    assert_true(_raises("(?=a)b"))        # lookahead
    assert_true(_raises("(?<=a)b"))       # lookbehind
    assert_true(_raises("a\\"))           # trailing backslash
    assert_true(_raises("*abc"))          # nothing to repeat
    # Named groups: `(?P<name>...)` (Python/RE2 style) is LEGAL; the
    # Perl-style `(?<name>...)` is NOT (RE2/DuckDB reject it as a perl operator).
    assert_true(_raises("(?<name>a)"))
    var named_ok = False
    try:
        _ = RegexProgram.compile("(?P<name>a)")
        named_ok = True
    except e:
        named_ok = False
    assert_true(named_ok)
    # And a valid pattern that LOOKS suspect: `(?:a*)*` is legal.
    var ok = False
    try:
        _ = RegexProgram.compile("(?:a*)*")
        ok = True
    except e:
        ok = False
    assert_true(ok)


# ---------------------------------------------------------------------------
# Linear-time guarantee — the classic catastrophic-backtracking input must
# complete immediately (an NFA does it in O(n*prog); a backtracker hangs).
# DuckDB: regexp_matches('a'*50,'(a+)+b')=f.
# ---------------------------------------------------------------------------

def test_linear_time_no_hang() raises:
    var s = String("")
    for _ in range(50):
        s += "a"
    assert_false(_like(s, "(a+)+b"))      # must return (false) without hanging


# ---------------------------------------------------------------------------
# Column kernels + NULL handling.
# ---------------------------------------------------------------------------

def test_kernel_regexp_like_column() raises:
    var arr = StringArray.from_strings(["abc", "xyz", "a1b", "barfoo"])
    var prog = RegexProgram.compile("[0-9]")
    var out = eval_regexp_like(arr, prog)
    assert_equal(len(out), 4)
    assert_false(out.get(0))   # "abc" — no digit
    assert_false(out.get(1))   # "xyz" — no digit
    assert_true(out.get(2))    # "a1b" — has '1'
    assert_false(out.get(3))   # "barfoo" — no digit


def test_kernel_regexp_like_nulls() raises:
    # Build a StringArray with a NULL row -> output bit is NULL.
    var arr = StringArray.from_strings(["foo123", "no digits", ""])
    var vbm = Bitmap.create_all_valid(3)
    vbm.clear(1)                       # row 1 is NULL
    arr.validity = Optional[Bitmap[HeapRegion]](vbm^)
    arr.null_count = 1
    var prog = RegexProgram.compile("\\d+")
    var out = eval_regexp_like(arr, prog)
    assert_true(out.get(0))            # "foo123" has digits
    assert_true(out.is_null(1))        # NULL input -> NULL output
    assert_false(out.get(2))           # "" has no digits


def test_kernel_regexp_extract_column() raises:
    var arr = StringArray.from_strings(["2026-05-11", "no-date-here", "1999-12-31"])
    var prog = RegexProgram.compile("(\\d{4})-(\\d{2})-(\\d{2})")
    var g1 = eval_regexp_extract(arr, prog, 1)
    assert_equal(g1.get(0), "2026")
    assert_equal(g1.get(1), "")        # no match -> ''
    assert_equal(g1.get(2), "1999")
    var g0 = eval_regexp_extract(arr, prog, 0)
    assert_equal(g0.get(0), "2026-05-11")
    assert_equal(g0.get(2), "1999-12-31")


# ---------------------------------------------------------------------------
# Engine dispatch — exercises _eval_predicate / _eval_column_expr (the same
# compute path PipelineCompiler drives) over hand-built RecordBatches +
# Expr.regexp_* nodes.
# ---------------------------------------------------------------------------

def test_engine_regexp_like_predicate() raises:
    var batch = _str_col(["apple", "banana", "cherry", "grape", "fig"])
    # WHERE s ~ '^[ab]'  (starts with 'a' or 'b')
    var e = Expr.regexp_like(Expr.col_idx(0), "^[ab]")
    var mask = _eval_predicate(e, batch)
    assert_equal(len(mask), 5)
    assert_true(mask.get(0))   # apple
    assert_true(mask.get(1))   # banana
    assert_false(mask.get(2))  # cherry
    assert_false(mask.get(3))  # grape
    assert_false(mask.get(4))  # fig
    # WHERE s ~ 'an'  (unanchored — contains 'an')
    var e2 = Expr.regexp_like(Expr.col_idx(0), "an")
    var mask2 = _eval_predicate(e2, batch)
    assert_false(mask2.get(0))  # apple — no 'an'
    assert_true(mask2.get(1))   # banana — 'an'
    assert_false(mask2.get(2))  # cherry — no 'an'
    assert_false(mask2.get(3))  # grape — no 'an'
    assert_false(mask2.get(4))  # fig — no 'an'


def test_engine_regexp_like_predicate_2() raises:
    var batch = _str_col(["a1", "bb", "c3", "dd", "e5"])
    # WHERE s ~ '[0-9]'
    var e = Expr.regexp_like(Expr.col_idx(0), "[0-9]")
    var mask = _eval_predicate(e, batch)
    assert_true(mask.get(0))   # a1
    assert_false(mask.get(1))  # bb
    assert_true(mask.get(2))   # c3
    assert_false(mask.get(3))  # dd
    assert_true(mask.get(4))   # e5
    # Bool-producing regexp_like in a projection (column path).
    var ec = Expr.regexp_like(Expr.col_idx(0), "[0-9]")
    var col = _eval_column_expr(ec, batch)
    assert_equal(col.arrow_type, ArrowType.BOOL)
    var ba = col.as_boolean()
    assert_true(ba.get(0))
    assert_false(ba.get(1))


def test_engine_regexp_extract_projection() raises:
    var batch = _str_col(["key=alpha", "key=beta", "novalue", "key=gamma"])
    # SELECT regexp_extract(s, 'key=(\w+)', 1)
    var e = Expr.regexp_extract(Expr.col_idx(0), "key=(\\w+)", 1)
    var col = _eval_column_expr(e, batch)
    assert_equal(col.arrow_type, ArrowType.STRING)
    var sa = col.as_string()
    assert_equal(sa.get(0), "alpha")
    assert_equal(sa.get(1), "beta")
    assert_equal(sa.get(2), "")       # no match -> ''
    assert_equal(sa.get(3), "gamma")
    # group 0 = whole match.
    var e2 = Expr.regexp_extract(Expr.col_idx(0), "key=(\\w+)", 0)
    var col2 = _eval_column_expr(e2, batch)
    var sa2 = col2.as_string()
    assert_equal(sa2.get(0), "key=alpha")
    assert_equal(sa2.get(2), "")


def test_engine_regexp_extract_in_predicate_raises() raises:
    # regexp_extract produces a non-boolean value -> can't be a predicate.
    var batch = _str_col(["a", "b"])
    var e = Expr.regexp_extract(Expr.col_idx(0), "(a)", 1)
    var raised = False
    try:
        _ = _eval_predicate(e, batch)
    except e2:
        raised = True
    assert_true(raised)


def test_engine_regexp_replace_implemented() raises:
    # regexp_replace uses RE2 \N rewrite syntax.  Full
    # semantics coverage is in test_regexp_replace; this is a smoke test of
    # the _eval_column_expr dispatch arm.  (regexp_match / regexp_split_to_array
    # / regexp_extract_all — see test_regexp_match_family.)
    var batch = _str_col(["abcabc"])
    # SELECT regexp_replace(s, 'a', 'X', 'g') = 'XbcXbc'
    var er = Expr.regexp_replace(Expr.col_idx(0), "a", "X", "g")
    var col = _eval_column_expr(er, batch)
    assert_equal(col.arrow_type, ArrowType.STRING)
    assert_equal(col.as_string().get(0), "XbcXbc")


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
